// GENERATED by `node tooling/i18n/locales.mjs --write` from one ARB per
// SUPPORTED code of tooling/i18n/locales.json:
//   packages/help/lib/l10n/help_en.arb
//   packages/help/lib/l10n/help_ta.arb
//   packages/help/lib/l10n/help_hi.arb
// NEVER HAND-EDIT: tooling/ci/assert-locale-register.mjs fails CI when this file
// and the ARBs disagree.
import 'package:flutter/widgets.dart' show Locale;

/// The locale codes this table carries: the register's supported set, read
/// when the table was rendered.
// locale-list: rendered FROM the register by tooling/i18n/locales.mjs, not typed.
const List<String> kHelpLocaleCodes = <String>['en', 'ta', 'hi'];

/// The help centre strings in one locale.
class HelpStrings {
  const HelpStrings._(this._m);

  final Map<String, String> _m;

  /// The strings for [locale]'s language, or the source locale's.
  static HelpStrings of(Locale locale) =>
      HelpStrings._(_tables[locale.languageCode] ?? _tables['en']!);

  String get helpAccessibility => _m['helpAccessibility']!;

  String get helpArticlesInEnglish => _m['helpArticlesInEnglish']!;

  String get helpAskUs => _m['helpAskUs']!;

  String get helpCentreTitle => _m['helpCentreTitle']!;

  String helpFixedIn(String version) =>
      _m['helpFixedIn']!.replaceAll('{version}', version);

  String get helpKnownIssuesTitle => _m['helpKnownIssuesTitle']!;

  String get helpNoKnownIssues => _m['helpNoKnownIssues']!;

  String get helpNoResults => _m['helpNoResults']!;

  String get helpSearchLabel => _m['helpSearchLabel']!;

  String get helpStillStuck => _m['helpStillStuck']!;
}

const Map<String, Map<String, String>> _tables = <String, Map<String, String>>{
  'en': <String, String>{
    'helpAccessibility': 'Accessibility statement',
    'helpArticlesInEnglish': 'Help articles are in English for now.',
    'helpAskUs': 'Ask us',
    'helpCentreTitle': 'Help',
    'helpFixedIn': 'Fixed in {version}',
    'helpKnownIssuesTitle': 'Known issues',
    'helpNoKnownIssues': 'No known issues',
    'helpNoResults': 'No article matches. Ask us below.',
    'helpSearchLabel': 'Search help',
    'helpStillStuck': 'Still stuck?',
  },
  'ta': <String, String>{
    'helpAccessibility': 'அணுகல்தன்மை அறிக்கை',
    'helpArticlesInEnglish': 'உதவிக் கட்டுரைகள் தற்போது ஆங்கிலத்தில் மட்டும் உள்ளன.',
    'helpAskUs': 'எங்களிடம் கேளுங்கள்',
    'helpCentreTitle': 'உதவி',
    'helpFixedIn': '{version} இல் சரிசெய்யப்பட்டது',
    'helpKnownIssuesTitle': 'அறியப்பட்ட சிக்கல்கள்',
    'helpNoKnownIssues': 'அறியப்பட்ட சிக்கல்கள் இல்லை',
    'helpNoResults': 'பொருந்தும் கட்டுரை இல்லை. கீழே எங்களிடம் கேளுங்கள்.',
    'helpSearchLabel': 'உதவியில் தேடுங்கள்',
    'helpStillStuck': 'இன்னும் சிக்கலா?',
  },
  'hi': <String, String>{
    'helpAccessibility': 'सुलभता विवरण',
    'helpArticlesInEnglish': 'सहायता लेख अभी केवल अंग्रेज़ी में हैं।',
    'helpAskUs': 'हमसे पूछें',
    'helpCentreTitle': 'सहायता',
    'helpFixedIn': '{version} में ठीक किया गया',
    'helpKnownIssuesTitle': 'ज्ञात समस्याएँ',
    'helpNoKnownIssues': 'कोई ज्ञात समस्या नहीं',
    'helpNoResults': 'कोई लेख मेल नहीं खाता। नीचे हमसे पूछें।',
    'helpSearchLabel': 'सहायता में खोजें',
    'helpStillStuck': 'अब भी अटके हैं?',
  },
};
