// GENERATED by `node tooling/i18n/locales.mjs --write` from one ARB per
// SUPPORTED code of tooling/i18n/locales.json:
//   packages/help/lib/l10n/help_en.arb
//   packages/help/lib/l10n/help_ta.arb
//   packages/help/lib/l10n/help_hi.arb
// NEVER HAND-EDIT: tooling/ci/assert-locale-register.mjs fails CI when this file
// and the ARBs disagree.
import 'package:flutter/widgets.dart' show Locale;

/// The locale codes this table carries: the register's supported set, read
/// when the table was rendered.
// locale-list: rendered FROM the register by tooling/i18n/locales.mjs, not typed.
const List<String> kHelpLocaleCodes = <String>['en', 'ta', 'hi'];

/// The help centre strings in one locale.
class HelpStrings {
  const HelpStrings._(this._m);

  final Map<String, String> _m;

  /// The strings for [locale]'s language, or the source locale's.
  static HelpStrings of(Locale locale) =>
      HelpStrings._(_tables[locale.languageCode] ?? _tables['en']!);

  String get helpAccessibility => _m['helpAccessibility']!;

  String get helpArticlesInEnglish => _m['helpArticlesInEnglish']!;

  String get helpAskUs => _m['helpAskUs']!;

  String get helpCentreTitle => _m['helpCentreTitle']!;

  String get helpChatAiLabel => _m['helpChatAiLabel']!;

  String get helpChatAiSemantics => _m['helpChatAiSemantics']!;

  String get helpChatBuyCredits => _m['helpChatBuyCredits']!;

  String get helpChatCopy => _m['helpChatCopy']!;

  String get helpChatNeedsCredits => _m['helpChatNeedsCredits']!;

  String get helpChatNoticeBody => _m['helpChatNoticeBody']!;

  String get helpChatNoticeOk => _m['helpChatNoticeOk']!;

  String get helpChatNoticeTitle => _m['helpChatNoticeTitle']!;

  String get helpChatOutOfScope => _m['helpChatOutOfScope']!;

  String get helpChatQuestionLabel => _m['helpChatQuestionLabel']!;

  String get helpChatSend => _m['helpChatSend']!;

  String get helpChatSources => _m['helpChatSources']!;

  String get helpChatTitle => _m['helpChatTitle']!;

  String get helpChatUnavailable => _m['helpChatUnavailable']!;

  String helpFixedIn(String version) =>
      _m['helpFixedIn']!.replaceAll('{version}', version);

  String get helpKnownIssuesTitle => _m['helpKnownIssuesTitle']!;

  String get helpNoKnownIssues => _m['helpNoKnownIssues']!;

  String get helpNoResults => _m['helpNoResults']!;

  String get helpSearchLabel => _m['helpSearchLabel']!;

  String get helpStillStuck => _m['helpStillStuck']!;
}

const Map<String, Map<String, String>> _tables = <String, Map<String, String>>{
  'en': <String, String>{
    'helpAccessibility': 'Accessibility statement',
    'helpArticlesInEnglish': 'Help articles are in English for now.',
    'helpAskUs': 'Ask us',
    'helpCentreTitle': 'Help',
    'helpChatAiLabel': 'AI',
    'helpChatAiSemantics': 'Answer generated by AI',
    'helpChatBuyCredits': 'See plans and AI credits',
    'helpChatCopy': 'Copy conversation',
    'helpChatNeedsCredits': 'The AI assistant uses AI credits. You have none left.',
    'helpChatNoticeBody': 'This assistant is an AI system. It answers only from our help articles, and its answers can be wrong. To reach a person, use Ask us.',
    'helpChatNoticeOk': 'I understand',
    'helpChatNoticeTitle': 'You are talking to an AI',
    'helpChatOutOfScope': 'I can only answer from our help articles, and none of them covers this. Ask us and a person will reply.',
    'helpChatQuestionLabel': 'Your question',
    'helpChatSend': 'Ask',
    'helpChatSources': 'From these articles:',
    'helpChatTitle': 'Ask the AI assistant',
    'helpChatUnavailable': 'The AI assistant is not available right now. Search the articles, or ask us.',
    'helpFixedIn': 'Fixed in {version}',
    'helpKnownIssuesTitle': 'Known issues',
    'helpNoKnownIssues': 'No known issues',
    'helpNoResults': 'No article matches. Ask us below.',
    'helpSearchLabel': 'Search help',
    'helpStillStuck': 'Still stuck?',
  },
  'ta': <String, String>{
    'helpAccessibility': 'அணுகல்தன்மை அறிக்கை',
    'helpArticlesInEnglish': 'உதவிக் கட்டுரைகள் தற்போது ஆங்கிலத்தில் மட்டும் உள்ளன.',
    'helpAskUs': 'எங்களிடம் கேளுங்கள்',
    'helpCentreTitle': 'உதவி',
    'helpChatAiLabel': 'AI',
    'helpChatAiSemantics': 'AI உருவாக்கிய பதில்',
    'helpChatBuyCredits': 'திட்டங்களையும் AI கிரெடிட்களையும் பார்க்கவும்',
    'helpChatCopy': 'உரையாடலை நகலெடு',
    'helpChatNeedsCredits': 'AI உதவியாளர் AI கிரெடிட்களைப் பயன்படுத்துகிறது. உங்களிடம் எதுவும் மீதமில்லை.',
    'helpChatNoticeBody': 'இந்த உதவியாளர் ஒரு AI அமைப்பு. இது எங்கள் உதவிக் கட்டுரைகளில் இருந்து மட்டுமே பதில் தருகிறது; அதன் பதில்கள் தவறாக இருக்கலாம். ஒரு நபரைத் தொடர்புகொள்ள, எங்களிடம் கேளுங்கள் என்பதைப் பயன்படுத்துங்கள்.',
    'helpChatNoticeOk': 'புரிந்தது',
    'helpChatNoticeTitle': 'நீங்கள் ஒரு AI உடன் பேசுகிறீர்கள்',
    'helpChatOutOfScope': 'எங்கள் உதவிக் கட்டுரைகளில் இருந்து மட்டுமே என்னால் பதில் தர முடியும், அவற்றில் எதுவும் இதைப் பற்றியதல்ல. எங்களிடம் கேளுங்கள், ஒரு நபர் பதில் தருவார்.',
    'helpChatQuestionLabel': 'உங்கள் கேள்வி',
    'helpChatSend': 'கேள்',
    'helpChatSources': 'இந்தக் கட்டுரைகளில் இருந்து:',
    'helpChatTitle': 'AI உதவியாளரிடம் கேளுங்கள்',
    'helpChatUnavailable': 'AI உதவியாளர் இப்போது கிடைக்கவில்லை. கட்டுரைகளில் தேடுங்கள், அல்லது எங்களிடம் கேளுங்கள்.',
    'helpFixedIn': '{version} இல் சரிசெய்யப்பட்டது',
    'helpKnownIssuesTitle': 'அறியப்பட்ட சிக்கல்கள்',
    'helpNoKnownIssues': 'அறியப்பட்ட சிக்கல்கள் இல்லை',
    'helpNoResults': 'பொருந்தும் கட்டுரை இல்லை. கீழே எங்களிடம் கேளுங்கள்.',
    'helpSearchLabel': 'உதவியில் தேடுங்கள்',
    'helpStillStuck': 'இன்னும் சிக்கலா?',
  },
  'hi': <String, String>{
    'helpAccessibility': 'सुलभता विवरण',
    'helpArticlesInEnglish': 'सहायता लेख अभी केवल अंग्रेज़ी में हैं।',
    'helpAskUs': 'हमसे पूछें',
    'helpCentreTitle': 'सहायता',
    'helpChatAiLabel': 'AI',
    'helpChatAiSemantics': 'AI द्वारा तैयार किया गया उत्तर',
    'helpChatBuyCredits': 'प्लान और AI क्रेडिट देखें',
    'helpChatCopy': 'बातचीत कॉपी करें',
    'helpChatNeedsCredits': 'AI सहायक AI क्रेडिट का उपयोग करता है। आपके पास कोई क्रेडिट नहीं बचा है।',
    'helpChatNoticeBody': 'यह सहायक एक AI सिस्टम है। यह केवल हमारे सहायता लेखों से उत्तर देता है, और इसके उत्तर गलत हो सकते हैं। किसी व्यक्ति तक पहुँचने के लिए \'हमसे पूछें\' का उपयोग करें।',
    'helpChatNoticeOk': 'मैं समझ गया/गई',
    'helpChatNoticeTitle': 'आप एक AI से बात कर रहे हैं',
    'helpChatOutOfScope': 'मैं केवल हमारे सहायता लेखों से उत्तर दे सकता हूँ, और उनमें से कोई इसे कवर नहीं करता। हमसे पूछें, कोई व्यक्ति उत्तर देगा।',
    'helpChatQuestionLabel': 'आपका प्रश्न',
    'helpChatSend': 'पूछें',
    'helpChatSources': 'इन लेखों से:',
    'helpChatTitle': 'AI सहायक से पूछें',
    'helpChatUnavailable': 'AI सहायक अभी उपलब्ध नहीं है। लेख खोजें, या हमसे पूछें।',
    'helpFixedIn': '{version} में ठीक किया गया',
    'helpKnownIssuesTitle': 'ज्ञात समस्याएँ',
    'helpNoKnownIssues': 'कोई ज्ञात समस्या नहीं',
    'helpNoResults': 'कोई लेख मेल नहीं खाता। नीचे हमसे पूछें।',
    'helpSearchLabel': 'सहायता में खोजें',
    'helpStillStuck': 'अब भी अटके हैं?',
  },
};
