// Cloudflare Pages Function: POST /api/subscribe
// Stores launch-notify signups in platform_db (Cloudflare D1, APAC) — [ADR 087].
//
// SITE PROMISE: "We store your email address and the time you signed up, and nothing else."
//
// That marker is load-bearing, not decoration: check-site-integrity.mjs requires the
// quoted sentence to appear VERBATIM on a page of the same deploy root. Change what
// this file stores and the site copy has to move with it, or the build fails — the
// promise and the code cannot drift apart quietly.
//
// ── WHY THE RATE-LIMIT KEY IS AN HMAC AND NOT sha256(ip) ─────────────────────
// This endpoint used to key its per-IP counter on a bare `sha256(ip)`. An unsalted
// hash of an IP address is NOT pseudonymisation: the whole IPv4 space is 2^32
// values, so an attacker (or anyone who obtains a KV export) recovers the exact
// address by hashing all of them — minutes on a laptop, and the search space for a
// /24 is 256. On a page whose own privacy policy promises we do not retain network
// identifiers, a reversible one is a re-identification risk, not an abuse guard.
//
// The key is now HMAC-SHA-256 over the address under a secret the attacker does not
// have, so the exhaustive search is not available. See SETUP step 4.
//
// ── WHY THE COUNTER IS A KEY SET AND NOT AN INTEGER ──────────────────────────
// Workers KV has no compare-and-swap and no atomic increment. The previous
// read-parse-increment-write was a LOST-UPDATE race with an unbounded consequence:
// under sustained concurrency every in-flight request reads the same `h` and writes
// `h+1`, so the stored count can sit at `h+1` forever while thousands of requests
// pass — the limit never actually engages.
//
// Instead each attempt writes its OWN key under a per-fingerprint prefix and the
// count is the size of that prefix. Nothing is read-modify-written, so no attempt
// can erase another's, and every attempt is counted exactly once.
//
// ACCEPTED, BOUNDED RACE: requests already in flight when the threshold is crossed
// can still get through, so the effective ceiling is RATE_LIMIT + (concurrent
// in-flight requests for that one fingerprint) rather than exactly RATE_LIMIT.
// KV list is also eventually consistent (up to ~60s), which widens that window.
// The consequence is bounded and cheap: the overshoot is per-fingerprint, every
// key expires within the hour, and a repeated signup for an address already on the
// list writes nothing at all (see the dedup below). Removing the race entirely
// needs a Durable Object — a coordination primitive this site does not otherwise
// need, for a soft anti-spam counter.
//
// SETUP (one time, in the Cloudflare dashboard — Pages project "nikatru" ->
// Settings -> Bindings; there is deliberately no wrangler config for this site):
//   1. D1 database binding, Production:
//         Variable name: PLATFORM_DB
//         D1 database:   platform_db
//      The signup list lives here, in table `signups`
//      (services/platform/migrations/0011_signups.sql, applied by services/platform).
//   2. KV namespace binding, Production:
//         Variable name: SIGNUPS
//         KV namespace:  nikatru-signups
//      Since [ADR 087] (2026-09-15) it holds ONLY the `rl:` rate-limit counter.
//   3. Redeploy (any push) so the bindings take effect.
//   4. 🔑 OWNER ACTION — Settings -> Environment variables and secrets -> Add,
//      as an ENCRYPTED secret (not a plaintext variable):
//         Variable name: SUBSCRIBE_RATE_LIMIT_SALT
//         Value:         32+ random bytes, e.g. `openssl rand -hex 32`
//      Rotating it simply resets the live counters (every key expires within an
//      hour anyway).
//      🔴 WITHOUT THIS SECRET THE PER-IP RATE LIMIT IS OFF — deliberately.
//      The alternative is storing a reversible fingerprint of a visitor's network
//      address, and a weaker anti-spam guard is a smaller harm than that. The
//      honeypot, the address validation and the per-address dedup all still apply.
//      (Measured 2026-09-15: it had never been set in production, so the limit
//      WAS off; the owner set it that day — Private platform-state
//      O-SIGNUP-RATE-LIMIT-OFF.)
//
// Read signups later (counts, never addresses, in anything that is logged):
//   `wrangler d1 execute platform_db --remote --command "SELECT COUNT(*) FROM signups"`.

// 🔴 `_headers` DOES NOT REACH THIS FILE, AND THAT IS DOCUMENTED, NOT A BUG.
// Cloudflare states it for both files: "Custom headers defined in the `_headers`
// file are not applied to responses generated by Pages Functions"
// (developers.cloudflare.com/pages/configuration/headers/, fetched 2026-08-20),
// and the same for `_redirects`
// (developers.cloudflare.com/pages/configuration/redirects/, same date).
//
// Measured 2026-08-21: every one of the site's six security headers was live on
// every static page and ABSENT from every response this endpoint returns — the
// one route on the whole origin that accepts a POST body and writes to KV was
// the only one with no header policy at all. The set below is the subset of
// `sites/nikatru/_headers` that means anything on a JSON API response:
//
//   · nosniff            — the header whose absence lets a browser re-interpret
//                          this JSON as something it can execute.
//   · frame-ancestors    — an API response has no business in a frame; carried
//     + X-Frame-Options    twice because the CSP directive and the legacy header
//                          are honoured by different things.
//   · HSTS               — must be on EVERY response of the origin to be honest:
//                          a host that sets it on documents only still teaches
//                          the browser nothing on the request that carried a
//                          real email address.
//   · Referrer-Policy    — this URL can appear in a Referer on an error page.
//   · CSP default-src 'none' — TIGHTER than the site-wide `'self'`, deliberately:
//                          a JSON document loads nothing, ever, so the honest
//                          policy is the empty one rather than the page policy
//                          copied across.
//
// ⚠️ Every Response constructed in this file must go through this helper, or it
// ships bare. `assert-function-headers.mjs` asserts exactly that, because a
// second `new Response(...)` added later is the way this regresses.
const SECURITY_HEADERS = {
  "x-content-type-options": "nosniff",
  "x-frame-options": "DENY",
  "referrer-policy": "strict-origin-when-cross-origin",
  "strict-transport-security": "max-age=63072000; includeSubDomains; preload",
  "content-security-policy": "default-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'",
};

const json = (obj, status = 200) =>
  new Response(JSON.stringify(obj), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
      ...SECURITY_HEADERS,
    },
  });

const isEmail = (e) =>
  typeof e === "string" &&
  e.length <= 254 &&
  /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);

/** Keyed one-way fingerprint of `text` under `secret`.
 *
 *  HMAC-SHA-256, not a bare digest: the input (an IP address) is drawn from a
 *  space small enough to enumerate, so without a secret the "hash" is a lookup
 *  table away from the plaintext. Truncated to 128 bits because this value is
 *  only ever a KV key prefix — collision resistance at that width is far beyond
 *  what a per-hour abuse counter needs, and a shorter key is a smaller thing to
 *  leak. */
async function fingerprint(secret, text) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const mac = await crypto.subtle.sign("HMAC", key, enc.encode(text));
  return [...new Uint8Array(mac)]
    .slice(0, 16)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const RATE_LIMIT = 12; // max signups per fingerprint per hour
const RATE_WINDOW_SECONDS = 3600;

// ── WHERE THE SIGNUP GOES, AND HOW LONG IT STAYS — [ADR 087], 2026-09-15 ──────
//
// The list moved from the KV namespace `nikatru-signups` (no location control)
// to table `signups` in platform_db, served from Singapore. The owner chose it:
// "Move to D1 in APAC (Recommended)", then "List to D1, counter stays
// (Recommended)" — so the `rl:` counter above stays in KV, unchanged.
//
// 🔴 NO FALLBACK TO KV. If PLATFORM_DB is not bound, the request fails exactly as
// it does when SIGNUPS is not bound (503, below). Writing the list back to KV
// "just in case" would put an email address in the store this move exists to
// leave, silently, on the one day nobody is watching.
//
// RETENTION is 400 days from the ORIGINAL signup time. A D1 table has no expiry,
// so the platform Worker's nightly `retentionSweep` deletes the rows
// (services/platform/src/scheduled.ts `SIGNUPS_RETENTION_DAYS`, register row
// tooling/ops/register.json → retention.d1.platform_db.signups). Why 400 and not
// 365 — a DPDP Rules 2025 Rule 8(3) one-year floor that 365 misses in a leap
// year — is written there, and the full reasoning that stood in this file until
// this change is in its git history.
//
// A repeat signup writes NOTHING: the email is the primary key (COLLATE NOCASE,
// so letter case does not make a second row) and the insert does nothing on
// conflict, so `signed_up_at` stays the first signup's time.
//
// The only statement this Function sends to platform_db.
export const SIGNUP_INSERT =
  "INSERT INTO signups (email, signed_up_at) VALUES (?, ?) ON CONFLICT(email) DO NOTHING";

export async function onRequestPost({ request, env }) {
  let email = "";
  let honeypot = "";

  try {
    const ct = request.headers.get("content-type") || "";
    if (ct.includes("application/json")) {
      const body = await request.json();
      email = (body.email || "").toString().trim();
      honeypot = (body.company || "").toString().trim();
    } else {
      const form = await request.formData();
      email = (form.get("email") || "").toString().trim();
      honeypot = (form.get("company") || "").toString().trim();
    }
  } catch (_) {
    return json({ ok: false, error: "Could not read your submission. Please try again." }, 400);
  }

  // Honeypot: a bot filled the hidden field. Pretend success, store nothing.
  if (honeypot) return json({ ok: true });

  if (!isEmail(email)) {
    return json({ ok: false, error: "Please enter a valid email address." }, 400);
  }

  // Bindings not in place -> fail gracefully (see SETUP above). BOTH are required:
  // the list lives in D1 and the abuse counter in KV. Never a KV fallback.
  if (!env || !env.SIGNUPS || !env.PLATFORM_DB) {
    return json(
      { ok: false, error: "Signups aren't switched on yet. Please try again soon." },
      503
    );
  }

  // --- Abuse guard: soft per-fingerprint rate limit. -------------------------
  // The address is never stored, hashed or otherwise, without the secret; see the
  // header for why an unsalted digest of an IP is not pseudonymous, and why this
  // limb switches OFF rather than degrade to one.
  const ip = request.headers.get("cf-connecting-ip") || "";
  const salt = (env.SUBSCRIBE_RATE_LIMIT_SALT || "").toString();
  if (ip && salt) {
    try {
      const bucket = "rl:" + (await fingerprint(salt, ip)) + ":";
      // `limit` caps the read: we only ever need to know whether the count has
      // reached the ceiling, never how far past it a flood went.
      const seen = await env.SIGNUPS.list({ prefix: bucket, limit: RATE_LIMIT + 1 });
      if (seen.keys.length >= RATE_LIMIT) {
        return json({ ok: false, error: "Too many attempts. Please try again later." }, 429);
      }
      // One key per attempt: an independent write, so no attempt can overwrite
      // another's. Expires within the window, so nothing lingers.
      await env.SIGNUPS.put(bucket + crypto.randomUUID(), "1", {
        expirationTtl: RATE_WINDOW_SECONDS,
      });
    } catch (_) {
      // If the rate-limit check fails, don't block a real signup.
    }
  }

  // --- Store the signup: email + timestamp ONLY. ---
  try {
    const record = { email, ts: new Date().toISOString() };
    await env.PLATFORM_DB.prepare(SIGNUP_INSERT).bind(record.email, record.ts).run();
    return json({ ok: true });
  } catch (_) {
    return json({ ok: false, error: "Something went wrong. Please try again." }, 500);
  }
}

// GET (or a curious visitor) -> 405, so the endpoint never leaks a stack trace.
export async function onRequestGet() {
  return json({ ok: false, error: "Method not allowed. POST an { email } payload." }, 405);
}
