// GENERATED by `node tooling/i18n/locales.mjs --write` from
// tooling/i18n/locales.json. NEVER HAND-EDIT: tooling/ci/assert-locale-register.mjs
// fails CI when this file and the register disagree.
//
// THE ONE LIST OF LANGUAGES the Dart side reads: both Settings pickers offer
// `kSupportedLocales`, and every test that loops over the locales loops over
// `kSupportedLocaleCodes` — so a language added to the register reaches every
// picker and every such test without a hand edit, and one missing an ARB fails
// the guard before it can render English under a native name.
import 'package:flutter/widgets.dart' show Locale;

/// One row of the locale register.
class RegisteredLocale {
  const RegisteredLocale({
    required this.code,
    required this.englishName,
    required this.nativeName,
    required this.script,
    required this.rtl,
    required this.plural,
    required this.supported,
    required this.pseudo,
  });

  /// The BCP-47 tag, e.g. `ta` or `pt-BR`.
  final String code;

  /// The language's name in English (for logs and tooling, never the picker).
  final String englishName;

  /// The language's name in ITSELF — what the picker shows, so a reader finds
  /// their language without first being able to read the current one.
  final String nativeName;

  /// ISO 15924 script code.
  final String script;

  /// Written right to left.
  final bool rtl;

  /// The CLDR cardinal plural categories the language uses.
  final List<String> plural;

  /// Ships everywhere (`status: supported`); false for pending and pseudo rows.
  final bool supported;

  /// A test-only pseudo locale (never shipped, never offered in a picker).
  final bool pseudo;

  /// The [Locale] this row selects.
  Locale get locale => localeOfTag(code);
}

/// The [Locale] a tag names (`ll`, `ll-RR`, `ll-Ssss`, `ll-Ssss-RR`; `_`
/// is read as `-`): the inverse of [Locale.toLanguageTag], which is what a
/// stored or synced language choice holds, so `pt-BR` comes back as pt_BR
/// and never as a bare `pt` (#1161 nit 5).
Locale localeOfTag(String tag) {
  final List<String> parts = tag.split(RegExp('[-_]'));
  final bool scripted = parts.length > 1 && parts[1].length == 4;
  return Locale.fromSubtags(
    languageCode: parts.first,
    scriptCode: scripted ? parts[1] : null,
    countryCode: parts.length > (scripted ? 2 : 1) ? parts.last : null,
  );
}

/// Every row of the register, supported first, then pending, then pseudo.
const List<RegisteredLocale> kLocaleRegister = <RegisteredLocale>[
  RegisteredLocale(
    code: 'en',
    englishName: 'English',
    nativeName: 'English',
    script: 'Latn',
    rtl: false,
    plural: <String>['one', 'other'],
    supported: true,
    pseudo: false,
  ),
  RegisteredLocale(
    code: 'ta',
    englishName: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Taml',
    rtl: false,
    plural: <String>['one', 'other'],
    supported: true,
    pseudo: false,
  ),
  RegisteredLocale(
    code: 'hi',
    englishName: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Deva',
    rtl: false,
    plural: <String>['one', 'other'],
    supported: true,
    pseudo: false,
  ),
  RegisteredLocale(
    code: 'en-XA',
    englishName: 'en-XA',
    nativeName: 'en-XA',
    script: 'Latn',
    rtl: false,
    plural: <String>['one', 'other'],
    supported: false,
    pseudo: true,
  ),
  RegisteredLocale(
    code: 'ar-XB',
    englishName: 'ar-XB',
    nativeName: 'ar-XB',
    script: 'Latn',
    rtl: true,
    plural: <String>['one', 'other'],
    supported: false,
    pseudo: true,
  ),
];

/// The template (source) locale's code.
const String kSourceLocaleCode = 'en';

/// The supported rows, in register order.
final List<RegisteredLocale> kSupportedLocales =
    List<RegisteredLocale>.unmodifiable(
      kLocaleRegister.where((RegisteredLocale r) => r.supported),
    );

/// The supported codes, in register order.
final List<String> kSupportedLocaleCodes = List<String>.unmodifiable(
  kSupportedLocales.map((RegisteredLocale r) => r.code),
);

/// The [Locale] of the supported row whose code is [code] — what a picker
/// stores when a tile is chosen. Throws for a code the register does not
/// support, which a picker built from [kSupportedLocales] cannot hand it.
Locale localeOfCode(String code) =>
    kSupportedLocales.firstWhere((RegisteredLocale r) => r.code == code).locale;

/// The supported codes other than the source locale — the translations.
final List<String> kTranslationLocaleCodes = List<String>.unmodifiable(
  kSupportedLocaleCodes.where((String c) => c != kSourceLocaleCode),
);

/// The test-only pseudo rows (`en-XA` long text, `ar-XB` right to left).
final List<RegisteredLocale> kPseudoLocales =
    List<RegisteredLocale>.unmodifiable(
      kLocaleRegister.where((RegisteredLocale r) => r.pseudo),
    );
