// GENERATED by `node tooling/ci/assert-locale-register.mjs --write` from
// tooling/i18n/locales.json, the locale register. NEVER HAND-EDIT: the guard
// fails CI when this file and the register disagree.
//
// Every surface that needs "which languages do we ship" reads this file: the
// Settings language pickers, the parity tests, the pseudo-locale tests.
import 'package:flutter/widgets.dart' show Locale, TextDirection;

/// One row of the locale register.
class RegisteredLocale {
  /// A register row; only the generated tables below construct one.
  const RegisteredLocale({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.script,
    required this.direction,
    required this.pluralRules,
    required this.supported,
  });

  /// The language code, as the ARB suffix and [Locale.languageCode] spell it.
  final String code;

  /// The English name of the language.
  final String name;

  /// The name in its own script: what the language picker shows, so a
  /// speaker finds their language without reading the current one.
  final String nativeName;

  /// The ISO 15924 script code.
  final String script;

  /// The layout direction the language reads in.
  final TextDirection direction;

  /// The CLDR cardinal plural categories the language uses.
  final List<String> pluralRules;

  /// True when every surface ships it; false while it is registered only.
  final bool supported;

  /// The [Locale] for [code].
  Locale get locale => Locale(code);
}

/// A test-only pseudo-locale: never shipped, never offered by a picker.
class PseudoLocale {
  /// A register pseudo row; only the generated table below constructs one.
  const PseudoLocale({
    required this.languageCode,
    required this.countryCode,
    required this.name,
    required this.direction,
    required this.expansion,
  });

  /// The language half of the tag (`en` of `en-XA`).
  final String languageCode;

  /// The private-use region half of the tag (`XA` of `en-XA`).
  final String countryCode;

  /// What the pseudo-locale is for.
  final String name;

  /// The layout direction the pseudo text is laid out in.
  final TextDirection direction;

  /// How much longer than English the pseudo text is (0.4 = 40%).
  final double expansion;

  /// The [Locale] for this pseudo-locale.
  Locale get locale => Locale(languageCode, countryCode);
}

/// Every registered locale, supported or pending, in register order.
const List<RegisteredLocale> kRegisteredLocales = <RegisteredLocale>[
  RegisteredLocale(
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latn',
    direction: TextDirection.ltr,
    pluralRules: <String>['one', 'other'],
    supported: true,
  ),
  RegisteredLocale(
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Taml',
    direction: TextDirection.ltr,
    pluralRules: <String>['one', 'other'],
    supported: true,
  ),
  RegisteredLocale(
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Deva',
    direction: TextDirection.ltr,
    pluralRules: <String>['one', 'other'],
    supported: true,
  ),
];

/// The locales every surface ships, in register order.
const List<RegisteredLocale> kSupportedLocales = <RegisteredLocale>[
  RegisteredLocale(
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latn',
    direction: TextDirection.ltr,
    pluralRules: <String>['one', 'other'],
    supported: true,
  ),
  RegisteredLocale(
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Taml',
    direction: TextDirection.ltr,
    pluralRules: <String>['one', 'other'],
    supported: true,
  ),
  RegisteredLocale(
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Deva',
    direction: TextDirection.ltr,
    pluralRules: <String>['one', 'other'],
    supported: true,
  ),
];

/// The codes of [kSupportedLocales], in register order.
const List<String> kSupportedLocaleCodes = <String>['en', 'ta', 'hi'];

/// The template language: the ARB every other locale is checked against.
const String kSourceLocaleCode = 'en';

/// The test-only pseudo-locales.
const List<PseudoLocale> kPseudoLocales = <PseudoLocale>[
  PseudoLocale(
    languageCode: 'en',
    countryCode: 'XA',
    name: 'Pseudo (accented, expanded)',
    direction: TextDirection.ltr,
    expansion: 0.4,
  ),
  PseudoLocale(
    languageCode: 'ar',
    countryCode: 'XB',
    name: 'Pseudo (right-to-left)',
    direction: TextDirection.rtl,
    expansion: 0.4,
  ),
];
