// ─────────────────────────────────────────────────────────────────────────────
// THE APEX ROUTER — `nikatru.com/<id>/*` serves the app; everything else is the
// static marketing/legal site, untouched.
//
//   browser → nikatru.com/subscriptiontracker/…
//                │
//                ├─ first path segment in app-routes.json?
//                │     no  → a `*.md` path?  yes → 404          [since 2026-09-22]
//                │                           no  → next()      → sites/nikatru asset
//                │     yes → a document the static site HAS at this path?
//                │             yes → that file (a per-app notice)   [since 2026-09-11]
//                │             no  → fetch(row.origin + rest)  → that app's own Pages project
//                │
//                └─ /apps/subscriptiontracker, /pricing, /privacy, /legal/**  served as before
//
// ── WHY THIS EXISTS [ADR 075] ────────────────────────────────────────────────
// Paddle approves a DOMAIN and says of a subdomain "you will need to have that
// subdomain approved separately"; its overlay enforces AT INIT, against the PAGE
// ORIGIN. So on `<id>.nikatru.com` in-app checkout could not open at all, and
// every new app cost a fresh submission. Razorpay wants a support ticket per
// sub-domain against a ceiling of one main site plus five. Neither conditions
// anything on a PATH. One apex approval, held once, covers app #51.
//
// ── WHY A PAGES FUNCTION AND NOT A ROUTER WORKER ─────────────────────────────
// Both can proxy. The question that decided it was ROLLBACK GRANULARITY, and it
// was settled by measurement on 2026-09-09 rather than by argument:
//
//   · Under this design each app keeps its OWN Direct Upload Pages project with
//     its OWN deployment history. Rolling one app back is
//     `POST /accounts/{a}/pages/projects/{app}/deployments/{id}/rollback`.
//     MEASURED on two throwaway projects: rolling app B back flipped
//     `/appb/version.json` from V2 to V1 while `/subscriptiontracker/version.json` and the
//     ROUTER'S OWN DEPLOYMENT ID were both unchanged. Blast radius: one app.
//   · A router Worker has ONE version history for the whole script
//     (`/workers/scripts/{name}/versions` is script-scoped; there is no
//     per-route version). Rolling it back rolls back the routing for EVERY app
//     at once. Restoring per-app granularity means one Worker plus one zone
//     route PER APP — a Cloudflare console step for app #2, which is exactly
//     the cost this design exists to avoid.
//   · And a Worker on `nikatru.com/*` would put the frozen legal archive behind
//     a Worker. Larger blast radius for a worse rollback story.
//
// A `_redirects` file was never a candidate: Cloudflare Pages supports 3xx and
// SAME-PROJECT 200 rewrites only. There is no proxy-to-another-origin form.
//
// ── THE FAILURE MODE IS `next()`, DELIBERATELY ───────────────────────────────
// 🔴 This file is the only thing between a visitor and `nikatru.com` — marketing,
// pricing, /checkout-return, and the dated consent archive under /legal/. A
// throw here takes all of it dark. So every branch that can fail falls THROUGH
// to the static site rather than erroring: a malformed table, a route row
// missing an origin, an upstream that will not answer. The app path breaks; the
// studio does not.
//
// Two layers of that, and they are different:
//   · BUILD TIME — `app-routes.json` is a static import, so bytes that are not
//     JSON fail the Functions bundle, the Pages build fails, and the PREVIOUS
//     deployment goes on serving. Nothing is published broken.
//   · RUN TIME  — JSON that parses but is the wrong SHAPE (an object, a row with
//     no origin) is caught below and routed to `next()`.
//
// ── WHY THE PROXY TARGET IS *.pages.dev AND NOT <id>.nikatru.com ─────────────
// 🔴 The retired subdomain gets a zone Redirect Rule 301ing it to this path. A
// rule on `<id>.nikatru.com/*` sits in the nikatru.com zone; `*.pages.dev` does
// not. Fetching the pages.dev origin therefore CANNOT be caught by that rule —
// the loop is impossible by construction rather than exempted by a header some
// future rule edit could stop matching. `row.origin` comes from
// `hosts.pagesOrigin` in app.yaml, which is declared because Cloudflare appended
// a suffix when the project name was taken (`subscriptiontracker-7qg.pages.dev`), so
// `<id>.pages.dev` is wrong for exactly the app this repository has.
//
// ── WHAT THIS FILE DOES NOT OWN ──────────────────────────────────────────────
// ⛔ `app-routes.json` is GENERATED by tooling/sites/generate-discovery.mjs from
// `catalog/apps.json`. Never hand-edit it; `site-drift-repair.yml` regenerates
// the discovery surface on every merge and opens a self-merging PR when the
// committed bytes drift, so a hand edit is undone by machinery.
// ⛔ Response headers for an app path. MEASURED 2026-09-09 on a throwaway Pages
// project: `_headers` is applied by the ASSET-serving stage, so it lands on
// `next()` responses and NOT on a response this function returns from a proxy
// fetch. The app's headers are therefore the app's own `apps/<id>/web/_headers`,
// which is what makes a per-app CSP possible at all — and what makes an app with
// NO declared CSP ship with none. See that file.
// ─────────────────────────────────────────────────────────────────────────────
import table from '../app-routes.json';
import { refusedByRouter } from '../../../tooling/sites/served.mjs';

/** Paths the router must never claim, whatever the table says.
 *
 *  🔴 `/.well-known/` is ORIGIN-SCOPED BY SPECIFICATION. `assetlinks.json` and
 *  `apple-app-site-association` are fetched by Android and iOS from the ORIGIN,
 *  never from a path, so on one shared origin they are ONE file for the whole
 *  portfolio and they must be served by the apex itself. Proxying them to an app
 *  would hand one app the deep-link verification of every other app. */
const NEVER_PROXY = ['/.well-known/'];

/** The table, validated once at module scope. Anything that is not an array of
 *  `{path, origin}` rows collapses to an EMPTY table, which makes every request
 *  a `next()` — the site serves, the apps 404 into the marketing 404, and the
 *  drift is loud rather than fatal. */
const routes = (() => {
  try {
    if (!Array.isArray(table)) return [];
    return table.filter(
      (r) =>
        r &&
        typeof r.path === 'string' &&
        /^\/[a-z0-9][a-z0-9_-]*$/.test(r.path) &&
        typeof r.origin === 'string' &&
        r.origin.startsWith('https://'),
    );
  } catch {
    return [];
  }
})();

/** 🔴 THE SECURITY HEADER SET A PROXIED RESPONSE WOULD OTHERWISE HAVE NONE OF.
 *
 *  MEASURED 2026-09-09 on a throwaway Pages project, and independently asserted
 *  by `assert-web-cache-policy.mjs`'s Functions limb: `_headers` is applied by
 *  the ASSET-serving stage, so it lands on a `next()` response and NOT on one
 *  this function returns from a proxy fetch. Without this block the app path
 *  would answer with no header policy at all while every static page on the same
 *  origin carried the full set.
 *
 *  ⚠️ APPLIED ONLY WHERE THE APP DECLARED NOTHING. The app's own bytes come with
 *  the app's own `apps/<id>/web/_headers`, and that file — not this one — is
 *  where a per-app policy belongs: it is the whole reason this design proxies
 *  instead of merging every app into one Pages project, where a single `_headers`
 *  would have to hold the UNION and the weakest policy would apply everywhere.
 *  Overwriting here would take that back. Setting TWO `Content-Security-Policy`
 *  headers would be worse still: browsers enforce the INTERSECTION, so a correct
 *  app policy plus this fallback would block the app in a way neither policy
 *  describes.
 *
 *  The CSP below is therefore a FLOOR for an app that declares none — deliberately
 *  strict, so that an app arriving without a policy fails loudly in its own
 *  console rather than silently inheriting nothing. `apps/subscriptiontracker/web/_headers`
 *  declares the real one, verified live against the running app on 2026-09-09. */
const SECURITY_HEADERS = {
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'DENY',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
  'content-security-policy':
    "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'",
};

/** Every response this function BUILDS goes through here, so each one carries the
 *  floor above. `_headers` never reaches a response this function returns itself
 *  (the header of this file), and that is as true of the Markdown 404 below as it
 *  is of a proxied app response. One constructor, so the set cannot be applied to
 *  one of them and forgotten on the other. */
function floored(body, init) {
  const out = new Response(body, init);
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    if (!out.headers.has(name)) out.headers.set(name, value);
  }
  return out;
}

/** 🔴 THE APEX SERVES NO MARKDOWN.
 *
 *  ⏱ 2026-09-22 — MEASURED against https://nikatru.com: `/README.md` and
 *  `/legal/README.md` answered 200. They are a maintainer's notes about the site,
 *  committed beside the pages because that is where a maintainer reads them, and
 *  Pages publishes every committed file under the root. The owner's answer the
 *  same day: nikatru.com serves no Markdown.
 *
 *  So a path the STATIC SITE would answer is refused here when its last segment
 *  ends `.md` (`refusedByRouter` in tooling/sites/served.mjs — the same rule the
 *  customer-visible retired-name guard reads, so that guard skips exactly the
 *  files this refuses and no others). Refused BEFORE `next()`: the file is never
 *  read, whatever it holds. An app path is not touched — the app's own origin
 *  answers for everything under it.
 *
 *  The import is resolved at BUILD time, like the route table: a bundle that
 *  cannot reach tooling/sites/served.mjs fails the Pages build, and the previous
 *  deployment goes on serving. */
const MARKDOWN_REFUSED = { status: 404, headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' } };

/** 🔴 A STATIC DOCUMENT UNDER AN APP PATH IS SERVED BEFORE THE APP IS ASKED.
 *
 *  ⏱ 2026-09-11 — REVIEW-stores-2026-09-10 #4. tooling/app-yaml/render-privacy.mjs
 *  writes each app's privacy notice to `sites/nikatru/<id>/privacy.html`, and
 *  sitemap.xml, llms.txt and support.html advertise it at `/<id>/privacy` — the
 *  URL a store reviewer opens. This function claimed the WHOLE `/<id>/` prefix,
 *  so that URL answered 200 with the Flutter app shell (measured live 2026-09-10
 *  and again 2026-09-11: 11,336 B, `<base href="/subscriptiontracker/">`), and
 *  the generated notice was served by nothing.
 *
 *  The rule is "the static site wins where it HAS a file", decided by ASKING the
 *  asset stage rather than by a list of paths: a list is a second copy of what the
 *  generator emits, and the next sibling document would be shadowed again the day
 *  it appeared. `next()` and not `env.ASSETS.fetch`, because `_headers` is measured
 *  to land on a `next()` response (the header of this file) — so the notice keeps
 *  the static site's own CSP.
 *
 *  Only DOCUMENT-SHAPED requests are asked about: GET or HEAD, with a last segment
 *  that has no extension or ends `.html`. The app's own bytes (`main.dart.js`,
 *  `assets/…`, `canvaskit/…`) all carry an extension and go straight to the origin
 *  with no extra lookup — and so do `/<id>/` and every directory form, because the
 *  app shell is the app's. A static `index.html` under an app path could therefore
 *  never be served, and tooling/ci/check-site-integrity.mjs fails one by name.
 *
 *  🔴 THIS DEPENDS ON `404.html` EXISTING AT THE SITE ROOT. Without it Pages serves
 *  the project as a single-page app and answers EVERY unknown path 200 with
 *  index.html — so every app deep link would be answered by the marketing home
 *  page. check-site-integrity.mjs runs this function against the tree with that
 *  rule modelled, and fails a root where an app deep link is not proxied. */
function asksStaticFirst(request, url, segment) {
  if (request.method !== 'GET' && request.method !== 'HEAD') return false;
  const rest = url.pathname.slice(segment.length);
  const last = rest.slice(rest.lastIndexOf('/') + 1);
  if (last === '') return false;
  return !last.includes('.') || last.toLowerCase().endsWith('.html');
}

export async function onRequest(context) {
  const { request, next } = context;
  // The static site's answer, when it was asked. Held OUTSIDE the try so a failing
  // proxy falls back to the answer already in hand instead of a second `next()`.
  let local = null;
  try {
    const url = new URL(request.url);

    const neverProxy = NEVER_PROXY.some((prefix) => url.pathname === prefix.slice(0, -1) || url.pathname.startsWith(prefix));
    const segment = `/${url.pathname.split('/')[1] ?? ''}`;
    const row = neverProxy ? null : routes.find((r) => r.path === segment);
    if (!row) return refusedByRouter(url.pathname) ? floored('Not found\n', MARKDOWN_REFUSED) : next();

    // `/subscriptiontracker` → `/subscriptiontracker/`. The build is compiled with `--base-href /<id>/`, so
    // every asset URL in the document is relative to the TRAILING SLASH. Serving
    // the document at the bare path would resolve `main.dart.js` against `/`
    // and 404 every asset — silently, as a blank page. A 301 (not 302): the
    // slashed form is the permanent address, and [ADR 075]'s whole instruction
    // was that a move is a move.
    if (url.pathname === segment) {
      return Response.redirect(`${url.origin}${segment}/${url.search}`, 301);
    }

    if (asksStaticFirst(request, url, segment)) {
      try {
        local = await next();
      } catch {
        local = null; // the asset stage failing must not take the app path down with it
      }
      if (local && (local.ok || local.status === 304)) return local;
      // Pages 308s `/x.html` to `/x` for a file that exists. Relay that hop for a
      // `.html` request ONLY, so `/<id>/privacy.html` reaches the notice as well.
      if (local && (local.status === 301 || local.status === 308) && url.pathname.toLowerCase().endsWith('.html')) {
        return local;
      }
    }

    const rest = url.pathname.slice(segment.length);
    const target = new URL(rest + url.search, row.origin);

    // `redirect: 'manual'` so an upstream 3xx is RELAYED rather than followed
    // here — following it would hide an upstream redirect loop inside a single
    // apex response, and the browser is the right place to see the hop.
    const upstream = await fetch(new Request(target, request), { redirect: 'manual' });
    // The static 404 that was asked for is not the answer; release its body.
    local?.body?.cancel().catch(() => {});
    return floored(upstream.body, upstream);
  } catch {
    // Every failure is the static site, never a 500 on the apex — and when the
    // static site was already asked, its answer IS that fallback.
    return local ?? next();
  }
}
