// GENERATED BY packages/tokens - DO NOT EDIT BY HAND.
// Edit contracts/tokens/dtcg/*.json and run `cd packages/tokens && npm run build`.
//
// This is the NIKATRU COMPANY brand - the palette the company's own websites
// declare - plus the two brand font families and the corner radius. It is NOT
// an app's palette: the app factory is multi-brand and every stamped app
// derives its Material 3 scheme from its own `seed_hex` via
// `ColorScheme.fromSeed`. Do not repaint a screen from these constants; see
// packages/tokens/style-dictionary.config.mjs for why `app_colors.dart` is
// hand-written and is a different palette on purpose.

import 'package:flutter/material.dart';

/// The NIKATRU company brand tokens, light scheme.
class BrandTokens {
  BrandTokens._();

  /// `--ink` in the light palette.
  static const Color ink = Color(0xFF0B1220);

  /// `--ink-2` in the light palette.
  static const Color ink2 = Color(0xFF111C33);

  /// `--primary` in the light palette.
  static const Color primary = Color(0xFF2E6FF2);

  /// `--teal` in the light palette.
  static const Color teal = Color(0xFF17C3A2);

  /// `--bg` in the light palette.
  static const Color bg = Color(0xFFF6F8FC);

  /// `--card` in the light palette.
  static const Color card = Color(0xFFFFFFFF);

  /// `--card-2` in the light palette.
  static const Color card2 = Color(0xFFF8FAFD);

  /// `--text` in the light palette.
  static const Color text = Color(0xFF1E293B);

  /// `--strong` in the light palette.
  static const Color strong = Color(0xFF0B1220);

  /// `--muted` in the light palette.
  static const Color muted = Color(0xFF586275);

  /// `--line` in the light palette.
  static const Color line = Color(0xFFE2E8F0);

  /// `--soft` in the light palette.
  static const Color soft = Color(0xFFF6F8FC);

  /// The display face, used for numerals and headings.
  static const String fontDisplay = 'Space Grotesk';

  /// The body face.
  static const String fontBody = 'Manrope';

  /// The brand corner radius, in logical pixels.
  static const double radius = 16;
}

/// The NIKATRU company brand tokens, dark-scheme overrides.
///
/// Only surfaces and text change; [BrandTokens.ink], [BrandTokens.ink2],
/// [BrandTokens.primary] and [BrandTokens.teal] are shared with the light
/// palette and are deliberately absent here.
class BrandTokensDark {
  BrandTokensDark._();

  /// `--bg` in the dark palette.
  static const Color bg = Color(0xFF0B1220);

  /// `--card` in the dark palette.
  static const Color card = Color(0xFF111C33);

  /// `--card-2` in the dark palette.
  static const Color card2 = Color(0xFF0E1830);

  /// `--text` in the dark palette.
  static const Color text = Color(0xFFC7D2E3);

  /// `--strong` in the dark palette.
  static const Color strong = Color(0xFFF1F5F9);

  /// `--muted` in the dark palette.
  static const Color muted = Color(0xFF93A1BC);

  /// `--line` in the dark palette.
  static const Color line = Color(0xFF22304D);

  /// `--soft` in the dark palette.
  static const Color soft = Color(0xFF0E1830);
}
