// GENERATED by tooling/app-yaml/render.mjs from apps/*/app.yaml `billing.mobileIap.revenuecatAppIds`.
// Do not edit: assert-app-yaml.mjs re-renders this file and fails on any difference.
//
// [ADR 085] decision A (owner, 2026-09-15, "RevenueCat app id per app"): a RevenueCat
// webhook event is routed to the NIKATRU app that declares its `event.app_id`; an id
// no app declares is refused, never guessed. Keys are RevenueCat app ids, values
// are NIKATRU app ids. An empty map means no app has declared mobile IAP yet, so
// every RevenueCat event is refused on decision A.
export const REVENUECAT_APP_IDS: Readonly<Record<string, string>> = {
};
