// GENERATED by tooling/app-yaml/render.mjs from apps/*/app.yaml `billing.mobileIap.storeProducts`
// (kind `app`) and catalog/bundles.json `storeProducts` (kind `bundle`).
// Do not edit: `render.mjs --check` re-renders this file and fails on any difference.
//
// O-IAP-BUNDLE-SALE-UNLOCKS-ONE-APP: src/lib/mor/grant.ts looks a RevenueCat event's
// `product_id` up here, under the app the event was routed to ([ADR 085] A). A `bundle` SKU
// is written to bundle_grants through upsertBundleGrant; an `app` SKU, and a SKU this map
// does not hold, keep the single-app path through store.ts. `store` is null for an app SKU
// (12a lists one id per plan on both stores) and names the rail for a bundle SKU.
export interface StoreSku {
  readonly app: string;
  readonly productId: string;
  readonly kind: 'app' | 'bundle';
  readonly plan: string;
  readonly term: 'subscription' | 'one_time';
  readonly store: string | null;
  readonly featureSet: string | null;
  readonly version: number | null;
}

export const STORE_SKUS: readonly StoreSku[] = [
  { app: "subscriptiontracker", productId: "pro_monthly", kind: "app", plan: "single-monthly", term: "subscription", store: null, featureSet: null, version: null },
  { app: "subscriptiontracker", productId: "pro_yearly", kind: "app", plan: "single-yearly", term: "subscription", store: null, featureSet: null, version: null },
];
