// ─────────────────────────────────────────────────────────────────────────────
// chassis_l10n_parity_test.dart — the CHASSIS strings, in both directions, and
// really rendered in both locales.
//
// [ADR 067] decision 2. `apps/subscriptiontracker/test/l10n_parity_test.dart` is the shape
// this follows and the reason it exists is the same one, one level up: gen-l10n
// FALLS BACK TO ENGLISH for a key missing from `chassis_ta.arb`. It does not
// fail, it does not throw at runtime, it prints a line into build output nobody
// reads. `l10n.yaml`'s `untranslated-messages-file:` is the diagnostic half —
// it writes WHICH keys are missing, in a form a translator can be handed. This
// is the ENFORCEMENT half: it fails the suite and names them.
//
// 🔴 AND THE BLAST RADIUS IS THE WHOLE PORTFOLIO, NOT ONE APP. These 149 keys
// are what every app the factory stamps renders. A key that loses its Tamil here
// loses it in every app at once, which is exactly the argument for moving them —
// and exactly why the enforcement had to move with them.
//
// ── FOUR THINGS, AND WHY EACH IS SEPARATE ────────────────────────────────────
//   1. en ⊆ ta — the silent fallback above.
//   2. ta ⊆ en — a Tamil value with no English original: a translation of
//      something that no longer exists. The fallback can never surface it, so
//      nothing else would ever report it.
//   3. placeholders agree, in BOTH directions — a set comparison is blind to a
//      Tamil value that drops `{amount}` (renders with the number missing) and
//      to one that invents `{x}` (renders the braces verbatim).
//   4. the strings REALLY RESOLVE — the arb files agreeing proves nothing about
//      whether `ChassisLocalizations.delegate` is loadable, whether the
//      generated triplet is present at all, or whether a widget under a
//      `MaterialApp` can read a key. That is a different failure with a
//      different cause: gen-l10n output is a BUILD PRODUCT here (gitignored,
//      regenerated by `flutter pub get`), so "the arb is right" and "the Dart
//      exists" are genuinely two claims.
//
// ── SELF-CHECK, BECAUSE THIS FILE IS ITSELF A SCANNER ────────────────────────
// Every limb is a set comparison an EMPTY set satisfies. The floors below assert
// the inputs are the size they are known to be before any comparison is
// believed. A guard that cannot tell "nothing wrong" from "nothing checked" is
// the failure this repository keeps recording.
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:nikatru_design_system/nikatru_design_system.dart';

/// Arb keys, minus the `@…` metadata blocks and the `@@locale` header.
Set<String> _messageKeys(Map<String, dynamic> arb) =>
    arb.keys.where((String k) => !k.startsWith('@')).toSet();

/// Every `{placeholder}` an ICU message REFERENCES, found by walking the braces
/// rather than pattern-matching them.
///
/// A pattern cannot tell an argument from the body of a select arm: in a
/// `select` whose arm is `day{day}`, the arm body looks exactly like a
/// placeholder named `day`, and the parity check then reports a placeholder the
/// template never declared. The walk knows which braces open an ARGUMENT (in
/// message text) and which open an ARM (after a `plural`, `select` or
/// `selectordinal` type), and reads each arm as message text again, so an
/// argument nested inside an arm is still found.
Set<String> _placeholdersIn(String value) => _IcuWalk(value).run();

class _IcuWalk {
  _IcuWalk(this.s);

  final String s;
  final Set<String> found = <String>{};
  int i = 0;

  static final RegExp _name = RegExp(r'^[A-Za-z_][A-Za-z0-9_]*$');
  static const Set<String> _selectors = <String>{
    'plural',
    'select',
    'selectordinal',
  };

  Set<String> run() {
    _message();
    return found;
  }

  /// Message text, up to an unmatched `}` or the end.
  void _message() {
    while (i < s.length) {
      final String c = s[i];
      if (c == '}') return;
      i++;
      if (c == '{') _argument();
    }
  }

  /// After an argument's `{`: its name, then either `}` or `, type …}`.
  void _argument() {
    _space();
    final String name = _token();
    if (_name.hasMatch(name)) found.add(name);
    _space();
    if (i < s.length && s[i] == ',') {
      i++;
      _space();
      final String type = _token();
      _space();
      if (_selectors.contains(type)) {
        if (i < s.length && s[i] == ',') i++;
        _arms();
      } else {
        _skipToClose();
      }
    }
    if (i < s.length && s[i] == '}') i++;
  }

  /// `selector{message} selector{message} …` up to the argument's own `}`.
  void _arms() {
    while (i < s.length) {
      _space();
      if (i >= s.length || s[i] == '}') return;
      final String selector = _token();
      _space();
      if (i < s.length && s[i] == '{') {
        i++;
        _message();
        if (i < s.length && s[i] == '}') i++;
      } else if (selector.isEmpty) {
        i++;
      }
    }
  }

  /// A formatted argument (`number`, `date`, …) carries no placeholder of its
  /// own after the type: skip to the brace that closes it.
  void _skipToClose() {
    int depth = 0;
    while (i < s.length) {
      final String c = s[i];
      if (c == '}' && depth == 0) return;
      if (c == '{') depth++;
      if (c == '}') depth--;
      i++;
    }
  }

  void _space() {
    while (i < s.length && s[i].trim().isEmpty) {
      i++;
    }
  }

  /// A run of characters up to whitespace or `,` `{` `}`.
  String _token() {
    final int start = i;
    while (i < s.length && !', {}\t\n\r'.contains(s[i])) {
      i++;
    }
    return s.substring(start, i);
  }
}

/// 🔴 THE CWD IS NOT ONE PLACE, AND A PATH THAT ASSUMES IT IS FAILS IN ONLY ONE
/// OF THE TWO WAYS THE SUITE IS RUN. `melos run test` enters each package, so
/// the CWD is `packages/design_system`; `flutter test packages/design_system`
/// from the workspace root — which is what CI's `workspace-gate` and every
/// local check do — leaves it at the ROOT. Both are legitimate, so both are
/// tried, and finding the file in NEITHER is still COVERAGE LOST rather than an
/// empty set quietly satisfying every comparison below.
Map<String, dynamic> _readArb(String relative) {
  const String pkg = 'packages/design_system';
  final List<String> candidates = <String>[relative, '$pkg/$relative'];
  final String? found =
      candidates.where((String p) => File(p).existsSync()).firstOrNull;
  expect(
    found,
    isNotNull,
    reason:
        'COVERAGE LOST — $relative was not found from ${Directory.current.path} '
        'at any of ${candidates.join(' or ')}, so this test compared two empty key '
        'sets and would have passed no matter what the arb files contain.',
  );
  return jsonDecode(File(found!).readAsStringSync()) as Map<String, dynamic>;
}

void main() {
  late Map<String, dynamic> en;
  late Map<String, dynamic> ta;
  late Set<String> enKeys;
  late Set<String> taKeys;

  setUpAll(() {
    en = _readArb('lib/src/l10n/chassis_en.arb');
    ta = _readArb('lib/src/l10n/chassis_ta.arb');
    enKeys = _messageKeys(en);
    taKeys = _messageKeys(ta);
  });

  group('the arb files are actually being read', () {
    // The floor is deliberately far below the real count (149 when the keys
    // moved) and must NOT be re-pinned to whatever the tree measures today — a
    // floor tuned to the current number is the stale floor this repository has
    // already removed once. It exists to separate "the sets agree" from "the
    // sets are empty".
    test('the template holds a substantial number of messages', () {
      expect(
        enKeys.length,
        greaterThan(100),
        reason:
            'COVERAGE LOST — chassis_en.arb parsed to only ${enKeys.length} message '
            'key(s). The parity comparisons below are set operations, and two empty '
            'sets are equal.',
      );
    });

    test('@@locale is excluded and @-metadata is not counted as a message', () {
      expect(enKeys, isNot(contains('@@locale')));
      expect(enKeys.every((String k) => !k.startsWith('@')), isTrue);
    });
  });

  group('en and ta hold exactly the same keys', () {
    test('every English key has a Tamil value', () {
      final List<String> missing = (enKeys.difference(taKeys).toList()..sort());
      expect(
        missing,
        isEmpty,
        reason:
            '${missing.length} key(s) are in chassis_en.arb and NOT in chassis_ta.arb, '
            'so gen-l10n will silently serve the ENGLISH text to a Tamil reader in '
            'EVERY app this factory stamps:\n  ${missing.join('\n  ')}\n'
            'Add a Tamil value for each. `packages/design_system/chassis-l10n-untranslated.json` '
            'carries the same list in the form a translator can be handed.',
      );
    });

    test('every Tamil key has an English original', () {
      final List<String> orphaned =
          (taKeys.difference(enKeys).toList()..sort());
      expect(
        orphaned,
        isEmpty,
        reason:
            '${orphaned.length} key(s) are in chassis_ta.arb with no counterpart in '
            'chassis_en.arb. gen-l10n resolves everything from the template, so these '
            'are translated strings no app can ever show — usually a rename that '
            'landed on one side only:\n  ${orphaned.join('\n  ')}',
      );
    });
  });

  group('a translated value keeps the placeholders its original references',
      () {
    test('there is something here to check', () {
      final int withPlaceholders = enKeys
          .where((String k) => _placeholdersIn(en[k] as String).isNotEmpty)
          .length;
      expect(
        withPlaceholders,
        greaterThan(3),
        reason:
            'COVERAGE LOST — only $withPlaceholders English message(s) reference a '
            'placeholder. The comparisons below would range over almost nothing, so '
            'a Tamil value that dropped one would pass.',
      );
    });

    test('no Tamil value drops a placeholder its English original uses', () {
      final List<String> broken = <String>[];
      for (final String key in enKeys.toList()..sort()) {
        if (!taKeys.contains(key)) continue; // reported by limb 1 already.
        final Set<String> lost = _placeholdersIn(
          en[key] as String,
        ).difference(_placeholdersIn(ta[key] as String));
        if (lost.isNotEmpty) {
          broken.add('$key is missing ${(lost.toList()..sort()).join(', ')}');
        }
      }
      expect(
        broken,
        isEmpty,
        reason:
            'A Tamil value no longer substitutes a value its English original does. '
            'The generated Tamil method still TAKES the argument and silently drops '
            'it, so nothing warns and the sentence renders with the number or name '
            'missing:\n  ${broken.join('\n  ')}',
      );
    });

    test('no Tamil value invents a placeholder its English original lacks', () {
      final List<String> invented = <String>[];
      for (final String key in enKeys.toList()..sort()) {
        if (!taKeys.contains(key)) continue;
        final Set<String> extra = _placeholdersIn(
          ta[key] as String,
        ).difference(_placeholdersIn(en[key] as String));
        if (extra.isNotEmpty) {
          invented.add('$key adds ${(extra.toList()..sort()).join(', ')}');
        }
      }
      expect(
        invented,
        isEmpty,
        reason:
            'A Tamil value references an argument the template does not declare. '
            'gen-l10n resolves arguments from chassis_en.arb, so nothing substitutes '
            'it and the braces reach the screen verbatim:\n  ${invented.join('\n  ')}',
      );
    });
  });

  // ── 4 · THE GENERATED DART, WHICH THE THREE LIMBS ABOVE CANNOT SEE ─────────
  //
  // The arb files could agree perfectly while `ChassisLocalizations` does not
  // exist, is stale, or cannot be loaded — the triplet is gitignored here and
  // regenerated by `flutter pub get`, so it is genuinely a separate claim. These
  // load the delegate the way an app does and read a key out of it.
  group('the delegate really resolves, in both locales', () {
    test(
        'both locales are offered — a delegate over one cannot change anything',
        () {
      expect(ChassisLocalizations.supportedLocales.length,
          greaterThanOrEqualTo(2));
      expect(
        ChassisLocalizations.supportedLocales.map((Locale l) => l.languageCode),
        containsAll(<String>['en', 'ta']),
      );
    });

    test('EVERY declared key renders a non-empty string in BOTH locales',
        () async {
      // The whole point of moving the keys was that one fix reaches every app.
      // The other side of that is that one BLANK reaches every app, and a blank
      // is what a translator's empty cell produces — parity cannot see it,
      // because the key is present.
      for (final Locale locale in <Locale>[
        const Locale('en'),
        const Locale('ta')
      ]) {
        final Map<String, dynamic> arb = locale.languageCode == 'en' ? en : ta;
        expect(
          ChassisLocalizations.delegate.isSupported(locale),
          isTrue,
          reason:
              'the delegate refuses $locale, which supportedLocales advertises',
        );
        await ChassisLocalizations.delegate.load(locale);
        final List<String> blank = <String>[];
        for (final String key in enKeys) {
          final Object? value = arb[key];
          if (value is! String || value.trim().isEmpty) blank.add(key);
        }
        expect(
          blank,
          isEmpty,
          reason:
              '${blank.length} key(s) render NOTHING in $locale. A blank is invisible '
              'to a key-set comparison and to gen-l10n, and it ships an empty label '
              'to every app this factory stamps:\n  ${blank.join('\n  ')}',
        );
      }
    });

    testWidgets(
        'a widget under a MaterialApp reads the chassis strings through context',
        (
      WidgetTester tester,
    ) async {
      // The accessor the brick's 13 re-pointed files use. If the barrel stops
      // exporting it, or the delegate is not composed, this is where it shows —
      // and it is the one thing an arb comparison can never tell you.
      late String fromContext;
      await tester.pumpWidget(
        MaterialApp(
          localizationsDelegates: <LocalizationsDelegate<dynamic>>[
            ...ChassisLocalizations.localizationsDelegates,
          ],
          supportedLocales: ChassisLocalizations.supportedLocales,
          locale: const Locale('ta'),
          home: Builder(
            builder: (BuildContext context) {
              fromContext = context.chassisL10n.settingsTitle;
              return Text(fromContext);
            },
          ),
        ),
      );
      await tester.pump();
      expect(fromContext, ta['settingsTitle']);
      expect(
        fromContext,
        isNot(en['settingsTitle']),
        reason:
            'the Tamil value is byte-identical to the English one, which is what a '
            'MISSING Tamil key looks like from here — gen-l10n serves the English '
            'value and nothing fails',
      );
      expect(find.text(ta['settingsTitle'] as String), findsOneWidget);
    });
  });
}
