#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// indexnow-ping.mjs — [pipeline 12]W-3 *"…and a deploy that changes them
// announces itself (IndexNow ping from CI)"*, built up to the exact line where
// the owner's key is required and not one step past it.
//
// 🔴 WHAT WAS THERE BEFORE THIS FILE: NOTHING. `grep -rn -i indexnow
// .github/workflows/` returned zero hits, and the clause's whole mechanism was a
// sentence in a stage document. The key file is owner-gated (proposed
// OWNER_QUEUE A-11) — but the key gates the LAST step, not the other four, and
// leaving all five unbuilt because one is blocked is how an owner-gated clause
// becomes a permanently unbuilt one. Everything here runs, and is testable,
// with no key in the tree.
//
// ── THE FOUR CANNOT-FAIL DEFECTS THIS IS WRITTEN AGAINST ────────────────────
// W-3's research note recorded that "the ping step fires on change" cannot fail
// as written: a step that exists in a workflow ALWAYS runs, and IndexNow answers
// `202` when the key is unverified — indistinguishable from success — so the
// first version of this step would have pinged with no key and been congratulated
// forever. So:
//
//   1. NO KEY, NO PING, AND A NON-ZERO EXIT. Not a warning. A keyless ping is
//      answered 202 and changes nothing, so a run that "succeeded" would be a
//      permanent false green on the one thing this file exists to do.
//   2. THE KEY FILE MUST CONTAIN THE KEY. IndexNow verifies by fetching
//      `https://<host>/<key>.txt` and comparing its BODY to the submitted key. A
//      file named right and holding the wrong bytes fails verification silently,
//      at the far end, where nothing here would ever see it.
//   3. "ON CHANGE" IS A COMPUTED FACT, NOT A WORKFLOW `paths:` FILTER. A push
//      that touches an unrelated file under the path filter must not ping. The
//      subject is diffed against a base ref, and only the URLs whose `<loc>` is
//      new or whose `<lastmod>` moved are submitted.
//   4. DEFAULT IS DRY RUN. The network call happens only under an explicit
//      `--ping`. A mis-wired workflow that forgets the flag prints what it would
//      have sent and exits 0; it cannot quietly start talking to a third party.
//
// ⚠️ GOOGLE IS NOT A PARTICIPANT. Google ignores IndexNow entirely. What reaches
// Google is the generated sitemap, which is why the generator — not this file —
// is the load-bearing half of W-3, and why this one is allowed to be blocked on
// an owner action without holding the requirement hostage.
//
// Usage:
//   node tooling/sites/indexnow-ping.mjs [--root sites/nikatru] [--base <ref>] [--ping]
//
// Exit 0 = nothing to announce, or announced. 1 = the key is missing/wrong, or
// the endpoint answered something other than 200/202.
// ─────────────────────────────────────────────────────────────────────────────
import { existsSync, readFileSync, statSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { listDir } from '../ci/tree-walk.mjs';

const ENDPOINT = 'https://api.indexnow.org/IndexNow';

/** The key file IndexNow expects at the deploy root: `<key>.txt`, the key being
 *  8–128 hex characters. Matched by SHAPE, never by a name in this repo — the
 *  key is generated by the owner and no code path here fabricates one. */
export const KEY_FILE_RE = /^([0-9a-f]{8,128})\.txt$/i;

/** `<loc>` → `<lastmod>` for a sitemap's bytes. Parsed as BLOCKS, so an entry
 *  with no lastmod cannot shift every later date onto the wrong page — the same
 *  reading check-site-integrity.mjs uses, and for the same recorded reason. */
export function sitemapMap(xml) {
  const out = new Map();
  for (const block of xml.matchAll(/<url\b[^>]*>([\s\S]*?)<\/url\s*>/gi)) {
    const loc = block[1].match(/<loc\s*>\s*([^<\s]+)\s*<\/loc\s*>/i);
    const lastmod = block[1].match(/<lastmod\s*>\s*([^<\s]+)\s*<\/lastmod\s*>/i);
    if (loc) out.set(loc[1].trim(), lastmod ? lastmod[1].trim() : null);
  }
  return out;
}

/** The URLs a deploy actually changed: new `<loc>`s, plus every `<loc>` whose
 *  `<lastmod>` moved. A removed URL is deliberately NOT submitted — IndexNow
 *  announces content to fetch, and asking a crawler to re-fetch a page we just
 *  deleted is a 404 we volunteered for. */
export function changedUrls(beforeXml, afterXml) {
  const before = sitemapMap(beforeXml);
  const after = sitemapMap(afterXml);
  const out = [];
  for (const [loc, lastmod] of after) {
    if (!before.has(loc) || before.get(loc) !== lastmod) out.push(loc);
  }
  return out.sort();
}

function die(lines) {
  console.error(`✗ ${lines[0]}`);
  for (const l of lines.slice(1)) console.error(`    ${l}`);
  process.exit(1);
}

// ── CLI ──────────────────────────────────────────────────────────────────────
// 🔴 EVERYTHING BELOW IS BEHIND `isMain`, and the first version was not. Its own
// test file imports `changedUrls`/`sitemapMap` to exercise them directly, and an
// unguarded body meant `import` RAN THE WHOLE SCRIPT — the test process exited 1
// with "INDEXNOW KEY ABSENT" against the real repository before a single case
// ran. Same shape as `generate-discovery.mjs`, which is guarded for the same
// reason: a file that is both a module and a script owes the check.
const isMain = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isMain) {
const argv = process.argv.slice(2);
const flag = (name, fallback = null) => {
  const at = argv.indexOf(name);
  return at === -1 ? fallback : argv[at + 1];
};
const REPO = resolve(flag('--repo') ?? join(dirname(fileURLToPath(import.meta.url)), '..', '..'));
const ROOT_REL = flag('--root', 'sites/nikatru');
const BASE = flag('--base', 'HEAD~1');
const WILL_PING = argv.includes('--ping');

const git = (args) => spawnSync('git', ['-C', REPO, ...args], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });

const rootAbs = join(REPO, ...ROOT_REL.split('/'));
if (!existsSync(rootAbs) || !statSync(rootAbs).isDirectory()) {
  die([`${ROOT_REL} is not a directory, so there is no deploy root to announce.`]);
}

// ── 3 · did the subject actually change? ────────────────────────────────────
// Computed BEFORE the key is looked for, so an unchanged deploy is a clean exit
// 0 whether or not the owner has done their half. Otherwise every push to an
// unrelated file would fail the lane on a missing key while having nothing to
// announce — a guard that cries wolf is one somebody switches off.
const sitemapRel = `${ROOT_REL}/sitemap.xml`;
const sitemapAbs = join(REPO, ...sitemapRel.split('/'));
if (!existsSync(sitemapAbs)) {
  die([
    `${sitemapRel} does not exist, so there is nothing to announce and nothing to diff.`,
    'Its absence is check-site-integrity.mjs\'s REQUIRED_FILES complaint; this is the second symptom.',
  ]);
}
const after = readFileSync(sitemapAbs, 'utf8');
const baseShow = git(['show', `${BASE}:${sitemapRel}`]);
const before = baseShow.status === 0 ? baseShow.stdout : '';
if (baseShow.status !== 0) {
  console.log(`⬜ ${sitemapRel} does not exist at ${BASE} — treating every URL as new.`);
}
const urls = changedUrls(before, after);

if (urls.length === 0) {
  console.log(
    `ok  indexnow — ${sitemapRel} is unchanged against ${BASE}; nothing to announce, so nothing was sent. ` +
      'A push that touches an unrelated file under the same path filter must not ping, which is why this is ' +
      'a diff of the artifact and not the workflow trigger.',
  );
  process.exit(0);
}

// ── 1 + 2 · the key, and it must be the key ─────────────────────────────────
const keyFiles = listDir(rootAbs).filter((f) => KEY_FILE_RE.test(f));
if (keyFiles.length === 0) {
  die([
    `INDEXNOW KEY ABSENT at ${ROOT_REL} — ${urls.length} URL(s) changed and cannot be announced. [12]W-3e, OWNER_QUEUE A-11 (proposed).`,
    'IndexNow answers 202 to a ping from a host whose key it cannot verify, and 202 is indistinguishable',
    'from success — so pinging anyway would report this lane green forever while announcing nothing.',
    'THE KEY IS OWNER WORK AND NOTHING HERE FABRICATES ONE: generate a 8–128 hex-character key, commit it',
    `as ${ROOT_REL}/<key>.txt containing exactly that key, and this step starts working with no code change.`,
    `Changed URLs that are waiting: ${urls.join(' ')}`,
  ]);
}
if (keyFiles.length > 1) {
  die([
    `${ROOT_REL} ships ${keyFiles.length} IndexNow key files (${keyFiles.join(', ')}), and a ping carries exactly one key.`,
    'Two keys at one deploy root is an old key that was never removed; delete the one that is not in use.',
  ]);
}
const keyFile = keyFiles[0];
const key = keyFile.match(KEY_FILE_RE)[1];
const body = readFileSync(join(rootAbs, keyFile), 'utf8').trim();
if (body !== key) {
  die([
    `${ROOT_REL}/${keyFile} does not contain its own key.`,
    `The file is named for key "${key}" and holds ${JSON.stringify(body.slice(0, 40))}. IndexNow verifies by`,
    'FETCHING that URL and comparing the body to the submitted key, so this fails at the far end — where',
    'nothing in this repository would ever see it, and where the answer is another indistinguishable 202.',
  ]);
}

const host = new URL(urls[0]).host;
const payload = { host, key, keyLocation: `https://${host}/${keyFile}`, urlList: urls };

if (!WILL_PING) {
  console.log(`⬜ DRY RUN (pass --ping to send) — would POST ${ENDPOINT}`);
  console.log(JSON.stringify(payload, null, 2));
  process.exit(0);
}

const res = await fetch(ENDPOINT, {
  method: 'POST',
  headers: { 'Content-Type': 'application/json; charset=utf-8' },
  body: JSON.stringify(payload),
});
if (res.status !== 200 && res.status !== 202) {
  die([
    `IndexNow answered ${res.status} ${res.statusText} for ${urls.length} URL(s) on ${host}.`,
    'Only 200 and 202 are accepted. 400 is a malformed payload, 403 is a key that does not verify, 422 is a',
    'URL that does not belong to the submitted host, 429 is too many requests.',
  ]);
}
console.log(
  `ok  indexnow — ${res.status} for ${urls.length} URL(s) on ${host}: ${urls.join(' ')}` +
    (res.status === 202
      ? '\n    ⚠️ 202 means ACCEPTED FOR PROCESSING, and it is also what an unverified key gets. It is not proof the key verified.'
      : ''),
);
}
