// ─────────────────────────────────────────────────────────────────────────────
// lastmod.mjs — THE ONE ANSWER to "what date does this page's <lastmod> carry".
//
// [pipeline 12]W-3a — *"the sitemap's `lastmod` values come from git history — a
// hand edit fails the drift guard."*
//
// 🔴 WHY ONE SHARED FUNCTION AND NOT TWO IMPLEMENTATIONS. Two things must agree
// about this value, and they run in different places:
//
//   · `tooling/sites/generate-discovery.mjs` WRITES it into
//     `sites/nikatru/sitemap.xml`, which is committed and served byte-for-byte
//     by Cloudflare's Git integration.
//   · `tooling/ci/check-site-integrity.mjs` ASSERTS it, per URL, on EVERY deploy
//     root — including `sites/rajasekarselvam`, which no generator writes.
//
// If the writer and the checker each derived the date their own way, the first
// disagreement would be a permanently red lane whose two messages both looked
// correct. They call this file instead, so they cannot disagree: the value is a
// FUNCTION of the repository state, and both sides evaluate the same function.
//
// ── THE FIXED-POINT PROBLEM, AND WHY THE ANSWER IS NOT `git log` ALONE ───────
// `generate-discovery.mjs`'s header used to record, correctly, that a git-derived
// `<lastmod>` could not be made drift-stable:
//
//     "`git log` on the file is empty on the commit that CREATES it, so the
//      committed bytes and the regenerated bytes would differ, failing the drift
//      diff forever"
//
// That is a real property and this file is the resolution, not a denial of it.
// The sitemap must state the date its subject file WILL carry once the state in
// front of us is committed — and that is knowable without knowing the future:
//
//     the file does not exist at HEAD            → it is being added now   → today
//     its bytes differ from HEAD                 → it is being changed now → today
//     its bytes equal HEAD                       → it last changed when git says
//
// The first two branches are what make the value stable across a `generate →
// commit → CI regenerates → diff` cycle: the generator writes today, the commit
// lands today, and CI (a clean checkout) then reads the same date back out of
// `git log`. The third branch is what makes a STALE value fail — which is the
// whole point, and the state `sites/nikatru/sitemap.xml` was in when this was
// written (six URLs claiming 2026-08-01/03 against a tree whose every page last
// changed 2026-08-04, in `6605cc1`).
//
// ⚠️ THE RESIDUAL, STATED RATHER THAN HIDDEN: generate on one day and commit on
// the next and the dates disagree by one. That surfaces as a named, self-healing
// failure ("regenerate the sitemap and commit"), never as a wrong value shipping
// quietly. There is no way to remove it — the commit's own date does not exist
// until the commit does.
//
// 🔴 ONE DECLARED TIMEZONE, ON BOTH HALVES: UTC (`LASTMOD_TZ` below).
//
// ⏱ 2026-09-23 — O-LASTMOD-READS-TWO-TIMEZONES. Until this date the git half
// read `git log --date=short`, which renders the AUTHOR date in the AUTHOR's
// recorded timezone, and `today()` read the RUNNING machine's local clock. The
// laptop is IST (UTC+5:30) and the CI runner is UTC, so for any commit made
// 00:00–05:30 IST the two halves named different days for the same instant,
// and the date a page carried was a function of which machine recorded the
// commit and which one regenerated. Measured on the pre-fix module with a
// fixture commit at 2026-01-02T01:00+05:30: git half 2026-01-02 under both
// TZ=Asia/Kolkata and TZ=UTC; `today()` at that instant 2026-01-02 under
// Kolkata and 2026-01-01 under UTC.
//
// Now the git half is `--date=format-local:%Y-%m-%d` with `TZ=UTC` fixed in
// the git child's environment, and `today()` reads the UTC components of the
// same clock. The rendered date no longer depends on the machine, the author,
// or the process's own TZ.
//
// WHY UTC AND NOT IST: CI is the arbiter. `check-site-integrity.mjs` and the
// deploy job's sitemap generation run on a UTC runner, and a declared zone equal
// to the arbiter's own clock is one fewer thing that can disagree there. It is
// also the ONLY zone name Git for Windows parses reliably: measured 2026-09-23
// on git 2.54.0.windows.1, `TZ=America/Los_Angeles` fell back to the machine's
// IST and rendered 2026-01-02 for the fixture above, while `TZ=UTC` rendered
// 2026-01-01 — so an IANA name here would silently read the laptop's clock.
// The cost, stated: a page changed 00:00–05:30 IST carries the previous UTC
// day, which is what the committed instant IS in UTC.
//
// ⚠️ SHALLOW CLONES. In a `fetch-depth: 1` checkout every file's `git log -1` is
// the single synthetic root commit, so every URL would resolve to the HEAD date
// and the assertion would pass over a sitemap saying one date for everything —
// exactly the "any generator that touches git satisfies this" failure W-3's own
// research note warned about. Callers MUST refuse a shallow repository;
// `isShallowRepo()` is here so they can, and `check-site-integrity.mjs` treats a
// true answer as COVERAGE LOST.
// ─────────────────────────────────────────────────────────────────────────────
import { spawnSync } from 'node:child_process';

/** The one timezone both halves read — see the header for why it is UTC. */
export const LASTMOD_TZ = 'UTC';

// TZ is fixed on EVERY git child, not only the `log` one, so no git call in
// this file can ever render a date from the machine's zone.
const git = (repoRoot, args) =>
  spawnSync('git', ['-C', repoRoot, ...args], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    env: { ...process.env, TZ: LASTMOD_TZ },
  });

/** True when `repoRoot` is inside a git work tree at all. A fixture tree in
 *  `tmpdir()` is not, and must not be treated as one — every function below
 *  degrades to `today()` there, which keeps a synthetic tree self-consistent
 *  (writer and checker still evaluate the same function on the same day). */
export function isGitRepo(repoRoot) {
  const r = git(repoRoot, ['rev-parse', '--is-inside-work-tree']);
  return r.status === 0 && r.stdout.trim() === 'true';
}

/** True when the checkout is shallow, i.e. `git log` cannot answer "when did
 *  THIS file last change" and answers "at HEAD" for everything. */
export function isShallowRepo(repoRoot) {
  const r = git(repoRoot, ['rev-parse', '--is-shallow-repository']);
  return r.status === 0 && r.stdout.trim() === 'true';
}

/** `YYYY-MM-DD` of the last commit that touched `relPath`, or null when the path
 *  has no history (untracked, or newly added and not yet committed). */
export function gitLastmod(repoRoot, relPath) {
  // `format-local` renders in the CHILD's TZ (fixed to LASTMOD_TZ by `git`
  // above), never in the author's recorded offset — which `--date=short` did.
  const r = git(repoRoot, ['log', '-1', '--date=format-local:%Y-%m-%d', '--format=%ad', '--', relPath]);
  if (r.status !== 0) return null;
  const d = r.stdout.trim();
  return /^\d{4}-\d{2}-\d{2}$/.test(d) ? d : null;
}

/** The file's bytes at HEAD, or null when HEAD does not carry it. Compared
 *  against the bytes that are about to be committed — see the header. */
export function headBytes(repoRoot, relPath) {
  const r = git(repoRoot, ['show', `HEAD:${relPath}`]);
  return r.status === 0 ? r.stdout : null;
}

/** Today, in LASTMOD_TZ (UTC), as `YYYY-MM-DD` — the same rendering
 *  `gitLastmod` gives a commit made at `now`, whatever the machine's zone. */
export function today(now = new Date()) {
  const p = (n) => String(n).padStart(2, '0');
  return `${now.getUTCFullYear()}-${p(now.getUTCMonth() + 1)}-${p(now.getUTCDate())}`;
}

/**
 * The `<lastmod>` the URL served by `relPath` must carry.
 *
 * @param repoRoot     absolute path to the checkout
 * @param relPath      repo-relative, POSIX-separated (e.g. `sites/nikatru/privacy.html`)
 * @param currentBytes the bytes that will be on disk after this run. The
 *                     GENERATOR passes its planned output, so a file it is about
 *                     to rewrite resolves to today on the FIRST run and not on
 *                     the second — without this the generator would not be
 *                     idempotent, and CI's regenerate-and-diff could never be
 *                     green. The GUARD omits it and the working tree is read.
 */
export function lastmodFor(repoRoot, relPath, currentBytes = undefined) {
  if (!isGitRepo(repoRoot)) return today();
  const head = headBytes(repoRoot, relPath);
  if (head === null) return today(); // being added in this commit
  if (currentBytes !== undefined && currentBytes !== head) return today(); // being changed
  if (currentBytes === undefined) {
    // No planned bytes: ask git whether the working tree differs from HEAD.
    const r = git(repoRoot, ['status', '--porcelain', '--', relPath]);
    if (r.status === 0 && r.stdout.trim() !== '') return today();
  }
  return gitLastmod(repoRoot, relPath) ?? today();
}
