import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:nikatru_help/nikatru_help.dart';

// ─────────────────────────────────────────────────────────────────────────────
// The help chat (lane help-ai-chat, Do 1, 5, 6). Each 🔴 case is a red control
// from the brief. No model is called: the transports are fakes.
// ─────────────────────────────────────────────────────────────────────────────

class _Server implements HelpChatTransport {
  _Server(this.reply);
  final HelpChatReply reply;
  int calls = 0;

  @override
  Future<HelpChatReply> ask({
    required String question,
    required String locale,
  }) async {
    calls++;
    return reply;
  }
}

const HelpChatReply _answer = HelpChatReply.answered(
  answer: 'Sign in with the same account on each device.',
  citations: <HelpChatCitation>[
    HelpChatCitation(
      id: 'demo/sync',
      title: 'Sync across devices',
      url: 'https://nikatru.com/help/#demo-sync',
    ),
  ],
  provider: 'anthropic',
  model: 'claude-haiku-4-5',
);

HelpIndex _index() => HelpIndex.fromJson(<String, Object?>{
  'version': 1,
  'locale': 'en',
  'avgdl': 10,
  'docs': <Object?>[
    <String, Object?>{
      'id': 'demo/sync',
      'scope': 'demo',
      'slug': 'sync',
      'title': 'Sync across devices',
      'summary': 'Sign in on each device.',
      'url': '/help/#demo-sync',
      'len': 10,
      'text': 'Sign in with the same account on each device.',
    },
  ],
  'postings': <String, Object?>{
    'sync': <Object?>[
      <Object?>[0, 3],
    ],
    'devic': <Object?>[
      <Object?>[0, 4],
    ],
  },
  'synonyms': <String, Object?>{},
  'knownIssues': <Object?>[],
});

Widget _panel(
  HelpChatTransport t, {
  bool seen = true,
  bool needsCredits = false,
  List<String>? asked,
  List<String>? bought,
}) => MaterialApp(
  home: Scaffold(
    body: SingleChildScrollView(
      child: HelpChatPanel(
        transport: t,
        locale: 'en',
        noticeSeen: seen,
        onNoticeSeen: () async {},
        onAskUs: (String q) => asked?.add(q),
        openUrl: (String u) async {},
        needsCredits: needsCredits,
        onBuyCredits: () => bought?.add('open'),
      ),
    ),
  ),
);

Future<void> _ask(WidgetTester tester, String q) async {
  await tester.enterText(find.byKey(HelpChatKeys.question), q);
  await tester.pump();
  await tester.tap(find.byKey(HelpChatKeys.send));
  await tester.pumpAndSettle();
}

void main() {
  testWidgets(
    '🔴 Art. 50: the first-use notice comes first, and nothing can be asked until it is acknowledged',
    (WidgetTester tester) async {
      final _Server server = _Server(_answer);
      await tester.pumpWidget(_panel(server, seen: false));
      expect(find.byKey(HelpChatKeys.notice), findsOneWidget);
      expect(find.text('You are talking to an AI'), findsOneWidget);
      expect(find.textContaining('can be wrong'), findsOneWidget);
      expect(find.textContaining('Ask us'), findsOneWidget);
      expect(find.byKey(HelpChatKeys.question), findsNothing);
      await tester.tap(find.byKey(HelpChatKeys.noticeOk));
      await tester.pumpAndSettle();
      expect(find.byKey(HelpChatKeys.question), findsOneWidget);
      expect(server.calls, 0);
    },
  );

  testWidgets(
    '🔴 Pro with zero credits: the plan or credit-pack prompt, never a call',
    (WidgetTester tester) async {
      final _Server server = _Server(_answer);
      final List<String> bought = <String>[];
      await tester.pumpWidget(
        _panel(server, needsCredits: true, bought: bought),
      );
      expect(find.byKey(HelpChatKeys.needsCredits), findsOneWidget);
      expect(find.byKey(HelpChatKeys.question), findsNothing);
      await tester.tap(find.byKey(HelpChatKeys.buyCredits));
      expect(bought, <String>['open']);
      expect(server.calls, 0);
    },
  );

  testWidgets(
    '🔴 every answer is labelled AI, announced to a screen reader, and the copied transcript keeps the marker',
    (WidgetTester tester) async {
      final SemanticsHandle handle = tester.ensureSemantics();
      String? copied;
      tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
        SystemChannels.platform,
        (MethodCall call) async {
          if (call.method == 'Clipboard.setData') {
            copied =
                (call.arguments as Map<Object?, Object?>)['text'] as String?;
          }
          return null;
        },
      );
      await tester.pumpWidget(_panel(_Server(_answer)));
      await _ask(tester, 'How do I sync?');
      expect(find.byKey(HelpChatKeys.aiLabel), findsOneWidget);
      expect(
        find.bySemanticsLabel(RegExp('Answer generated by AI')),
        findsOneWidget,
      );
      expect(find.text('Sync across devices'), findsOneWidget);
      await tester.tap(find.byKey(HelpChatKeys.copy));
      await tester.pump();
      expect(copied, contains('generated_by: ai'));
      expect(copied, contains('provider: anthropic'));
      expect(copied, contains('model: claude-haiku-4-5'));
      handle.dispose();
    },
  );

  testWidgets('an out-of-scope question is the scoped refusal with Ask us', (
    WidgetTester tester,
  ) async {
    final List<String> asked = <String>[];
    await tester.pumpWidget(
      _panel(
        _Server(const HelpChatReply.refused(HelpChatRefusal.outOfScope)),
        asked: asked,
      ),
    );
    await _ask(tester, 'What is the weather?');
    expect(find.byKey(HelpChatKeys.refusal), findsOneWidget);
    await tester.tap(find.byKey(HelpChatKeys.askUs));
    expect(asked, <String>['What is the weather?']);
  });

  group('🔴 bring your own key', () {
    test(
      'with a key set, no request reaches our chat route; the grounding is the bundled index',
      () async {
        final _Server ours = _Server(_answer);
        String? sentSystem;
        String? sentInput;
        final ByokHelpChat byok = ByokHelpChat(
          index: _index(),
          scopes: const <String>{'demo'},
          complete: (String system, String input) async {
            sentSystem = system;
            sentInput = input;
            return (
              text: jsonEncode(<String, Object?>{
                'in_scope': true,
                'answer': 'Sign in on each device.',
                'citations': <String>['demo/sync'],
              }),
              provider: 'openai',
              model: 'byok-model',
            );
          },
        );
        // With the own key set, the transport is ALWAYS the key's, never ours.
        final HelpChatTransport picked = helpChatTransportFor(
          const HelpChatGate(
            flagOn: true,
            hasPro: true,
            aiCredits: 5,
            ownKey: true,
          ),
          server: ours,
          byok: byok,
        )!;
        expect(
          helpChatTransportFor(
            const HelpChatGate(flagOn: true, hasPro: true, aiCredits: 5),
            server: ours,
            byok: byok,
          ),
          same(ours),
        );
        final HelpChatReply r = await picked.ask(
          question: 'How do I sync my devices?',
          locale: 'en',
        );
        expect(ours.calls, 0);
        expect(r.answer, 'Sign in on each device.');
        expect(r.citations.single.url, 'https://nikatru.com/help/#demo-sync');
        expect(r.provider, 'openai');
        expect(sentSystem, kHelpChatSystem);
        expect(
          (jsonDecode(sentInput!) as Map<String, Object?>)['articles'],
          isNotEmpty,
        );
      },
    );

    test(
      'a key-side answer citing an article it was not given is refused',
      () async {
        final ByokHelpChat byok = ByokHelpChat(
          index: _index(),
          scopes: const <String>{'demo'},
          complete: (String s, String i) async => (
            text: jsonEncode(<String, Object?>{
              'in_scope': true,
              'answer': 'Yes.',
              'citations': <String>['other/article'],
            }),
            provider: 'openai',
            model: 'm',
          ),
        );
        final HelpChatReply r = await byok.ask(
          question: 'How do I sync my devices?',
          locale: 'en',
        );
        expect(r.refusal, HelpChatRefusal.unavailable);
      },
    );
  });

  test(
    'the route\'s answer becomes a reply only with the Art. 50 marker; every refusal maps',
    () async {
      final List<Map<String, Object?>> sent = <Map<String, Object?>>[];
      final ServerHelpChat chat = ServerHelpChat(
        appId: 'demo',
        post: (String path, Map<String, Object?> body) async {
          expect(path, '/v1/ai/help-chat');
          sent.add(body);
          return (
            status: 200,
            body: <String, Object?>{
              'generated_by': 'ai',
              'provenance': <String, Object?>{
                'generator': 'ai',
                'provider': 'anthropic',
                'model': 'claude-haiku-4-5',
                'at': 'x',
              },
              'answer': 'Sign in on each device.',
              'citations': <Object?>[
                <String, Object?>{
                  'id': 'demo/sync',
                  'title': 'Sync',
                  'url': 'https://nikatru.com/help/#demo-sync',
                },
              ],
            },
          );
        },
      );
      final HelpChatReply r = await chat.ask(
        question: 'How do I sync?',
        locale: 'en',
      );
      expect(r.answer, 'Sign in on each device.');
      expect(sent.single, <String, Object?>{
        'app_id': 'demo',
        'question': 'How do I sync?',
        'locale': 'en',
      });
      // 🔴 an answer WITHOUT the marker is not shown.
      expect(
        helpChatReplyFromWire(200, <String, Object?>{
          'answer': 'x',
          'citations': <Object?>[],
          'provenance': <String, Object?>{},
        }).answer,
        isNull,
      );
      expect(
        helpChatReplyFromWire(200, <String, Object?>{
          'refusal': 'out_of_scope',
          'ask_us': true,
        }).refusal,
        HelpChatRefusal.outOfScope,
      );
      expect(
        helpChatReplyFromWire(402, <String, Object?>{
          'error': 'ai_requires_plan',
        }).refusal,
        HelpChatRefusal.needsPlan,
      );
      expect(
        helpChatReplyFromWire(402, <String, Object?>{
          'error': 'ai_credits_exhausted',
        }).refusal,
        HelpChatRefusal.needsCredits,
      );
      expect(
        helpChatReplyFromWire(403, null).refusal,
        HelpChatRefusal.needsConsent,
      );
      expect(
        helpChatReplyFromWire(503, null).refusal,
        HelpChatRefusal.unavailable,
      );
    },
  );
}
