// ─────────────────────────────────────────────────────────────────────────────
// names-hi.mjs — the Hindi (Devanagari) display name of every service in
// make-recipe.mjs's SERVICES table, keyed by service id.
//
// Same rule as the Tamil column: a brand is TRANSLITERATED into the script, never
// translated (prompt in make-recipe.mjs promptFor). Added 2026-10-02 by the i18n
// pipeline so the catalogue ships every supported locale of tooling/i18n/
// locales.json — before it, a Hindi reader saw the catalogue in English.
//
// Agent-produced and UNREVIEWED by a native reader, like every agent-produced
// translation in this tree unless a row says otherwise. make-recipe.mjs refuses a
// render when a service id has no entry here, or an entry names no service.
// ─────────────────────────────────────────────────────────────────────────────
export const HI_NAMES = Object.freeze({
  netflix: 'नेटफ़्लिक्स',
  amazon_prime: 'अमेज़न प्राइम',
  jiohotstar: 'जियोहॉटस्टार',
  spotify: 'स्पॉटिफ़ाई',
  youtube_premium: 'यूट्यूब प्रीमियम',
  apple_music: 'ऐपल म्यूज़िक',
  apple_tv_plus: 'ऐपल टीवी+',
  icloud_plus: 'आईक्लाउड+',
  google_one: 'गूगल वन',
  sonyliv: 'सोनीलिव',
  zee5: 'ज़ी5',
  jiosaavn: 'जियोसावन',
  gaana: 'गाना',
  audible: 'ऑडिबल',
  kindle_unlimited: 'किंडल अनलिमिटेड',
  microsoft_365: 'माइक्रोसॉफ़्ट 365',
  adobe_creative_cloud: 'अडोबी क्रिएटिव क्लाउड',
  canva: 'कैनवा',
  chatgpt_plus: 'चैटजीपीटी प्लस',
  dropbox: 'ड्रॉपबॉक्स',
  notion: 'नोशन',
  linkedin_premium: 'लिंक्डइन प्रीमियम',
  duolingo: 'डुओलिंगो',
  swiggy_one: 'स्विगी वन',
  zomato_gold: 'ज़ोमैटो गोल्ड',
  zepto_pass: 'ज़ेप्टो पास',
  times_prime: 'टाइम्स प्राइम',
  tinder: 'टिंडर',
  xbox_game_pass: 'एक्सबॉक्स गेम पास',
  playstation_plus: 'प्लेस्टेशन प्लस',
  nintendo_switch_online: 'निंटेंडो स्विच ऑनलाइन',
  crunchyroll: 'क्रंचीरोल',
  hulu: 'हुलु',
  the_hindu: 'द हिंदू',
  cultpass: 'कल्टपास',
  prime_video: 'प्राइम वीडियो',
  sun_nxt: 'सन नेक्स्ट',
  aha: 'आहा',
  hoichoi: 'होइचोई',
  discovery_plus: 'डिस्कवरी+',
  lionsgate_play: 'लायंसगेट प्ले',
  shemaroome: 'शेमारूमी',
  manorama_max: 'मनोरमामैक्स',
  fancode: 'फ़ैनकोड',
  tata_play: 'टाटा प्ले',
  tata_play_binge: 'टाटा प्ले बिंज',
  airtel_xstream_play: 'एयरटेल एक्सस्ट्रीम प्ले',
  dish_tv: 'डिश टीवी',
  sun_direct: 'सन डायरेक्ट',
  mubi: 'मूबी',
  jio_postpaid: 'जियो पोस्टपेड',
  jio_prepaid: 'जियो प्रीपेड',
  jiofiber: 'जियोफ़ाइबर',
  airtel_postpaid: 'एयरटेल पोस्टपेड',
  airtel_prepaid: 'एयरटेल प्रीपेड',
  airtel_xstream_fiber: 'एयरटेल एक्सस्ट्रीम फ़ाइबर',
  airtel_black: 'एयरटेल ब्लैक',
  vi_postpaid: 'वीआई पोस्टपेड',
  vi_prepaid: 'वीआई प्रीपेड',
  bsnl: 'बीएसएनएल',
  act_fibernet: 'एसीटी फ़ाइबरनेट',
  hathway: 'हैथवे',
  excitel: 'एक्साइटेल',
  amazon_music: 'अमेज़न म्यूज़िक अनलिमिटेड',
  youtube_music: 'यूट्यूब म्यूज़िक',
  hungama_music: 'हंगामा म्यूज़िक',
  pocket_fm: 'पॉकेट एफ़एम',
  kuku_fm: 'कुकू एफ़एम',
  storytel: 'स्टोरीटेल',
  magzter_gold: 'मैगज़्टर गोल्ड',
  flipkart_vip: 'फ़्लिपकार्ट वीआईपी',
  eazydiner_prime: 'ईज़ीडाइनर प्राइम',
  country_delight: 'कंट्री डिलाइट',
  pharmeasy_plus: 'फ़ार्मईज़ी प्लस',
  tata_1mg_care: 'टाटा 1एमजी केयर प्लान',
  practo_plus: 'प्रैक्टो प्लस',
  healthifyme: 'हेल्दीफ़ाईमी',
  fittr: 'फ़िटर',
  toi_plus: 'टीओआई+',
  indian_express: 'द इंडियन एक्सप्रेस',
  et_prime: 'ईटी प्राइम',
  mint: 'मिंट',
  business_standard: 'बिज़नेस स्टैंडर्ड',
  the_ken: 'द केन',
  moneycontrol_pro: 'मनीकंट्रोल प्रो',
  byjus: 'बायजूस',
  unacademy: 'अनएकेडमी',
  physics_wallah: 'फ़िज़िक्स वाला',
  vedantu: 'वेदांतु',
  testbook_pass: 'टेस्टबुक पास',
  naukri_fastforward: 'नौकरी फ़ास्टफ़ॉरवर्ड',
  tallyprime: 'टैलीप्राइम',
  quick_heal: 'क्विक हील',
  aisle: 'आइल',
  shaadi: 'शादी.कॉम',
  bharat_matrimony: 'भारतमैट्रिमोनी',
  tamil_matrimony: 'तमिलमैट्रिमोनी',
  jeevansathi: 'जीवनसाथी',
  truecaller_premium: 'ट्रूकॉलर प्रीमियम',
  zoho_mail: 'ज़ोहो मेल',
  zoho_workplace: 'ज़ोहो वर्कप्लेस',
  zoho_books: 'ज़ोहो बुक्स',
  disney_plus: 'डिज़्नी+',
  hbo_max: 'एचबीओ मैक्स',
  paramount_plus: 'पैरामाउंट+',
  peacock: 'पीकॉक',
  espn_plus: 'ईएसपीएन+',
  dazn: 'डैज़न',
  sling_tv: 'स्लिंग टीवी',
  youtube_tv: 'यूट्यूब टीवी',
  fubo: 'फ़ूबो',
  starz: 'स्टार्ज़',
  curiositystream: 'क्यूरियोसिटीस्ट्रीम',
  britbox: 'ब्रिटबॉक्स',
  nebula: 'नेबुला',
  f1_tv: 'एफ़1 टीवी',
  snapchat_plus: 'स्नैपचैट+',
  apple_one: 'ऐपल वन',
  tidal: 'टाइडल',
  deezer: 'डीज़र',
  soundcloud_go: 'साउंडक्लाउड गो+',
  ea_play: 'ईए प्ले',
  ubisoft_plus: 'यूबीसॉफ़्ट+',
  apple_arcade: 'ऐपल आर्केड',
  google_play_pass: 'गूगल प्ले पास',
  geforce_now: 'जीफ़ोर्स नाउ',
  discord_nitro: 'डिस्कॉर्ड नाइट्रो',
  humble_choice: 'हंबल चॉइस',
  roblox_premium: 'रोब्लॉक्स प्रीमियम',
  pcloud: 'पीक्लाउड',
  mega: 'मेगा',
  box: 'बॉक्स',
  backblaze: 'बैकब्लेज़',
  aws: 'अमेज़न वेब सर्विसेज़',
  digitalocean: 'डिजिटलओशन',
  cloudflare: 'क्लाउडफ़्लेयर',
  godaddy: 'गोडैडी',
  hostinger: 'होस्टिंगर',
  claude_pro: 'क्लॉड प्रो',
  google_ai_pro: 'गूगल एआई प्रो',
  perplexity_pro: 'परप्लेक्सिटी प्रो',
  midjourney: 'मिडजर्नी',
  copilot_pro: 'कोपायलट प्रो',
  github_copilot: 'गिटहब कोपायलट',
  cursor: 'कर्सर',
  elevenlabs: 'इलेवनलैब्स',
  github: 'गिटहब',
  google_workspace: 'गूगल वर्कस्पेस',
  slack: 'स्लैक',
  zoom: 'ज़ूम',
  figma: 'फ़िग्मा',
  grammarly: 'ग्रामरली',
  evernote: 'एवरनोट',
  todoist: 'टूडूइस्ट',
  adobe_acrobat: 'अडोबी एक्रोबैट',
  adobe_lightroom: 'अडोबी लाइटरूम',
  onepassword: '1पासवर्ड',
  bitwarden: 'बिटवार्डन',
  proton_unlimited: 'प्रोटॉन अनलिमिटेड',
  nordvpn: 'नॉर्डवीपीएन',
  expressvpn: 'एक्सप्रेसवीपीएन',
  surfshark: 'सर्फ़शार्क',
  norton_360: 'नॉर्टन 360',
  mcafee: 'मैकेफ़ी',
  wix: 'विक्स',
  squarespace: 'स्क्वेयरस्पेस',
  shopify: 'शॉपिफ़ाई',
  telegram_premium: 'टेलीग्राम प्रीमियम',
  meta_verified: 'मेटा वेरिफ़ाइड',
  x_premium: 'एक्स प्रीमियम',
  bumble: 'बम्बल',
  hinge: 'हिंज',
  coursera_plus: 'कोर्सेरा प्लस',
  udemy_personal_plan: 'यूडेमी पर्सनल प्लान',
  skillshare: 'स्किलशेयर',
  masterclass: 'मास्टरक्लास',
  brilliant: 'ब्रिलियंट',
  babbel: 'बैबल',
  linkedin_learning: 'लिंक्डइन लर्निंग',
  everand: 'एवरैंड',
  blinkist: 'ब्लिंकिस्ट',
  nytimes: 'द न्यूयॉर्क टाइम्स',
  wsj: 'द वॉल स्ट्रीट जर्नल',
  washington_post: 'द वॉशिंगटन पोस्ट',
  the_economist: 'द इकोनॉमिस्ट',
  financial_times: 'फ़ाइनेंशियल टाइम्स',
  medium: 'मीडियम',
  strava: 'स्ट्रावा',
  peloton_app: 'पेलोटन ऐप',
  fitbit_premium: 'फ़िटबिट प्रीमियम',
  apple_fitness_plus: 'ऐपल फ़िटनेस+',
  headspace: 'हेडस्पेस',
  calm: 'काम',
  myfitnesspal: 'माईफ़िटनेसपाल प्रीमियम',
  whoop: 'हूप',
  anytime_fitness: 'एनीटाइम फ़िटनेस',
  uber_one: 'ऊबर वन',
  dashpass: 'डैशपास',
  instacart_plus: 'इंस्टाकार्ट+',
  hellofresh: 'हेलोफ़्रेश',
  walmart_plus: 'वॉलमार्ट+',
  costco: 'कॉस्टको मेंबरशिप',
});
