// GENERATED by `node tooling/i18n/locales.mjs --write` from one ARB per
// SUPPORTED code of tooling/i18n/locales.json:
//   packages/feedback/lib/l10n/feedback_en.arb
//   packages/feedback/lib/l10n/feedback_ta.arb
//   packages/feedback/lib/l10n/feedback_hi.arb
// NEVER HAND-EDIT: tooling/ci/assert-locale-register.mjs fails CI when this file
// and the ARBs disagree.
import 'package:flutter/widgets.dart' show Locale;

/// The locale codes this table carries: the register's supported set, read
/// when the table was rendered.
// locale-list: rendered FROM the register by tooling/i18n/locales.mjs, not typed.
const List<String> kFeedbackLocaleCodes = <String>['en', 'ta', 'hi'];

/// The "Report a problem" strings in one locale.
class FeedbackStrings {
  const FeedbackStrings._(this._m);

  final Map<String, String> _m;

  /// The strings for [locale]'s language, or the source locale's.
  static FeedbackStrings of(Locale locale) =>
      FeedbackStrings._(_tables[locale.languageCode] ?? _tables['en']!);

  String get attachScreenshot => _m['attachScreenshot']!;

  String get categoryAccessibility => _m['categoryAccessibility']!;

  String get categoryBilling => _m['categoryBilling']!;

  String get categoryBug => _m['categoryBug']!;

  String get categoryCrash => _m['categoryCrash']!;

  String get categoryLabel => _m['categoryLabel']!;

  String get categoryOther => _m['categoryOther']!;

  String get categoryQuestion => _m['categoryQuestion']!;

  String get categoryTranslation => _m['categoryTranslation']!;

  String get close => _m['close']!;

  String get contactEmailLabel => _m['contactEmailLabel']!;

  String get descriptionLabel => _m['descriptionLabel']!;

  String get descriptionRequired => _m['descriptionRequired']!;

  String get emailSupport => _m['emailSupport']!;

  String get includeLogs => _m['includeLogs']!;

  String get markupBlur => _m['markupBlur']!;

  String get markupDone => _m['markupDone']!;

  String get markupDraw => _m['markupDraw']!;

  String get markupHighlight => _m['markupHighlight']!;

  String get markupScreenshot => _m['markupScreenshot']!;

  String get markupUndo => _m['markupUndo']!;

  String get notifyConsent => _m['notifyConsent']!;

  String get previewTitle => _m['previewTitle']!;

  String get queuedBody => _m['queuedBody']!;

  String get refusedBody => _m['refusedBody']!;

  String get replyConsent => _m['replyConsent']!;

  String get reportProblem => _m['reportProblem']!;

  String get screenshotBlurNote => _m['screenshotBlurNote']!;

  String get send => _m['send']!;

  String get sending => _m['sending']!;

  String sentBody(String id) =>
      _m['sentBody']!.replaceAll('{id}', id);

  String get stepsLabel => _m['stepsLabel']!;
}

const Map<String, Map<String, String>> _tables = <String, Map<String, String>>{
  'en': <String, String>{
    'attachScreenshot': 'Attach a screenshot of the screen you were on',
    'categoryAccessibility': 'Accessibility',
    'categoryBilling': 'Billing or payment',
    'categoryBug': 'Something isn\'t working',
    'categoryCrash': 'The app crashed',
    'categoryLabel': 'What kind of problem?',
    'categoryOther': 'Something else',
    'categoryQuestion': 'A question',
    'categoryTranslation': 'Wrong or missing translation',
    'close': 'Close',
    'contactEmailLabel': 'Your email address',
    'descriptionLabel': 'What happened?',
    'descriptionRequired': 'Please describe the problem.',
    'emailSupport': 'Email support instead',
    'includeLogs': 'Include recent app logs (personal details removed)',
    'markupBlur': 'Blur',
    'markupDone': 'Done',
    'markupDraw': 'Draw',
    'markupHighlight': 'Highlight',
    'markupScreenshot': 'Mark up the screenshot',
    'markupUndo': 'Undo',
    'notifyConsent': 'Tell me when it is fixed',
    'previewTitle': 'Exactly what will be sent',
    'queuedBody': 'You are offline. Your report is saved on this device and will be sent once, when you are back online.',
    'refusedBody': 'Your report could not be sent. You can email support instead.',
    'replyConsent': 'You may reply to me',
    'reportProblem': 'Report a problem',
    'screenshotBlurNote': 'Text fields and private details are blurred before anything is sent. You can blur more, but you cannot remove the blur.',
    'send': 'Send report',
    'sending': 'Sending…',
    'sentBody': 'Thank you. Your report number is {id}.',
    'stepsLabel': 'Steps to make it happen again (optional)',
  },
  'ta': <String, String>{
    'attachScreenshot': 'நீங்கள் இருந்த திரையின் திரைப்பிடிப்பை இணைக்கவும்',
    'categoryAccessibility': 'அணுகல்தன்மை',
    'categoryBilling': 'கட்டணம் அல்லது பணம் செலுத்துதல்',
    'categoryBug': 'ஏதோ வேலை செய்யவில்லை',
    'categoryCrash': 'செயலி நின்றுவிட்டது',
    'categoryLabel': 'எந்த வகையான சிக்கல்?',
    'categoryOther': 'வேறு ஏதாவது',
    'categoryQuestion': 'ஒரு கேள்வி',
    'categoryTranslation': 'தவறான அல்லது விடுபட்ட மொழிபெயர்ப்பு',
    'close': 'மூடு',
    'contactEmailLabel': 'உங்கள் மின்னஞ்சல் முகவரி',
    'descriptionLabel': 'என்ன நடந்தது?',
    'descriptionRequired': 'சிக்கலை விவரிக்கவும்.',
    'emailSupport': 'அதற்குப் பதிலாக ஆதரவுக்கு மின்னஞ்சல் அனுப்பு',
    'includeLogs': 'சமீபத்திய செயலிப் பதிவுகளைச் சேர்க்கவும் (தனிப்பட்ட விவரங்கள் நீக்கப்பட்டவை)',
    'markupBlur': 'மங்கலாக்கு',
    'markupDone': 'முடிந்தது',
    'markupDraw': 'வரை',
    'markupHighlight': 'முன்னிலைப்படுத்து',
    'markupScreenshot': 'திரைப்பிடிப்பில் குறியிடவும்',
    'markupUndo': 'செயல்தவிர்',
    'notifyConsent': 'சரிசெய்யப்பட்டதும் எனக்குத் தெரிவிக்கவும்',
    'previewTitle': 'சரியாக அனுப்பப்படுவது இதுதான்',
    'queuedBody': 'நீங்கள் இணைப்பில் இல்லை. உங்கள் புகார் இந்தச் சாதனத்தில் சேமிக்கப்பட்டுள்ளது, மீண்டும் இணைப்பில் வந்ததும் ஒருமுறை அனுப்பப்படும்.',
    'refusedBody': 'உங்கள் புகாரை அனுப்ப முடியவில்லை. அதற்குப் பதிலாக ஆதரவுக்கு மின்னஞ்சல் அனுப்பலாம்.',
    'replyConsent': 'நீங்கள் எனக்குப் பதிலளிக்கலாம்',
    'reportProblem': 'சிக்கலைப் புகாரளி',
    'screenshotBlurNote': 'எதையும் அனுப்பும் முன் உரைப் புலங்களும் தனிப்பட்ட விவரங்களும் மங்கலாக்கப்படும். நீங்கள் மேலும் மங்கலாக்கலாம், ஆனால் மங்கலை நீக்க முடியாது.',
    'send': 'புகாரை அனுப்பு',
    'sending': 'அனுப்பப்படுகிறது…',
    'sentBody': 'நன்றி. உங்கள் புகார் எண் {id}.',
    'stepsLabel': 'இது மீண்டும் நிகழும் படிகள் (விருப்பத்தேர்வு)',
  },
  'hi': <String, String>{
    'attachScreenshot': 'जिस स्क्रीन पर आप थे, उसका स्क्रीनशॉट जोड़ें',
    'categoryAccessibility': 'सुगम्यता',
    'categoryBilling': 'बिलिंग या भुगतान',
    'categoryBug': 'कुछ काम नहीं कर रहा',
    'categoryCrash': 'ऐप बंद हो गया',
    'categoryLabel': 'किस तरह की समस्या है?',
    'categoryOther': 'कुछ और',
    'categoryQuestion': 'एक सवाल',
    'categoryTranslation': 'गलत या छूटा हुआ अनुवाद',
    'close': 'बंद करें',
    'contactEmailLabel': 'आपका ईमेल पता',
    'descriptionLabel': 'क्या हुआ?',
    'descriptionRequired': 'कृपया समस्या का वर्णन करें।',
    'emailSupport': 'इसके बजाय सहायता को ईमेल करें',
    'includeLogs': 'हाल के ऐप लॉग शामिल करें (निजी जानकारी हटाकर)',
    'markupBlur': 'धुंधला करें',
    'markupDone': 'हो गया',
    'markupDraw': 'बनाएँ',
    'markupHighlight': 'हाइलाइट करें',
    'markupScreenshot': 'स्क्रीनशॉट पर निशान लगाएँ',
    'markupUndo': 'पूर्ववत करें',
    'notifyConsent': 'ठीक होने पर मुझे बताएँ',
    'previewTitle': 'ठीक यही भेजा जाएगा',
    'queuedBody': 'आप ऑफ़लाइन हैं। आपकी रिपोर्ट इस डिवाइस पर सहेजी गई है और ऑनलाइन होने पर एक बार भेजी जाएगी।',
    'refusedBody': 'आपकी रिपोर्ट नहीं भेजी जा सकी। आप इसके बजाय सहायता को ईमेल कर सकते हैं।',
    'replyConsent': 'आप मुझे जवाब दे सकते हैं',
    'reportProblem': 'समस्या की रिपोर्ट करें',
    'screenshotBlurNote': 'कुछ भी भेजने से पहले टेक्स्ट फ़ील्ड और निजी जानकारी धुंधली कर दी जाती है। आप और धुंधला कर सकते हैं, पर धुंधलापन हटा नहीं सकते।',
    'send': 'रिपोर्ट भेजें',
    'sending': 'भेजा जा रहा है…',
    'sentBody': 'धन्यवाद। आपकी रिपोर्ट संख्या {id} है।',
    'stepsLabel': 'इसे दोबारा होने के चरण (वैकल्पिक)',
  },
};
