// ─────────────────────────────────────────────────────────────────────────────
// apple-privacy-manifest.test.mjs — assert-apple-privacy-manifest.mjs must be
// able to FAIL, and render-apple-privacy-manifest.mjs must round-trip.
//
// 🔴 EVERY TREE BELOW IS BUILT FROM THE REAL FILES AND THEN MUTATED. Nothing
// here is a hand-written fixture of what a privacy manifest "looks like": the
// audit, both `.xcprivacy` files, both `project.pbxproj` files,
// `.flutter-plugins-dependencies`, `data-safety.json` and `pubspec.lock` are
// COPIED from `apps/subscriptiontracker` and one thing is broken per case. The house rule is
// that a fixture agrees with whatever misunderstanding wrote it — a plist I
// typed would encode my idea of a plist, and the guard would then be tested
// against my idea rather than against Xcode's.
//
// ⚠️ AND EVERY MUTATION IS LAND-CHECKED BEFORE ITS EXIT CODE IS TRUSTED. The
// play-declarations run recorded two mutations that reported NOT CAUGHT because
// `.replace` had silently anchored on the wrong occurrence — the guard was right
// to stay quiet, and the test was wrong. `mutated()` below fails loudly when a
// replacement changed nothing, so a no-op mutation can never read as a weak
// limb.
//
// RECORDED MUTATION RUN — see the table in the suite `the limbs must bite`.
// Every case asserts a NON-ZERO exit AND the specific sentence that limb owns,
// because "some limb fired" is not evidence that THIS limb fired.
//
// Run:  node --test "tooling/ci/test/apple-privacy-manifest.test.mjs"
// ─────────────────────────────────────────────────────────────────────────────
import { test, describe, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, cpSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { spiedRun, racyOn, pathKey } from './fixtures/fs-spy-run.mjs';
import {
  AUDIT_REL,
  MANIFEST_REL,
  PBXPROJ_REL,
  PLATFORMS,
  APP_TARGET_SOURCES,
  AppleManifestUnavailable,
  readAudit,
  renderAll,
  renderManifest,
} from '../../store/render-apple-privacy-manifest.mjs';
import { parsePlist, parsePbxproj, BUILT_LAYOUT } from '../assert-apple-privacy-manifest.mjs';

const CI_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const REPO = resolve(CI_DIR, '..', '..');
const GUARD = join(CI_DIR, 'assert-apple-privacy-manifest.mjs');
const RENDERER = join(REPO, 'tooling', 'store', 'render-apple-privacy-manifest.mjs');
const APP = 'subscriptiontracker';

/**
 * 🔴 THE ONE SUBJECT FILE THAT IS NOT IN GIT, AND WHY IT NEEDS A FIXTURE.
 *
 * `apps/<app>/.flutter-plugins-dependencies` is GENERATED by `flutter pub get` and
 * IGNORED (apps/subscriptiontracker/.gitignore:30). It is the right thing for the GUARD to read —
 * it is what the Apple build actually links, so it is the only derivation of the
 * plugin set that cannot go stale — and the guard runs in `workspace_gate`, right
 * after `flutter pub get --enforce-lockfile`, where it exists.
 *
 * This TEST FILE is a different matter: ci.yml runs the whole `tooling/ci/test/*`
 * glob in the `platform` lane, which has no Flutter in it at all, so on a CI runner
 * the file is simply absent and every case here died on one assertion. That is not
 * a finding about the guard — it is this file depending on something git does not
 * carry.
 *
 * So: the REAL file is used whenever it exists (a developer machine, and preflight,
 * where the mutations therefore still range over the real tree exactly as intended),
 * and a committed fixture stands in when it does not.
 *
 * ⚠️ A FIXTURE THAT NOBODY COMPARES IS A FIXTURE THAT ROTS, and a stale one here
 * would make the plugin-set limb pass against a plugin list the build stopped
 * having. `the committed fixture still matches the real generated file` below is
 * that comparison; it runs wherever the real file exists and states plainly that it
 * cannot run on a Flutter-less runner.
 */
const PLUGIN_DEPS_REL = `apps/${APP}/.flutter-plugins-dependencies`;
const PLUGIN_DEPS_FIXTURE = join(CI_DIR, 'test', 'fixtures', 'subscriptiontracker.flutter-plugins-dependencies.json');
const realPluginDeps = () => join(REPO, PLUGIN_DEPS_REL);
const havePluginDeps = () => existsSync(realPluginDeps());
const pluginDepsSource = () => (havePluginDeps() ? realPluginDeps() : PLUGIN_DEPS_FIXTURE);

/** Everything the guard reads. Copied verbatim; the tests break one at a time. */
const SUBJECT_FILES = [
  ['pubspec.lock', 'pubspec.lock'],
  [`apps/${APP}/${AUDIT_REL}`, `apps/${APP}/${AUDIT_REL}`],
  [`apps/${APP}/store/android-play/data-safety.json`, `apps/${APP}/store/android-play/data-safety.json`],
  [`apps/${APP}/.flutter-plugins-dependencies`, `apps/${APP}/.flutter-plugins-dependencies`],
  ...PLATFORMS.map((p) => [`apps/${APP}/${MANIFEST_REL[p]}`, `apps/${APP}/${MANIFEST_REL[p]}`]),
  ...PLATFORMS.map((p) => [`apps/${APP}/${PBXPROJ_REL[p]}`, `apps/${APP}/${PBXPROJ_REL[p]}`]),
];

let TMP;
let seq = 0;
before(() => {
  TMP = mkdtempSync(join(tmpdir(), 'nikatru-appleprivacy-'));
});
after(() => {
  if (TMP) rmSync(TMP, { recursive: true, force: true });
});

const run = (root) => {
  const r = spawnSync(process.execPath, [GUARD, root], { encoding: 'utf8' });
  return { code: r.status, out: `${r.stdout}${r.stderr}` };
};

/** A copy of the real subject tree. `mutate(root)` breaks exactly one thing. */
function tree(mutate) {
  const root = join(TMP, `t${seq++}`);
  for (const [from, to] of SUBJECT_FILES) {
    const src = from === PLUGIN_DEPS_REL ? pluginDepsSource() : join(REPO, from);
    assert.ok(existsSync(src), `subject file missing from the real tree: ${from}`);
    const dst = join(root, to);
    mkdirSync(dirname(dst), { recursive: true });
    cpSync(src, dst);
  }
  if (mutate) mutate(root);
  return root;
}

const read = (root, rel) => readFileSync(join(root, rel), 'utf8');
const write = (root, rel, text) => writeFileSync(join(root, rel), text);

/** Replace, and REFUSE to continue if nothing changed. A no-op mutation is a
 *  broken test, not a weak guard, and the difference is invisible unless you go
 *  and look. */
function mutated(text, from, to, what) {
  const next = typeof from === 'string' ? text.replace(from, to) : text.replace(from, to);
  assert.notEqual(next, text, `mutation did not land: ${what}`);
  return next;
}

/** Edit the audit and REGENERATE both manifests, so limb 1 stays green and the
 *  limb under test is the only thing that can fire. Without this every audit
 *  mutation would trip the byte comparison first and prove nothing about the
 *  limb it was written for. */
function editAuditAndRegenerate(root, edit) {
  const rel = `apps/${APP}/${AUDIT_REL}`;
  const audit = JSON.parse(read(root, rel));
  const before = JSON.stringify(audit);
  edit(audit);
  assert.notEqual(JSON.stringify(audit), before, 'audit mutation did not land');
  write(root, rel, `${JSON.stringify(audit, null, 2)}\n`);
  const rendered = renderAll(audit, APP);
  for (const p of PLATFORMS) write(root, `apps/${APP}/${MANIFEST_REL[p]}`, rendered[p]);
}

// ─────────────────────────────────────────────────────────────────────────────
describe('render-apple-privacy-manifest.mjs — the generator round-trips', () => {
  test('the committed .xcprivacy files are BYTE-FOR-BYTE what the audit renders', () => {
    const { audit } = readAudit(join(REPO, 'apps', APP));
    const rendered = renderAll(audit, APP);
    for (const p of PLATFORMS) {
      const committed = readFileSync(join(REPO, 'apps', APP, MANIFEST_REL[p]), 'utf8');
      assert.equal(rendered[p], committed, `${MANIFEST_REL[p]} is not what the audit renders`);
    }
  });

  test('--check on the real tree exits 0', () => {
    const r = spawnSync(process.execPath, [RENDERER, '--app', APP, '--check'], {
      encoding: 'utf8',
      cwd: REPO,
    });
    assert.equal(r.status, 0, `${r.stdout}${r.stderr}`);
  });

  test('each manifest is read ONCE, with no existence check of its path first (CodeQL #91)', () => {
    // The write mode decides on the same bytes --check reads. The renderer derives its root from
    // its own location, so the shared read is pinned here on the real tree, strictly: not even
    // the existsSync-then-read CodeQL tolerates.
    const { code, text, verdict } = spiedRun([RENDERER, '--app', APP, '--check'], { cwd: REPO, under: REPO });
    assert.equal(code, 0, text);
    for (const rel of ['ios/Runner/PrivacyInfo.xcprivacy', 'macos/Runner/PrivacyInfo.xcprivacy']) {
      const suffix = `/apps/${APP}/${rel}`;
      assert.ok(verdict.uses.some((u) => u.endsWith(pathKey(suffix))), `${rel} was never read`);
      assert.deepEqual(racyOn(verdict, suffix, { key: 'pairs' }), []);
    }
  });

  // ⏱ 2026-10-01 (T16): the REAL audit's iOS accessed-API array is no longer
  // empty (home_widget's app-group UserDefaults, declared by the app target
  // because that binary ships no manifest), so the two real renderings differ
  // in that paragraph and that array too. The property this case pins — the
  // PLATFORM is two lines and nothing else — is measured on the audit with
  // the per-platform arrays made equal; the next case pins the arrays.
  test('the two platforms differ in EXACTLY two lines — the platform id and the source list', () => {
    const { audit: real } = readAudit(join(REPO, 'apps', APP));
    const audit = JSON.parse(JSON.stringify(real));
    audit.accessedApiDetermination.macos = audit.accessedApiDetermination.ios;
    const ios = renderManifest(audit, 'ios', APP).split('\n');
    const macos = renderManifest(audit, 'macos', APP).split('\n');
    assert.equal(ios.length, macos.length);
    const differing = ios.map((l, i) => (l === macos[i] ? null : i)).filter((i) => i !== null);
    assert.equal(differing.length, 2, `expected 2 differing lines, got ${differing.length}`);
    assert.match(ios[differing[0]], /Platform: ios\./);
    assert.match(macos[differing[0]], /Platform: macos\./);
    for (const f of APP_TARGET_SOURCES.ios) assert.ok(ios[differing[1]].includes(f));
    for (const f of APP_TARGET_SOURCES.macos) assert.ok(macos[differing[1]].includes(f));
  });

  test('what it renders parses back to what the audit declares', () => {
    const { audit } = readAudit(join(REPO, 'apps', APP));
    for (const p of PLATFORMS) {
      const doc = parsePlist(renderManifest(audit, p, APP));
      assert.equal(doc.NSPrivacyTracking, audit.tracking.NSPrivacyTracking);
      assert.deepEqual(doc.NSPrivacyTrackingDomains, audit.tracking.NSPrivacyTrackingDomains);
      assert.deepEqual(
        doc.NSPrivacyCollectedDataTypes.map((r) => r.NSPrivacyCollectedDataType),
        audit.collectedDataTypes.rows.map((r) => r.type),
      );
      assert.deepEqual(
        doc.NSPrivacyCollectedDataTypes.map((r) => r.NSPrivacyCollectedDataTypeLinked),
        audit.collectedDataTypes.rows.map((r) => r.linked),
      );
      assert.deepEqual(
        doc.NSPrivacyCollectedDataTypes.map((r) => r.NSPrivacyCollectedDataTypePurposes),
        audit.collectedDataTypes.rows.map((r) => r.purposes),
      );
      assert.deepEqual(
        doc.NSPrivacyAccessedAPITypes,
        audit.accessedApiDetermination[p].map((e) => ({
          NSPrivacyAccessedAPIType: e.category,
          NSPrivacyAccessedAPITypeReasons: e.reasons,
        })),
      );
    }
    // And the real arrays, pinned: iOS declares home_widget's app-group
    // UserDefaults (T16); macOS, where home_widget has no implementation, none.
    assert.deepEqual(audit.accessedApiDetermination.ios, [
      { category: 'NSPrivacyAccessedAPICategoryUserDefaults', reasons: ['1C8F.1'] },
    ]);
    assert.deepEqual(audit.accessedApiDetermination.macos, []);
  });

  test('a NON-EMPTY accessedApiDetermination renders and parses back — U-1\'s remedy is not dead code', () => {
    const { audit } = readAudit(join(REPO, 'apps', APP));
    const withRow = JSON.parse(JSON.stringify(audit));
    withRow.accessedApiDetermination.ios = [
      { category: 'NSPrivacyAccessedAPICategorySystemBootTime', reasons: ['35F9.1'] },
    ];
    const text = renderManifest(withRow, 'ios', APP);
    const doc = parsePlist(text);
    assert.deepEqual(doc.NSPrivacyAccessedAPITypes, [
      {
        NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime',
        NSPrivacyAccessedAPITypeReasons: ['35F9.1'],
      },
    ]);
    // And the header must stop claiming the array is empty.
    assert.ok(!text.includes('NSPrivacyAccessedAPITypes IS EMPTY BY MEASUREMENT'));
    assert.ok(text.includes('NSPrivacyAccessedAPITypes IS NON-EMPTY'));
  });

  test('readAudit REFUSES an audit that is absent, unparseable or vacuous', () => {
    const empty = join(TMP, 'no-audit');
    mkdirSync(empty, { recursive: true });
    assert.throws(() => readAudit(empty), AppleManifestUnavailable);

    const root = tree((r) => {
      const audit = JSON.parse(read(r, `apps/${APP}/${AUDIT_REL}`));
      audit.collectedDataTypes.rows = [];
      write(r, `apps/${APP}/${AUDIT_REL}`, `${JSON.stringify(audit, null, 2)}\n`);
    });
    assert.throws(() => readAudit(join(root, 'apps', APP)), (e) => {
      assert.ok(e instanceof AppleManifestUnavailable);
      assert.match(e.lines.join(' '), /declares no collectedDataTypes\.rows/);
      return true;
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe('the readers parse structure, not prose', () => {
  test('the plist reader does not read the header comment as a declaration', () => {
    // The rendered header names UserDefaults, CA92.1 and 1C8F.1 in a sentence
    // explaining why they are NOT declared. A grep would conclude the opposite.
    // ⏱ 2026-10-01 (T16): read on the MACOS file, whose array is still empty;
    // the iOS one now really declares UserDefaults (see the case above).
    const committed = readFileSync(join(REPO, 'apps', APP, MANIFEST_REL.macos), 'utf8');
    assert.ok(committed.includes('NSPrivacyAccessedAPICategoryUserDefaults') === false);
    assert.ok(committed.includes('CA92.1'), 'the header must still name CA92.1 in prose');
    assert.deepEqual(parsePlist(committed).NSPrivacyAccessedAPITypes, []);
  });

  test('the pbxproj reader finds BOTH native targets and both Resources phases', () => {
    const objects = parsePbxproj(readFileSync(join(REPO, 'apps', APP, PBXPROJ_REL.ios), 'utf8'));
    const targets = [...objects.values()].filter((o) => o.isa === 'PBXNativeTarget').map((o) => o.name);
    assert.deepEqual(targets.sort(), ['Runner', 'RunnerTests']);
    const phases = [...objects.values()].filter((o) => o.isa === 'PBXResourcesBuildPhase');
    assert.equal(phases.length, 2, 'the iOS project carries two Resources phases; the empty one is RunnerTests');
  });

  test('a settings dict re-using a target id does not overwrite the target', () => {
    // PBXProject carries `attributes = { TargetAttributes = { <targetId> = {…} } }`
    // and that inner block has no `isa`. It is not an object.
    const objects = parsePbxproj(readFileSync(join(REPO, 'apps', APP, PBXPROJ_REL.ios), 'utf8'));
    for (const o of objects.values()) assert.ok(o.isa, `object ${o.id} has no isa`);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe('assert-apple-privacy-manifest.mjs — the positive controls', () => {
  // 🔴 THESE RUN AGAINST tree(null), NOT AGAINST REPO, AND THE REASON IS NOT
  // COSMETIC. The guard reads exactly SUBJECT_FILES, so an unmutated copy of them
  // IS the real subject — and on a machine that has run `flutter pub get`, tree()
  // copies the REAL .flutter-plugins-dependencies, so this is the real tree.
  // Pointed at REPO instead, all three died on a Flutter-less CI runner, where the
  // generated file does not exist: a positive control that cannot run in CI is a
  // positive control CI does not have. The stronger check against the literal
  // repository is kept below, conditioned on the file being there.
  test('the REAL repository passes', () => {
    const { code, out } = run(tree(null));
    assert.equal(code, 0, `the real tree must pass, got:\n${out}`);
  });

  test('an unmutated copy of the real subject files passes', () => {
    const { code, out } = run(tree(null));
    assert.equal(code, 0, `the baseline copy must pass, got:\n${out}`);
  });

  test('it PRINTS what it cannot see on every run, in the audit\'s own words', () => {
    const { code, out } = run(tree(null));
    assert.equal(code, 0);
    assert.match(out, /CANNOT SEE — THE COCOAPODS CLOSURE/);
    assert.match(out, /Sentry\/HybridSDK 8\.58\.4/);
    assert.match(out, /CANNOT SEE — THE BUILT BUNDLE/);
    assert.match(out, /UNRESOLVED U-1/);
    assert.match(out, /objc_msgSend/);

    // …and the words are READ from the audit, not restated in the guard: an item
    // that exists only in this copy of the audit must print. A guard carrying its
    // own text would print the sentences above and never this one
    // (O-UNGRADED-MECHANISM-CLAIMS, tooling/mechanism-claims.json).
    const planted = 'PLANTED ITEM THAT EXISTS ONLY IN THIS FIXTURE AUDIT';
    const t = tree((root) =>
      editAuditAndRegenerate(root, (audit) => {
        assert.ok(Array.isArray(audit.cannotSee?.items), 'the real audit carries cannotSee.items');
        audit.cannotSee.items.push(planted);
      }),
    );
    const edited = run(t);
    assert.equal(edited.code, 0, edited.out);
    assert.match(edited.out, new RegExp(`CANNOT SEE — ${planted}`));
  });

  test('it WARNS, and does not fail, on constants whose witness is `knowledge`', () => {
    const { code, out } = run(tree(null));
    assert.equal(code, 0);
    assert.match(out, /witness `knowledge`/);
    assert.match(out, /collectedDataType NSPrivacyCollectedDataTypeCoarseLocation/);
  });

  // The literal working tree, in place, with nothing copied — the one check that
  // proves the guard is green on the repository a human is actually holding. It
  // needs the generated plugin file, so it states plainly when it could not run
  // rather than reporting ok over a thing it did not do.
  test('the literal working tree passes, where the generated plugin file exists', (t) => {
    if (!havePluginDeps()) {
      t.diagnostic(
        `no ${PLUGIN_DEPS_REL} on this machine (generated, gitignored), so the guard was not run ` +
          'against the working tree in place. The copy-based controls above still ran.',
      );
      return;
    }
    const { code, out } = run(REPO);
    assert.equal(code, 0, `the literal working tree must pass, got:\n${out}`);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
describe('the limbs must bite', () => {
  // ── limb 1 ────────────────────────────────────────────────────────────────
  test('limb 1 — a HAND-EDITED .xcprivacy is a build failure', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${MANIFEST_REL.ios}`;
      write(
        r,
        rel,
        mutated(
          read(r, rel),
          '<string>NSPrivacyCollectedDataTypeCoarseLocation</string>',
          '<string>NSPrivacyCollectedDataTypePreciseLocation</string>',
          'hand-edit the iOS manifest',
        ),
      );
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /is NOT what .* renders — first difference at line/);
  });

  test('limb 1 — a hand-edited macOS manifest is caught too, not just iOS', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${MANIFEST_REL.macos}`;
      write(r, rel, mutated(read(r, rel), '<array/>\n</dict>', '<array>\n\t</array>\n</dict>', 'macOS body edit'));
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /macos\/Runner\/PrivacyInfo\.xcprivacy is NOT what/);
  });

  test('limb 1 — a DELETED manifest is a failure, not a skip', () => {
    const root = tree((r) => rmSync(join(r, 'apps', APP, MANIFEST_REL.macos)));
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /macos\/Runner\/PrivacyInfo\.xcprivacy does not exist/);
  });

  // ── limb 2 ────────────────────────────────────────────────────────────────
  test('limb 2 — the pbxproj REFERENCE removed', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${PBXPROJ_REL.ios}`;
      const before = read(r, rel);
      const after = before
        .split('\n')
        .filter((l) => !l.includes('PrivacyInfo.xcprivacy'))
        .join('\n');
      assert.notEqual(after, before, 'mutation did not land: strip the xcprivacy references');
      write(r, rel, after);
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /contains no PBXFileReference for PrivacyInfo\.xcprivacy/);
  });

  // 🔴 THE MISTAKE THAT MATTERS. The string is still in the file, the file
  // reference still exists, the build file still exists — and the app bundle
  // gets nothing, because the only Resources phase naming it is RunnerTests'.
  test('limb 2 — the reference present but ONLY in the RunnerTests Resources phase', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${PBXPROJ_REL.ios}`;
      let text = read(r, rel);
      const memberLine = text
        .split('\n')
        .find((l) => /PrivacyInfo\.xcprivacy in Resources \*\/,\s*$/.test(l));
      assert.ok(memberLine, 'could not find the Runner Resources membership line');
      text = mutated(text, `${memberLine}\n`, '', 'remove the membership line from the Runner phase');
      // The EMPTY PBXResourcesBuildPhase is RunnerTests' — put it there instead.
      text = mutated(
        text,
        /(isa = PBXResourcesBuildPhase;\n\t{3}buildActionMask = 2147483647;\n\t{3}files = \(\n)(\t{3}\);)/,
        `$1${memberLine}\n$2`,
        'insert the membership line into the RunnerTests phase',
      );
      write(r, rel, text);
      const after = read(r, rel);
      assert.ok(after.includes('PrivacyInfo.xcprivacy'), 'the string must still be present — that is the point');
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /is NOT in the Runner target's PBXResourcesBuildPhase/);
    assert.match(out, /SILENT HALF/);
  });

  test('limb 2 — the macOS manifest dropped from the Runner Resources phase', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${PBXPROJ_REL.macos}`;
      const text = read(r, rel);
      const memberLine = text.split('\n').find((l) => /PrivacyInfo\.xcprivacy in Resources \*\/,\s*$/.test(l));
      assert.ok(memberLine, 'could not find the macOS Runner Resources membership line');
      write(r, rel, mutated(text, `${memberLine}\n`, '', 'drop the macOS membership line'));
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /is NOT in the Runner target's PBXResourcesBuildPhase/);
  });

  test('limb 2 — the header\'s source-file set must match the Runner Sources phase', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${PBXPROJ_REL.ios}`;
      const text = read(r, rel);
      const line = text.split('\n').find((l) => /SceneDelegate\.swift in Sources \*\/,\s*$/.test(l));
      assert.ok(line, 'could not find the SceneDelegate Sources line');
      write(r, rel, mutated(text, `${line}\n`, '', 'drop SceneDelegate from the Sources phase'));
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /the ios manifest header says the app target's own code is/);
  });

  // ── limb 3 ────────────────────────────────────────────────────────────────
  test('limb 3 — an INVENTED accessed-API category', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        a.accessedApiDetermination.ios = [
          { category: 'NSPrivacyAccessedAPICategoryTelepathy', reasons: ['35F9.1'] },
        ];
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /NSPrivacyAccessedAPICategoryTelepathy`, which is not in the audit's vocabulary/);
  });

  test('limb 3 — a reason code declared under the WRONG category', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        // CA92.1 is real, and it belongs to UserDefaults, not SystemBootTime.
        a.accessedApiDetermination.macos = [
          { category: 'NSPrivacyAccessedAPICategorySystemBootTime', reasons: ['CA92.1'] },
        ];
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /reason code `CA92\.1` under `NSPrivacyAccessedAPICategorySystemBootTime`/);
    assert.match(out, /belongs to `NSPrivacyAccessedAPICategoryUserDefaults`/);
  });

  test('limb 3 — an INVENTED reason code', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        a.accessedApiDetermination.ios = [
          { category: 'NSPrivacyAccessedAPICategorySystemBootTime', reasons: ['ZZ99.9'] },
        ];
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /reason code `ZZ99\.9`, which is not in the audit's vocabulary\.reasonCodes/);
  });

  test('limb 3 — an INVENTED purpose string', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        a.collectedDataTypes.rows[0].purposes = ['NSPrivacyCollectedDataTypePurposeVibes'];
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /purpose `NSPrivacyCollectedDataTypePurposeVibes`/);
  });

  // ── limb 4 ────────────────────────────────────────────────────────────────
  test('limb 4 — a NEW plugin with no inventory row: "nobody said what required-reason APIs this uses"', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/.flutter-plugins-dependencies`;
      const fpd = JSON.parse(read(r, rel));
      fpd.plugins.ios.push({
        name: 'camera_avfoundation',
        path: '/pub-cache/hosted/pub.dev/camera_avfoundation-0.9.0/',
        native_build: true,
        dependencies: [],
        dev_dependency: false,
      });
      write(r, rel, `${JSON.stringify(fpd)}\n`);
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /camera_avfoundation is linked into the build/);
    assert.match(out, /nobody said what required-reason APIs this uses/);
  });

  test('limb 4 — EQUALITY, not subset: an inventory row the build no longer links', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/.flutter-plugins-dependencies`;
      const fpd = JSON.parse(read(r, rel));
      const before = fpd.plugins.macos.length;
      fpd.plugins.macos = fpd.plugins.macos.filter((p) => p.name !== 'in_app_review');
      assert.equal(fpd.plugins.macos.length, before - 1, 'mutation did not land: drop in_app_review');
      write(r, rel, `${JSON.stringify(fpd)}\n`);
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /declares in_app_review, which the build no longer links/);
  });

  test('limb 4 — a plugin VERSION bump the audit never read', () => {
    const root = tree((r) => {
      const text = read(r, 'pubspec.lock');
      write(
        r,
        'pubspec.lock',
        mutated(
          text,
          /(  app_links:\n(?:.*\n)*?    version: ")7\.2\.1(")/,
          '$17.9.9$2',
          'bump app_links in pubspec.lock',
        ),
      );
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /audits app_links 7\.2\.1 and pubspec\.lock resolves app_links 7\.9\.9/);
  });

  // ── limb 5 ────────────────────────────────────────────────────────────────
  test('limb 5 — a Play row FLIPPED without this file moving is a contradiction', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/store/android-play/data-safety.json`;
      const ds = JSON.parse(read(r, rel));
      const victim = ds.answers.find((a) => a.collected?.['backend-live'] === false);
      assert.ok(victim, 'no un-collected Play row to flip');
      victim.collected['backend-live'] = true;
      write(r, rel, `${JSON.stringify(ds, null, 2)}\n`);
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /the two sworn declarations CONTRADICT each other/);
    assert.match(out, /Play says collected, Apple does not declare/);
  });

  test('limb 5 — an Apple row whose fromPlayRow the Play file does not collect', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/store/android-play/data-safety.json`;
      const ds = JSON.parse(read(r, rel));
      const victim = ds.answers.find((a) => a.type === 'Crash logs');
      assert.ok(victim, 'the Crash logs row is expected in the Play declaration');
      victim.collected['backend-live'] = false;
      write(r, rel, `${JSON.stringify(ds, null, 2)}\n`);
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /Apple names fromPlayRow, Play does not collect: Crash logs/);
  });

  test('limb 5 — the two files answering for DIFFERENT build postures', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/store/android-play/data-safety.json`;
      const ds = JSON.parse(read(r, rel));
      ds.buildPosture.current = 'demo';
      write(r, rel, `${JSON.stringify(ds, null, 2)}\n`);
    });
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /answers for posture `backend-live` and .* builds `demo`/);
  });

  test('limb 5 — a fromPlayRow that names no Play row at all', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        a.collectedDataTypes.rows[0].fromPlayRow = 'Telepathic impressions';
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /which is not a row in .* at all/);
  });

  // ── limb 6 ────────────────────────────────────────────────────────────────
  test('limb 6 — NSPrivacyTrackingDomains non-empty while NSPrivacyTracking is false', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        a.tracking.NSPrivacyTrackingDomains = ['telemetry.example.com'];
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /NSPrivacyTracking false AND 1 NSPrivacyTrackingDomains/);
    assert.match(out, /only the PAIR is checkable/);
  });

  test('limb 6 — a row used for TRACKING while the app swears it does not track', () => {
    const root = tree((r) =>
      editAuditAndRegenerate(r, (a) => {
        a.collectedDataTypes.rows.find((x) => x.type === 'NSPrivacyCollectedDataTypeDeviceID').tracking = true;
      }),
    );
    const { code, out } = run(root);
    assert.notEqual(code, 0);
    assert.match(out, /NSPrivacyCollectedDataTypeDeviceID` is used for TRACKING while NSPrivacyTracking is false/);
  });

  // ── limb 7 ────────────────────────────────────────────────────────────────
  // Every case here asserts EXIT 2, the repo's COVERAGE LOST code, not merely
  // non-zero: with `notEqual(code, 0)` the coverageLost helper could exit 1 (a
  // finding) and no case noticed (O-COVERAGE-LOST-BRANCH-UNTESTED, 2026-09-15).
  test('limb 7 — a SUBJECT-FREE tree REFUSES', () => {
    const root = join(TMP, `empty${seq++}`);
    mkdirSync(root, { recursive: true });
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /apps does not exist/);
  });

  test('limb 7 — apps/ with no audit in it REFUSES rather than printing ok over nothing', () => {
    const root = join(TMP, `noaudit${seq++}`);
    mkdirSync(join(root, 'apps', 'ghost'), { recursive: true });
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /NOT ONE carries store\/ios-appstore\/privacy-manifest\.json/);
  });

  test('limb 7 — an audit with NO collected rows REFUSES', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${AUDIT_REL}`;
      const audit = JSON.parse(read(r, rel));
      audit.collectedDataTypes.rows = [];
      write(r, rel, `${JSON.stringify(audit, null, 2)}\n`);
    });
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /declares no collectedDataTypes\.rows/);
  });

  test('limb 7 — an EMPTY binaryInventory REFUSES', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${AUDIT_REL}`;
      const audit = JSON.parse(read(r, rel));
      audit.binaryInventory.macos = [];
      write(r, rel, `${JSON.stringify(audit, null, 2)}\n`);
    });
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /declares an empty binaryInventory\.macos/);
  });

  /* ⏱ 2026-09-22 (O-APPLE-PRIVACY-GUARD-CANNOT-RUN-IN-A-WORKTREE) — ONE case became
     TWO, because the refusal now names WHICH of two states it is in and the two
     sentences send the reader somewhere different. Both still exit 2 and both still
     say `does not exist`: that part is asserted in each case, so a later edit cannot
     quietly turn either into a pass or break the readers that match on it.
     The discriminator is `.dart_tool/package_config.json`, which `flutter pub get`
     writes beside this file and which `SUBJECT_FILES` never copies — so the fixture
     tree is NEVER BUILT by construction, and the second case plants it. */
  test('limb 7 — a missing .flutter-plugins-dependencies in a NEVER BUILT tree says so, and names the one command', () => {
    const root = tree((r) => rmSync(join(r, 'apps', APP, '.flutter-plugins-dependencies')));
    assert.equal(existsSync(join(root, '.dart_tool', 'package_config.json')), false, 'the fixture must start unresolved or this case proves nothing');
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /flutter-plugins-dependencies does not exist/);
    assert.match(out, /NEVER BUILT/, out);
    assert.match(out, /flutter pub get/, out);
    assert.doesNotMatch(out, /WAS resolved/, out);
  });

  test('limb 7 — the same file missing from a RESOLVED tree is reported as LOST, not as unbuilt', () => {
    const root = tree((r) => {
      rmSync(join(r, 'apps', APP, '.flutter-plugins-dependencies'));
      // The only evidence that `flutter pub get` ever ran here. Contents are never
      // parsed by the guard — its EXISTENCE is the whole signal — so `{}` is honest.
      mkdirSync(join(r, '.dart_tool'), { recursive: true });
      writeFileSync(join(r, '.dart_tool', 'package_config.json'), '{}', 'utf8');
    });
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /flutter-plugins-dependencies does not exist/);
    assert.match(out, /WAS resolved/, out);
    assert.match(out, /LOST after/, out);
    assert.doesNotMatch(out, /NEVER BUILT/, out);
    // ⚠️ It must NOT tell the reader to re-run the command that would erase the
    // evidence of whatever deleted the file.
    assert.doesNotMatch(out, /Run the one command/, out);
  });

  test('limb 7 — a missing data-safety.json REFUSES rather than skipping limb 5', () => {
    const root = tree((r) => rmSync(join(r, 'apps', APP, 'store', 'android-play', 'data-safety.json')));
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /data-safety\.json does not exist/);
  });

  test('limb 7 — an empty closed vocabulary REFUSES (a membership test against nothing cannot fail)', () => {
    const root = tree((r) => {
      const rel = `apps/${APP}/${AUDIT_REL}`;
      const audit = JSON.parse(read(r, rel));
      audit.vocabulary.purposes.values = [];
      write(r, rel, `${JSON.stringify(audit, null, 2)}\n`);
    });
    const { code, out } = run(root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /enumerates no vocabulary\.purposes\.values/);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// --built — THE BUNDLE THAT SHIPS (limb 8, O-APPLE-PROVER-SKIPS-THE-PKG)
//
// 🔴 THE BUNDLES BELOW ARE REBUILT FROM A CAPTURE, NOT IMAGINED.
// fixtures/apple-run-36229543907/bundles.json is what readBuiltBundle() read out
// of the .ipa and the .pkg that bp run 36229543907 shipped: every framework,
// every SDK resource bundle and every PrivacyInfo.xcprivacy path with its digest.
// The manifests the audit pins are committed byte for byte, the app's own is the
// committed file (measured identical in both bundles), and the rest get a
// placeholder because no row pins them. Each case then breaks ONE thing, against
// a copy of the REAL audit.
// ─────────────────────────────────────────────────────────────────────────────
const RUN_DIR = join(CI_DIR, 'test', 'fixtures', 'apple-run-36229543907');
const CAPTURED = JSON.parse(readFileSync(join(RUN_DIR, 'bundles.json'), 'utf8'));
const PLACEHOLDER_PLIST = '<?xml version="1.0" encoding="UTF-8"?>\n<plist version="1.0">\n<dict/>\n</plist>\n';

// ⏱ 2026-09-27 (rv-c31, the Flutter majors chain): THE CAPTURE IS GRADED AGAINST THE AUDIT IT WAS
// PROVEN AGAINST, not against whatever audit the tree carries today. M7 moved the audit to
// flutter_secure_storage_darwin while this capture embeds flutter_secure_storage(.framework|_macos),
// so the REAL audit against it went red, and every mutation below passed only because its base already
// failed. fixtures/apple-run-36229543907/privacy-manifest.json is the last audit graded against this
// capture (main 1cd269b7; W36 wrote its SDK rows FROM it). The REAL audit against the bundle that SHIPS is build-platforms.yml's PROVE step
// (`--built` on every release-signed Apple build); re-capture from its first run after a plugin move.
const CAPTURE_AUDIT = join(RUN_DIR, 'privacy-manifest.json');
/** `tree()` carrying the capture's own audit. */
const capturedTree = (mutate) => tree((r) => { cpSync(CAPTURE_AUDIT, join(r, 'apps', APP, AUDIT_REL)); if (mutate) mutate(r); });

/** The captured bundle for `platform`, rebuilt under TMP. `root` is the subject
 *  tree whose committed app manifest the bundle carries; `mutate(app)` breaks
 *  one thing in the bundle. */
function builtApp(platform, root, mutate) {
  const cap = CAPTURED[platform];
  const layout = BUILT_LAYOUT[platform];
  const app = join(TMP, `app${seq++}`, cap.app);
  mkdirSync(join(app, layout.frameworks), { recursive: true });
  writeFileSync(join(app, platform === 'ios' ? 'Info.plist' : join('Contents', 'Info.plist')), PLACEHOLDER_PLIST);
  for (const fw of cap.frameworks) mkdirSync(join(app, layout.frameworks, fw), { recursive: true });
  for (const b of cap.bundles) mkdirSync(join(app, layout.resources, b), { recursive: true });
  for (const m of cap.manifests) {
    const dst = join(app, m.rel);
    mkdirSync(dirname(dst), { recursive: true });
    if (m.captured === 'self') cpSync(join(root, 'apps', APP, MANIFEST_REL[platform]), dst);
    else if (m.captured) cpSync(join(RUN_DIR, m.captured), dst);
    else writeFileSync(dst, PLACEHOLDER_PLIST);
  }
  if (mutate) mutate(app);
  return app;
}

/** `--built` on one bundle, against the subject tree `root`. */
const runBuilt = (app, root, ...more) => {
  const r = spawnSync(process.execPath, [GUARD, '--app', APP, '--built', app, ...more, root], { encoding: 'utf8' });
  return { code: r.status, out: `${r.stdout}${r.stderr}` };
};

/** The audit row whose `binary` begins with `prefix`, on one platform. */
const rowOf = (audit, platform, prefix) => {
  const row = audit.binaryInventory[platform].find((r) => r.binary.startsWith(prefix));
  assert.ok(row, `the real audit carries a ${platform} row beginning ${prefix}`);
  return row;
};

describe('assert-apple-privacy-manifest.mjs --built — the bundle that ships', () => {
  test('the capture is what it says: every committed manifest hashes to the digest recorded for it', () => {
    let committed = 0;
    for (const platform of PLATFORMS) {
      for (const m of CAPTURED[platform].manifests) {
        if (!m.captured || m.captured === 'self') continue;
        const bytes = readFileSync(join(RUN_DIR, m.captured));
        assert.equal(createHash('sha256').update(bytes).digest('hex'), m.sha256, `${m.captured} is not the ${m.rel} of run ${CAPTURED.run}`);
        committed++;
      }
    }
    assert.equal(committed, 6, 'three pinned manifests, captured on each of the two platforms');
  });

  test('the audit bp run 36229543907 was proven against passes the iOS bundle it shipped, and prints what it embeds', () => {
    const root = capturedTree(null);
    const { code, out } = runBuilt(builtApp('ios', root), root);
    assert.equal(code, 0, out);
    assert.match(out, /--built: OK — Runner\.app \(ios, apps\/subscriptiontracker\): 8 framework\(s\), 7 SDK resource bundle\(s\), 14 PrivacyInfo\.xcprivacy/);
    assert.match(out, /RevenueCat_RevenueCat\.bundle ← RevenueCat \(purchases-ios/);
    assert.match(out, /118b16e0e97ffe8b6f1f01b7e04f68e5da764474a4d39d2933b0eeaef3cdc0ca {2}Frameworks\/Sentry\.framework\/PrivacyInfo\.xcprivacy/);
    assert.match(out, /CANNOT SEE — a statically linked SDK/);
  });

  test('the same audit passes the macOS bundle the same run shipped inside the .pkg', () => {
    const root = capturedTree(null);
    const { code, out } = runBuilt(builtApp('macos', root), root);
    assert.equal(code, 0, out);
    assert.match(out, /--built: OK — Subscriptions\.app \(macos, apps\/subscriptiontracker\): 8 framework\(s\), 7 SDK resource bundle\(s\), 14 PrivacyInfo\.xcprivacy/);
    assert.match(out, /Contents\/Frameworks\/objective_c\.framework ← objective_c\.framework/);
  });

  // RC5 in the design's table. At BASE the flag did not exist: `--built x.app`
  // read x.app as the repo root and exited 2 over `x.app/apps`.
  test('RC5 — an extra Frameworks/Foo.framework that no row answers for exits 1', () => {
    const root = capturedTree(null);
    const app = builtApp('ios', root, (a) => mkdirSync(join(a, 'Frameworks', 'Foo.framework')));
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 1, out);
    assert.match(out, /built-sdk · ios: Frameworks\/Foo\.framework is embedded in the bundle and no row of binaryInventory\.ios answers for it/);
  });

  test('RC5 — a Swift Package resource bundle that no row answers for exits 1 (the shape RevenueCat ships in)', () => {
    const root = capturedTree(null);
    const app = builtApp('macos', root, (a) => mkdirSync(join(a, 'Contents', 'Resources', 'Foo_Foo.bundle')));
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 1, out);
    assert.match(out, /built-sdk · macos: Contents\/Resources\/Foo_Foo\.bundle is embedded in the bundle/);
  });

  test('RC6 — a real row set back to `manifest: unread` exits 1', () => {
    const root = capturedTree((r) =>
      editAuditAndRegenerate(r, (a) => {
        rowOf(a, 'ios', 'RevenueCat ').manifest = 'unread';
      }),
    );
    const { code, out } = runBuilt(builtApp('ios', root), root);
    assert.equal(code, 1, out);
    assert.match(out, /built-unread · ios: `RevenueCat \(purchases-ios, linked through purchases_flutter 10\.13\.1\)` is still `manifest: unread`/);
  });

  test('built-hash — a pinned SDK manifest whose bytes changed exits 1 and names both digests', () => {
    const root = capturedTree(null);
    const app = builtApp('ios', root, (a) => {
      const rel = join(a, 'RevenueCat_RevenueCat.bundle', 'PrivacyInfo.xcprivacy');
      writeFileSync(rel, mutated(readFileSync(rel, 'utf8'), '</plist>', '<!-- a newer SDK -->\n</plist>', 'edit the RevenueCat manifest'));
    });
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 1, out);
    assert.match(out, /built-hash · ios: RevenueCat_RevenueCat\.bundle\/PrivacyInfo\.xcprivacy is sha256 [0-9a-f]{64} in the bundle, and `RevenueCat .*` pins 76c876c73bf3/);
  });

  test('built-hash — a pinned manifest that is no longer in the bundle exits 1', () => {
    const root = capturedTree(null);
    const app = builtApp('macos', root, (a) =>
      rmSync(join(a, 'Contents', 'Frameworks', 'OrderedSet.framework'), { recursive: true }),
    );
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 1, out);
    assert.match(out, /was read from Contents\/Frameworks\/OrderedSet\.framework\/Versions\/A\/Resources\/OrderedSet_privacy\.bundle\/Contents\/Resources\/PrivacyInfo\.xcprivacy, and the bundle carries no file there/);
  });

  test('built-hash — a `read` row that carries no sha256 exits 1', () => {
    const root = capturedTree((r) =>
      editAuditAndRegenerate(r, (a) => {
        delete rowOf(a, 'ios', 'Sentry.framework ').sha256;
      }),
    );
    const { code, out } = runBuilt(builtApp('ios', root), root);
    assert.equal(code, 1, out);
    assert.match(out, /built-hash · ios: `Sentry\.framework .*` is `manifest: read` and does not carry both `readFrom`/);
  });

  test('built-self — the app\'s own manifest missing from the bundle is the SILENT HALF, exit 1', () => {
    const root = capturedTree(null);
    const app = builtApp('ios', root, (a) => rmSync(join(a, 'PrivacyInfo.xcprivacy')));
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 1, out);
    assert.match(out, /built-self · ios: the bundle carries no PrivacyInfo\.xcprivacy/);
    assert.match(out, /SILENT HALF/);
  });

  test('built-self — an app manifest in the bundle that is not the committed one exits 1', () => {
    const root = capturedTree(null);
    const app = builtApp('macos', root, (a) => {
      const rel = join(a, 'Contents', 'Resources', 'PrivacyInfo.xcprivacy');
      writeFileSync(rel, mutated(readFileSync(rel, 'utf8'), '<false/>', '<true/>', 'flip a boolean in the bundled app manifest'));
    });
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 1, out);
    assert.match(out, /built-self · macos: the bundle's Contents\/Resources\/PrivacyInfo\.xcprivacy \(sha256 [0-9a-f]{64}\) is not the committed manifest/);
  });

  test('COVERAGE LOST — zero frameworks enumerated exits 2, not a pass over an empty list', () => {
    const root = capturedTree(null);
    const app = builtApp('ios', root, (a) => {
      rmSync(join(a, 'Frameworks'), { recursive: true });
      mkdirSync(join(a, 'Frameworks'));
    });
    const { code, out } = runBuilt(app, root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /COVERAGE LOST/);
    assert.match(out, /has no Frameworks\/\*\.framework/);
  });

  test('COVERAGE LOST — an unmatched glob arrives as its own text and exits 2', () => {
    const root = capturedTree(null);
    const { code, out } = runBuilt(join(TMP, 'runner-temp', 'ipa-check-*', 'Payload', '*.app'), root);
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /is not a directory, so no built bundle was read/);
  });

  test('COVERAGE LOST — a glob that matched two bundles exits 2 rather than reading one of them', () => {
    const root = capturedTree(null);
    const { code, out } = runBuilt(builtApp('ios', root), root, builtApp('ios', root));
    assert.equal(code, 2, `COVERAGE LOST must exit 2, not ${code}:\n${out}`);
    assert.match(out, /--built takes ONE bundle and 2 were given/);
  });

  test('COVERAGE LOST — --built without --app exits 2 rather than guessing the audit', () => {
    const root = capturedTree(null);
    const r = spawnSync(process.execPath, [GUARD, '--built', builtApp('ios', root), root], { encoding: 'utf8' });
    assert.equal(r.status, 2, `${r.stdout}${r.stderr}`);
    assert.match(`${r.stdout}${r.stderr}`, /--built needs --app <slug>/);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// THE FIXTURE MAY NOT DRIFT FROM THE THING IT STANDS IN FOR.
// ─────────────────────────────────────────────────────────────────────────────
test('the committed fixture still matches the real generated file', (t) => {
  if (!havePluginDeps()) {
    // Not a skip that hides a failure: on a Flutter-less runner there is nothing
    // to compare AGAINST, and saying so is the honest report. The comparison runs
    // on every developer machine and in preflight, which is where a stale fixture
    // would be introduced in the first place.
    t.diagnostic(
      `no ${PLUGIN_DEPS_REL} on this machine (it is generated and gitignored), ` +
        'so the fixture could not be compared to it here. Run `flutter pub get` to make this case real.',
    );
    return;
  }
  const real = JSON.parse(readFileSync(realPluginDeps(), 'utf8'));
  const fixture = JSON.parse(readFileSync(PLUGIN_DEPS_FIXTURE, 'utf8'));
  for (const platform of PLATFORMS) {
    const names = (o) => (o.plugins?.[platform] ?? []).map((x) => x.name).sort();
    assert.deepEqual(
      names(fixture),
      names(real),
      `the ${platform} plugin set in tooling/ci/test/fixtures/subscriptiontracker.flutter-plugins-dependencies.json ` +
        'has drifted from the real generated file. Re-copy it: the fixture exists so this test file ' +
        'can run where the generated file does not, and a fixture nobody compares is one that rots.',
    );
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ⏱ 2026-09-26 — THE AUDIT'S DECLARED STATE (O-BRICK-SWORN-FILES-HAVE-NO-PREVIEW-STATE).
// The preview app is the brick's own audit template, rendered as mason renders
// it, beside the real app #1: what the app-brick probe job grades in CI.
// ─────────────────────────────────────────────────────────────────────────────
const BRICK_AUDIT = join(REPO, 'tooling', 'bricks', 'app', '__brick__', 'apps', '{{app_id}}', AUDIT_REL);

/** `apps/probe` carrying the brick's audit (`"sworn": false`) and an app.yaml
 *  building it for `platforms`. */
function stampProbe(root, platforms) {
  const audit = readFileSync(BRICK_AUDIT, 'utf8').replaceAll('{{app_id}}', 'probe').replaceAll('{{{short_name}}}', 'Probe');
  mkdirSync(join(root, 'apps', 'probe', dirname(AUDIT_REL)), { recursive: true });
  write(root, `apps/probe/${AUDIT_REL}`, audit);
  write(root, 'apps/probe/app.yaml', `id: probe\nplatforms:\n${platforms.map((p) => `  - ${p}\n`).join('')}`);
}

describe('⏱ 2026-09-26 — the audit\'s declared state', () => {
  test('the real audit says "sworn": true and the brick template says false', () => {
    assert.equal(JSON.parse(readFileSync(join(REPO, 'apps', APP, AUDIT_REL), 'utf8')).sworn, true);
    assert.equal(JSON.parse(readFileSync(BRICK_AUDIT, 'utf8')).sworn, false);
  });

  test('a stamped web-only preview app beside app #1 passes, and the log counts it', () => {
    const { code, out } = run(tree((root) => stampProbe(root, ['web'])));
    assert.equal(code, 0, out);
    assert.match(out, /1 sworn, 1 preview \(probe\) · a preview waives limbs 1 and 7\(a\); 0 manifest\(s\)/);
  });

  test('🔴 RC6 — a preview built for ios with no ios/ is exit 1, naming the manifest it owes', () => {
    const { code, out } = run(tree((root) => stampProbe(root, ['web', 'ios'])));
    assert.equal(code, 1, out);
    assert.match(out, /apps\/probe\/ios\/Runner\/PrivacyInfo\.xcprivacy does not exist/);
  });

  test('a preview built for ios whose manifest is in the Runner Resources phase passes', () => {
    const { code, out } = run(
      tree((root) => {
        stampProbe(root, ['web', 'ios']);
        for (const rel of [MANIFEST_REL.ios, PBXPROJ_REL.ios]) {
          mkdirSync(dirname(join(root, 'apps', 'probe', rel)), { recursive: true });
          cpSync(join(REPO, 'apps', APP, rel), join(root, 'apps', 'probe', rel));
        }
      }),
    );
    assert.equal(code, 0, out);
    assert.match(out, /1 sworn, 1 preview \(probe\) · a preview waives limbs 1 and 7\(a\); 1 manifest\(s\)/);
  });

  test('🔴 a preview built for macos with the manifest on disk and no project to carry it is exit 1', () => {
    const { code, out } = run(
      tree((root) => {
        stampProbe(root, ['web', 'macos']);
        mkdirSync(dirname(join(root, 'apps', 'probe', MANIFEST_REL.macos)), { recursive: true });
        cpSync(join(REPO, 'apps', APP, MANIFEST_REL.macos), join(root, 'apps', 'probe', MANIFEST_REL.macos));
      }),
    );
    assert.equal(code, 1, out);
    assert.match(out, /apps\/probe\/macos\/Runner\.xcodeproj\/project\.pbxproj: it does not exist/);
  });

  test('🔴 app #1\'s audit with "sworn" deleted is exit 1, naming the file', () => {
    const { code, out } = run(
      tree((root) => {
        const rel = `apps/${APP}/${AUDIT_REL}`;
        write(root, rel, mutated(read(root, rel), '  "sworn": true,\n', '', 'drop the sworn key'));
      }),
    );
    assert.equal(code, 1, out);
    assert.match(out, /privacy-manifest\.json carries no boolean "sworn" \(found null\)/);
  });

  test('🔴 every audit in preview is COVERAGE LOST (exit 2): nothing was compared', () => {
    const { code, out } = run(
      tree((root) => {
        const rel = `apps/${APP}/${AUDIT_REL}`;
        write(root, rel, mutated(read(root, rel), '  "sworn": true,\n', '  "sworn": false,\n', 'app #1 to preview'));
      }),
    );
    assert.equal(code, 2, out);
    assert.match(out, /every audit is a preview \("sworn": false\): subscriptiontracker/);
  });
});
