// ─────────────────────────────────────────────────────────────────────────────
// content-qa-checks.test.mjs — the recorded failing inputs for [pipeline 7]P-3.
//
// 🔴 WHAT WAS MISSING, AND IT IS NOT "THE STAGE IS UNBUILT". `qa.mjs` exists, it
// freezes FIVE `DECLARED_CHECKS`, `assert-publish-gate.mjs:44` imports `runQa`
// and ci.yml's `content_gate` job runs it on every push. But
// `grep -rln "runQa\|DECLARED_CHECKS" tooling/ci/test/` matched nothing before
// this file: five checks declared, wired, and NEVER ONCE PROVEN TO FIRE.
//
// The gate's only input in CI is the real frozen pack, which is valid by
// definition — so only the passing path was ever exercised, and every one of the
// five could have been deleted, inverted, or never have worked at all, and the
// gate would print `ok publish gate` exactly as it does today. This repo's own
// rule: an assertion you cannot write the failing input for is worse than none.
//
// ─────────────────────────────────────────────────────────────────────────────
// THE SHAPE, and why each limb is here:
//
//   1. DERIVED, NOT LISTED. The per-check cases below are generated by iterating
//      `DECLARED_CHECKS` at runtime and looking a fixture up by id. A sixth
//      declared check does not get a shorter suite — it gets a RED test naming
//      itself. A hand-written list of five `it()` blocks would silently keep
//      testing five.
//   2. ISOLATION. Each case asserts that EVERY problem returned names the check
//      under test. Without it a fixture could be "caught" by an unrelated check
//      — a planted email address that also happens to duplicate a key would
//      still go green with pii-scrub deleted.
//   3. NEGATIVE CONTROL. The unmutated pack must come back with ZERO problems,
//      or a case could pass because the input was already dirty.
//   4. THE EXIT CODE, through the REAL GUARD on a COPY OF THE REAL TREE. P-3
//      requires the qa stage to EXIT NON-ZERO, not to return an array. `runQa`
//      returning problems that nothing acts on is a gate that reports and
//      permits — so the last describe plants a defect in the committed pack
//      fixture and runs `assert-publish-gate.mjs` as CI runs it.
//
// ⛔ NOT WIDENED TO AUDIO/IMAGE ON PURPOSE. `recipe.mjs` declares
// `QA_IMPLEMENTED_MODALITIES = ['text']` and prints that restriction on every
// run. LUFS, ASR-WER and pHash each need a downloaded model, and every local QA
// model needs a `tooling/legal/content-licence-register.json` row BEFORE it runs
// ([pipeline 7]P-5 / G-36). Proving the TEXT checks fire is this file's job;
// adding a limb whose model has no licence row is a different increment.
// ─────────────────────────────────────────────────────────────────────────────
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, describe, it } from 'node:test';

import { DECLARED_CHECKS, runQa } from '../../content_pipeline/src/qa.mjs';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const RECIPE_REL = 'tooling/content_pipeline/examples/lingo-phrases/recipe.json';

/** The pack directory is DERIVED from the recipe's major version exactly as
 *  assert-publish-gate.mjs derives it, so a version bump moves both together
 *  rather than leaving this file reading a pack the gate no longer looks at. */
const RECIPE = JSON.parse(readFileSync(join(REPO, RECIPE_REL), 'utf8'));
const PACK_REL = `packages/core/test/fixtures/pack/v${RECIPE.pack_version.split('.')[0]}`;

/** A fresh parse per case. `structuredClone` of one parse would work too; a
 *  re-read is used because it also proves the committed bytes are what every
 *  case starts from, not a mutation left behind by the case before it. */
const realPack = () => ({
  content: JSON.parse(readFileSync(join(REPO, PACK_REL, 'content.json'), 'utf8')),
  prov: JSON.parse(readFileSync(join(REPO, PACK_REL, 'PROVENANCE.json'), 'utf8')),
});

// ─────────────────────────────────────────────────────────────────────────────
// ONE PLANTED DEFECT PER DECLARED CHECK.
//
// Each `plant` mutates a copy of the REAL committed pack — not a pack this file
// invented. A fixture you wrote encodes the same misunderstanding as the guard
// you wrote (assert-seams-wired.mjs shipped with six passing fixture tests over
// a version that could not catch the real defect), so the subject here is the
// artifact the gate actually reads, one field different.
//
// `expect` must name the reason, not merely be non-empty: "problems is not
// empty" is satisfied by a crash, by an unrelated check, and by a typo in the
// fixture.
// ─────────────────────────────────────────────────────────────────────────────
const FIXTURES = [
  {
    check: 'schema-validity',
    defect: 'a content value blanked to the empty string — what a partial write or a dropped translation leaves',
    plant: ({ content }) => {
      content.en['greeting.hello'] = '';
    },
    expect: /\[schema-validity\] en\/greeting\.hello: not a non-empty string/,
  },
  {
    check: 'assistant-tell',
    defect: 'model-voice leakage: the generator\'s refusal preamble shipped as the phrase itself',
    plant: ({ content }) => {
      content.en['greeting.hello'] = 'As an AI, the greeting is not available.';
    },
    expect: /\[assistant-tell\] en\/greeting\.hello: model-voice leakage/,
  },
  {
    check: 'pii-scrub',
    defect: 'a real email address in shipped copy',
    plant: ({ content }) => {
      content.en['greeting.hello'] = 'Write to ops@example.com for a greeting.';
    },
    expect: /\[pii-scrub\] en\/greeting\.hello: contains an email address/,
  },
  {
    check: 'intra-pack-dedup',
    defect: 'two keys in one locale carrying identical copy — the shape a truncated generation run leaves',
    plant: ({ content }) => {
      content.en['greeting.thank_you'] = content.en['greeting.hello'];
    },
    expect: /\[intra-pack-dedup\] en: "greeting\.thank_you" and "greeting\.hello" carry identical copy/,
  },
  {
    check: 'marking-declared',
    defect: 'a Gemini-image item declaring marking "none" — SynthID stripped in the optimize stage, which is the realistic way it goes missing',
    plant: ({ prov }) => {
      prov.items[0].generator_model_id = 'google/gemini-image';
    },
    expect: /\[marking-declared\] badge\.streak: google\/gemini-image applies SynthID and this item declares "none"/,
  },
];

describe('[pipeline 7]P-3 — the declared QA checks are COVERED by failing inputs', () => {
  it('COVERAGE — the fixture set equals the declared set, in both directions', () => {
    const declared = DECLARED_CHECKS.map((c) => c.id);
    const planted = FIXTURES.map((f) => f.check);

    assert.equal(
      new Set(planted).size,
      planted.length,
      `COVERAGE LOST — two fixtures name the same check (${planted.join(', ')}). ` +
        'Duplicates inflate the count and let a different check reach zero fixtures while the length still matches.',
    );
    const uncovered = declared.filter((id) => !planted.includes(id));
    assert.deepEqual(
      uncovered,
      [],
      `COVERAGE LOST — declared check(s) ${uncovered.join(', ')} have no planted failing input. ` +
        'A check with no failing input has never been proven to fire; the suite would stay green with it deleted.',
    );
    const orphans = planted.filter((id) => !declared.includes(id));
    assert.deepEqual(
      orphans,
      [],
      `COVERAGE LOST — fixture(s) ${orphans.join(', ')} name no declared check. ` +
        'A fixture aimed at a check that no longer exists proves nothing and pads the count.',
    );
    assert.equal(
      FIXTURES.length,
      DECLARED_CHECKS.length,
      `COVERAGE LOST — ${DECLARED_CHECKS.length} declared check(s), ${FIXTURES.length} fixture(s).`,
    );
  });

  it('NEGATIVE CONTROL — the real committed pack returns ZERO problems', () => {
    const { content, prov } = realPack();
    const r = runQa(RECIPE, content, prov);
    assert.deepEqual(
      r.problems,
      [],
      'the unmutated pack is already dirty, so every case below could pass without its planted defect mattering',
    );
    assert.ok(r.itemsChecked > 0, `COVERAGE LOST — runQa examined ${r.itemsChecked} content items on the real pack. A checker that reads nothing reports clean.`);
    assert.deepEqual(
      r.checks.map((c) => c.id),
      DECLARED_CHECKS.map((c) => c.id),
      'the report does not name every declared check',
    );
  });

  // 🔴 DERIVED FROM DECLARED_CHECKS AT RUNTIME. Adding a sixth check adds a
  // sixth case here that FAILS naming itself, rather than leaving five cases
  // that still pass.
  for (const declared of DECLARED_CHECKS) {
    it(`FAILS on a planted ${declared.id} defect — ${declared.what}`, () => {
      const fixture = FIXTURES.find((f) => f.check === declared.id);
      assert.ok(
        fixture,
        `COVERAGE LOST — declared check "${declared.id}" (${declared.modality}) has no planted failing input in this file. ` +
          'It is declared, reported, and never proven to fire.',
      );

      const pack = realPack();
      fixture.plant(pack);
      const r = runQa(RECIPE, pack.content, pack.prov);

      assert.ok(
        r.problems.length > 0,
        `NOT CAUGHT — ${declared.id}: ${fixture.defect}\nrunQa returned no problem at all.`,
      );
      assert.match(r.problems.join('\n'), fixture.expect, `${declared.id}: caught, but the message does not name the reason`);
      // ISOLATION — every problem must be this check's. Otherwise the case could
      // stay green with `declared.id` deleted, "caught" by a neighbour.
      const foreign = r.problems.filter((p) => !p.startsWith(`[${declared.id}]`));
      assert.deepEqual(
        foreign,
        [],
        `${declared.id}: the planted defect also tripped another check — ${foreign.join(' | ')}. ` +
          'A case that is caught by a neighbour proves the neighbour, not the check under test.',
      );
    });
  }
});

// The second branch of two checks whose single fixture above exercises only one
// path. Kept OUT of FIXTURES so the length assertion stays one-per-check.
describe('[pipeline 7]P-3 — the second branch of the two-branch checks', () => {
  it('pii-scrub also catches a phone-shaped digit run, not just an email', () => {
    const { content, prov } = realPack();
    content.en['greeting.hello'] = 'Call 044 2841 9000 to say hello.';
    const r = runQa(RECIPE, content, prov);
    assert.match(r.problems.join('\n'), /\[pii-scrub\] en\/greeting\.hello: contains a long digit run \(phone-shaped\)/);
  });

  it('marking-declared also catches a generator with NO declared marking behaviour', () => {
    const { content, prov } = realPack();
    prov.items[0].generator_model_id = 'some-vendor/undeclared-model';
    const r = runQa(RECIPE, content, prov);
    assert.match(
      r.problems.join('\n'),
      /\[marking-declared\] badge\.streak: generator "some-vendor\/undeclared-model" has no declared marking behaviour/,
    );
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// THE EXIT CODE. Everything above proves `runQa` RETURNS problems; P-3 requires
// the stage to EXIT NON-ZERO. A `runQa` whose problems nothing forwards is a
// gate that reports and permits, and it is one deleted `for` loop away.
// ─────────────────────────────────────────────────────────────────────────────
const trees = [];
after(() => {
  for (const t of trees) rmSync(t, { recursive: true, force: true });
});

/** A copy of the real tree's stage-7 subject. Copied, not invented — the guard
 *  reads the committed pack fixture, the committed gates dirs, the drill record
 *  and the workflow YAML, and a tree missing any of them fails for a reason that
 *  has nothing to do with QA. */
function tree() {
  const dst = mkdtempSync(join(tmpdir(), 'nk-qa-'));
  trees.push(dst);
  for (const rel of ['tooling/ci', 'tooling/content_pipeline', 'tooling/legal', 'packages/core/test/fixtures', '.github/workflows']) {
    cpSync(join(REPO, rel), join(dst, rel), { recursive: true });
  }
  return dst;
}

const runGate = (root) => spawnSync(process.execPath, [join(root, 'tooling', 'ci', 'assert-publish-gate.mjs'), root], { encoding: 'utf8', cwd: root });

const plantInPack = (root, member, f) => {
  const p = join(root, PACK_REL, member);
  const o = JSON.parse(readFileSync(p, 'utf8'));
  f(o);
  writeFileSync(p, `${JSON.stringify(o, null, 2)}\n`);
};

describe('[pipeline 7]P-3 — the qa stage EXITS NON-ZERO, through the real guard', () => {
  it('the unmutated tree passes — or nothing below means anything', () => {
    const r = runGate(tree());
    assert.equal(r.status, 0, `${r.stdout}\n${r.stderr}`);
    assert.ok(existsSync(join(REPO, PACK_REL, 'content.json')), 'the pack fixture the gate reads is not where this test plants defects');
  });

  for (const [label, member, plant, expect] of [
    ['a PII email address', 'content.json', (o) => { o.en['greeting.hello'] = 'Write to ops@example.com for a greeting.'; }, /QA: \[pii-scrub\].*email address/],
    ['model-voice leakage', 'content.json', (o) => { o.en['greeting.hello'] = 'As an AI, the greeting is not available.'; }, /QA: \[assistant-tell\]/],
    ['a duplicated key', 'content.json', (o) => { o.en['greeting.thank_you'] = o.en['greeting.hello']; }, /QA: \[intra-pack-dedup\]/],
    ['a stripped SynthID mark', 'PROVENANCE.json', (o) => { o.items[0].generator_model_id = 'google/gemini-image'; }, /QA: \[marking-declared\].*applies SynthID/],
  ]) {
    it(`exits non-zero, naming the check, on ${label} in the shipped pack`, () => {
      const t = tree();
      plantInPack(t, member, plant);
      const r = runGate(t);
      const out = `${r.stdout}\n${r.stderr}`;
      assert.notEqual(r.status, 0, `the publish gate exited 0 with ${label} in the pack it gates\n${out}`);
      assert.ok(!/SyntaxError|ReferenceError|ERR_MODULE/.test(out), `the gate CRASHED rather than caught\n${out}`);
      assert.match(out, expect, `caught, but the gate's message does not name the QA check\n${out}`);
    });
  }
});
