// ─────────────────────────────────────────────────────────────────────────────
// artifact-build.mjs — THE ONE TABLE IN THIS TEMPLATE, and the only fact on the
// whole page that is typed rather than read out of a register.
//
// It is not a guard and it scans nothing. It is a declaration, imported by
// resolve-slot.mjs (which uses it) and by assert-slot-pipeline.mjs (which holds
// it to tooling/channel-register.json in BOTH directions). It sits in its own
// file for exactly that reason: a table declared inside its only consumer is a
// table nothing else can check, and this corpus already records what a value
// with no reader costs — `uploadCertificate._aliasNote` in the channel register
// is the entry that went stale for weeks because nothing read it.
//
// ── WHY THE FACT NEEDS A HOME AT ALL ────────────────────────────────────────
// No file in this tree records WHICH BUILD VERB EMITS WHICH ARTIFACT FORMAT.
// tooling/channel-register.json says Google Play takes `.aab`; nothing says that
// `.aab` comes from `flutter build appbundle` and never from `flutter build
// apk`. That gap has already been expensive here: the register recorded a
// FORMAT GAP for months while the only Android artifact in the tree was an
// .apk, which Play does not accept.
//
// 🔴 `packagedBy` IS THE LOAD-BEARING HALF, NOT AN ANNOTATION.
// `flutter build windows` produces a directory of loose binaries, NOT an .msix.
// `flutter build linux` does not produce a .snap. A template that mapped format
// to verb and stopped there would print "built .msix" over a folder of DLLs and
// hand it to a submission step. So every format records WHERE its packaging
// happens, and where nothing in this repository does it, that is what it says.
//
// The value is prose on purpose. A boolean would invite a pipeline to branch on
// it; a sentence naming the script or the workflow forces a reader to go and
// look at the thing that actually packages, which is the only place the truth
// is. This module is data, so a wrong sentence here is caught by review, and a
// MISSING key is caught by assert-slot-pipeline.mjs on every run.
// ─────────────────────────────────────────────────────────────────────────────

/** artifactFormat (as spelled in tooling/channel-register.json) -> how it is
 *  actually produced. Keys must equal the register's format set exactly; that
 *  equality is asserted, in both directions, by assert-slot-pipeline.mjs. */
export const ARTIFACT_BUILD = {
  'static-bundle': {
    flutterTarget: 'web',
    packagedBy: null,
  },
  '.aab': {
    flutterTarget: 'appbundle',
    packagedBy: null,
  },
  '.ipa': {
    flutterTarget: 'ipa',
    packagedBy: null,
  },
  '.pkg': {
    flutterTarget: 'macos',
    packagedBy: 'productbuild + notarisation — tooling/ci/apple-signing.mjs and the Apple lane. NOT this template.',
  },
  '.msix': {
    flutterTarget: 'windows',
    packagedBy: '`dart run msix:create` — the lane workflow the register names. NOT this template.',
  },
  '.exe': {
    flutterTarget: 'windows',
    packagedBy: 'installer packaging — NOT IMPLEMENTED ANYWHERE IN THIS REPOSITORY. The windows-direct channel declares this format and nothing emits it.',
  },
  '.snap': {
    flutterTarget: 'linux',
    packagedBy: '`snapcraft pack` over a recipe generated by tooling/release/generate-snapcraft.mjs — the lane workflow. NOT this template.',
  },
  '.AppImage': {
    flutterTarget: 'linux',
    packagedBy: 'AppImage packaging — tooling/ci/appimage-signing.mjs and its lane. NOT this template.',
  },
};

/** Every artifact format the register names, derived from the register itself so
 *  the comparison in assert-slot-pipeline.mjs is against the real set and never
 *  against a second list. */
export function registerFormats(register) {
  const set = new Set();
  for (const ch of register.channels ?? []) for (const f of ch.artifactFormats ?? []) set.add(f);
  return set;
}
