// GENERATED by tooling/catalog/render-rail-prices.mjs from services/platform/src/app-config-data.json `prices`.
// Do not edit: `render-rail-prices.mjs --check` re-renders this file and fails on any difference.
// Change a rail id or its amount only after a read of the vendor's own catalogue, in the register's
// `rails`, then re-render. Why each map exists is the renderer's header (O-RAIL-PRICE-IDS-HAND-KEPT).

// OUR offering id → PADDLE's price id, per app. A caller never names a price; checkout.ts resolves it here.
export const PADDLE_PRICE_IDS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  fullshot: {},
  subscriptiontracker: {
    pro_monthly: 'pri_01m346p0fjtaffk6waj5x5vz1c',
    pro_yearly: 'pri_01m346p0v8103kqy1zb8zmmj7y',
    pro_lifetime: 'pri_01m346p14yzeqjjwj153thx8p2',
  },
};

// What each mapped Paddle price costs ON PADDLE, in minor units, as read back (the time is the register's `readAt`).
export const RAIL_PRICE_AMOUNTS_MINOR: Readonly<Record<string, Readonly<Record<string, number>>>> = {
  fullshot: {},
  subscriptiontracker: {
    pro_monthly: 599, // read back 2026-09-22T09:20:50Z
    pro_yearly: 3499, // read back 2026-09-22T09:20:50Z
    pro_lifetime: 8900, // read back 2026-09-26T23:43:12Z
  },
};

// Served offerings Paddle cannot sell at that price today, each with its reason. Empty for an app whose paywall is on.
export const RAIL_PRICE_PENDING: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  fullshot: {
    pro_monthly: 'no Paddle price exists yet: the sandbox price is created through the Paddle API with the vault key and read back here, and the live price waits for the owner\'s word at the first FullShot store submission',
    pro_yearly: 'no Paddle price exists yet: the sandbox price is created through the Paddle API with the vault key and read back here, and the live price waits for the owner\'s word at the first FullShot store submission',
  },
  subscriptiontracker: {},
};

// OUR offering id → RAZORPAY's plan id, per app. Empty until Razorpay PR B and the owner's plans ([ADR 094]).
export const RAZORPAY_PLAN_IDS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  fullshot: {},
  subscriptiontracker: {},
};

// Served offerings Razorpay cannot sell today, each with its reason. Razorpay PR B reads this map.
export const RAZORPAY_PRICE_PENDING: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  fullshot: {
    pro_monthly: 'no Razorpay plan exists yet: the owner creates it (ADR 094), and Razorpay PR B reads it from here',
    pro_yearly: 'no Razorpay plan exists yet: the owner creates it (ADR 094), and Razorpay PR B reads it from here',
  },
  subscriptiontracker: {
    pro_monthly: 'no Razorpay plan exists yet: the owner creates it (ADR 094), and Razorpay PR B reads it from here',
    pro_yearly: 'no Razorpay plan exists yet: the owner creates it (ADR 094), and Razorpay PR B reads it from here',
    pro_lifetime: 'not sold in India: the Razorpay order path (POST /v1/orders) is not built, so this one-time offering carries no webInrMinor and is out of the India book (render-rail-prices.mjs limb J) until it is and the owner creates the item (ADR 094)',
  },
};

// RAIL → OUR offering id → that rail's sellable id, per app: the map the payments port reads
// (RAIL_PRICE_IDS[railId][appId][offeringId]). Keyed by tooling/ports/payments.json adapter ids.
export const RAIL_PRICE_IDS: Readonly<Record<string, Readonly<Record<string, Readonly<Record<string, string>>>>>> = {
  paddle: PADDLE_PRICE_IDS,
  razorpay: RAZORPAY_PLAN_IDS,
};
