/// The pinned Ed25519 public keys used to verify every remote content pack's
/// signature, keyed by the manifest's `key_id` (ADR 007 + ADR 016). SINGLE
/// SOURCE OF TRUTH — the [PackVerifier] impl selects its key from here.
///
/// **Why a map and not one constant (ADR 016):** the pinned key is baked into
/// every released binary on all 6 platforms. With a single key and no rotation
/// field, a *compromised* key can never be revoked — every installed app would
/// be stuck trusting it until a synchronised store update, and users who never
/// update are permanently stranded. Cold-storage backup covers key *loss*;
/// only `key_id` covers *compromise*. The field must exist BEFORE the first pack
/// ships, because older binaries can't be taught to read it afterwards.
///
/// Losing the private key = no pack signed with that `key_id` can ever be
/// updated again — back it up with a restore drill before the first signed pack
/// ships.
///
/// 📌 CORRECTED 2026-08-21 — a PLACEHOLDER paragraph describing an EMPTY map
/// stood here while the literal below held a real key. It is preserved verbatim,
/// with the measurements that retired it, in the CORRECTIONS block below the map.
///
/// Rotation: ADD the new entry, keep the old one until no shipped binary needs
/// it, and sign new packs with the new `key_id`. Never reuse a retired `key_id`.
/// PINNED 2026-07-27 (`OWNER_QUEUE` S-3, [ADR 022]). Base64 of the raw 32-byte
/// Ed25519 public key. Generated by `tool/gen_pack_keypair.dart` using the same
/// `cryptography` package this file verifies with, so the encoding cannot drift
/// between generation and verification.
///
/// The private seed lives in `.claude/pack-signing.seed` (backed up to Drive)
/// **and** on paper — two copies that fail differently. See [ADR 022].
const Map<String, String> kContentPackPublicKeys = <String, String>{
  'k1': 'zcrBolFZjWixE+0UF0Qbd6T2jUKGkWgAWtJVmYdK6dQ=',
};

// ── 🔴 ANCHOR — 2026-08-21. LINE 28 ABOVE IS CITED BY NUMBER FROM ANOTHER ────
// ── FILE. DO NOT INSERT ANYTHING ABOVE IT. ──────────────────────────────────
// `tooling/ci/assert-stamp-properties.mjs` reads "the path
// packages/core/lib/src/content/pack_verifier.dart:28 documents", meaning the
// `.claude/pack-signing.seed` line in the doc comment above this map. The
// 2026-08-21 corrections to this file were first written INTO that doc comment,
// which pushed the seed line down (to :67 on that intermediate tree, measured
// there and independently by a reviewer) and silently broke the pointer. That 67
// is history, not a fact about this file — nothing here is at :67 any more.
// THE REPAIR TAKEN WAS TO PUT THE LINE BACK rather than to renumber a file this
// change does not own: every word this session added above the map was moved
// below it, so lines 20–32 are byte-identical to `git show HEAD:` on this file
// and :28 is the seed line again. Re-take that, do not trust this sentence:
//     grep -n "^/// The private seed lives in" \
//       packages/core/lib/src/content/pack_verifier.dart
// The `^///` anchor matters — without it the grep also matches the recipe line
// in this note and returns TWO lines, not one. The restore re-lands the map
// literal on 30–32 and `'k1'` on :31, which is how the private repo cites them.
// ⚠️ THIS IS A DISCIPLINE, NOT A GUARD, and the durable repair is not this
// file's to make. Measured 2026-08-21 while the pointer was still broken:
// `node tooling/scripts/assert-public-citations.mjs` → EXIT 0, "every citation
// resolves", 1259 tracked file(s); a citation that lands on the WRONG real line
// is not something it reports. (It lives under tooling/scripts/, not
// tooling/ci/ — a `node tooling/ci/assert-public-citations.mjs` in this session
// died MODULE_NOT_FOUND, which reads exactly like a guard that failed.) The
// repair that would never need re-taking belongs to the owner of
// assert-stamp-properties.mjs: cite the seed line the way this file now cites
// `Ed25519PackVerifier`, by its searchable sentence, with no number. A line
// number is a pointer into a file other people edit; this corpus has broken 203
// and 218 citations that way twice, and this session made it three.

// ── 📌 CORRECTIONS, 2026-08-21 — KEPT BELOW THE MAP, NOT AT THE SENTENCES ───
// ── THEY CORRECT, FOR THE REASON THE ANCHOR NOTE ABOVE GIVES ────────────────
// FOUR sentences in this file described a world that ended on 2026-07-27, when
// `k1` was generated and pinned. All four are corrected where they stood; what
// they SAID, and the measurements that retired them, are kept here, because a
// correction that deletes what it corrects cannot itself be checked. The
// backlog entry this came from named ONE of the four; the file carried four.
// The tree wins.
//
// (1) THE HEADER'S THIRD LINE read "SOURCE OF TRUTH — the app-layer
//     [PackVerifier] impl selects its key from here". It has not been app-layer
//     since ADR 007 was amended on 2026-07-26 by owner decision (`pipeline
//     C-6`): the only impl is `Ed25519PackVerifier`, in THIS package, as the
//     seam's own doc at [PackVerifier] already records. One word, so it was
//     fixed in place rather than given a block of its own. Found while
//     correcting the other three.
//
// (2) A PLACEHOLDER PARAGRAPH stood where the forward pointer now sits, and it
//     described an EMPTY map while a real key sat in the very literal it
//     documents — in the pre-correction file that paragraph ended at :19 and
//     the `'k1'` entry was at :31, twelve lines below, so one doc comment
//     carried both halves of a contradiction. Kept verbatim, at the ORIGINAL
//     wrap points so that every line below, from the first non-space character
//     onward, is byte-identical to the corresponding line of
//     `git show HEAD:packages/core/lib/src/content/pack_verifier.dart` — a
//     re-wrapped quotation is one no `grep -F` can find, which is not a
//     preserved quotation at all:
//
//       PLACEHOLDER until the owner generates the pack-signing keypair (OWNER_QUEUE
//       S-3): the private key goes to `.claude/` (never git), the public key is pinned
//       here as `{'k1': '<base64 of the raw 32-byte key>'}`. While this map is empty a
//       correct [PackVerifier] MUST reject remote packs (only the trusted bundled base
//       loads), so no unsigned CDN content is ever accepted. Losing the private key =
//       no pack signed with that `key_id` can ever be updated again — back it up with
//       a restore drill before the first signed pack ships.
//
//     (The last two lines are the surviving third sentence, quoted here for
//     completeness; they still stand above as their own paragraph.)
//     The paragraph had exactly THREE sentences and only the third survives.
//     Count them before citing one — the last pass at this same defect class
//     miscited a paragraph's sentence count twice, which is why it is spelled
//     out here.
//     MEASURED THIS RUN, not inherited from a note: the map literal above
//     carries ONE entry, `'k1'`, a 44-character base64 value, so the "while
//     this map is empty" premise has no subject on any build made from this
//     tree. The PINNED 2026-07-27 paragraph was APPENDED when the key landed
//     and the placeholder above it was simply left standing, which is precisely
//     how one file comes to assert a thing and its negation.
//     STILL OPEN, and much narrower than the deleted text implies: what remains
//     of OWNER_QUEUE S-3 is owner CUSTODY, not key generation. Read this run,
//     `tooling/channel-register.json`'s `content-pack-k1.restoreDrill` is
//     `"date": null` with `"required": true`. Pointed at that FIELD rather than
//     restated here, so the next reader checks a value instead of trusting a
//     sentence — but do NOT expect anything to go red when it goes stale.
//
// (3) and (4) are `isContentPackKeyConfigured` and `RejectingPackVerifier`.
//     Their superseded text is preserved at their own declarations below, where
//     no line number points, so it did not have to move.
//
// LATENT, never live, for all four: these are `///` comments. No code path, no
// test and no guard reads one, and no behaviour moved in either direction while
// they were wrong. What it cost was reader trust.

/// The pinned public key for [keyId] (base64 of the raw 32-byte Ed25519 key), or
/// null when that `key_id` is not pinned in this build. A null result MUST be
/// treated as "reject the pack" — never as "skip verification" (ADR 016).
String? contentPackPublicKeyFor(String keyId) => kContentPackPublicKeys[keyId];

/// Whether at least one real pack-signing key has been pinned. TRUE on this
/// tree since `k1` was pinned on 2026-07-27.
///
/// 📌 CORRECTED 2026-08-21. The second sentence here read: "False until S-3
/// lands, and while false every remote pack fails closed." S-3's KEY half landed
/// on 2026-07-27 — `nikatru/OWNER_QUEUE.md`'s S-3 row reads "🟢 KEY GENERATED +
/// PINNED 2026-07-27 — `main` @ `64f90a5` (PR #34)", opened and read this run —
/// so this getter had been returning true for over three weeks while its own doc
/// said it was false. The fail-closed clause is not deleted, only re-scoped: it
/// describes a build whose map is EMPTY, which this one is not. Per-pack
/// fail-closed behaviour is unchanged and is stated where it is actually
/// binding, in [PackVerifier.verify]'s contract — an unknown or unpinned
/// `key_id` returns false, never "skip verification".
///
/// UNUSUALLY FOR THIS CLASS THE UNDERLYING FACT IS MACHINE-DEFENDED, which is
/// exactly why the COMMENT and not the code is what rotted. Proved this run
/// rather than asserted, and re-run after this file's last edit: a scratchpad
/// copy of this package with the `k1` entry deleted took `dart test` in
/// `packages/core` from 307 pass / 0 fail / EXIT 0 to 305 pass / 2 fail /
/// EXIT 1 — `content_pack_test.dart` ("the production key is pinned, and only
/// the pinned id resolves") and `ed25519_pack_verifier_test.dart` ("a real
/// pinned key still rejects a garbage signature"), both failing
/// `Expected: true / Actual: <false>`.
///
/// WHAT THAT DOES NOT CATCH IS THIS PARAGRAPH. No test reads a `///` comment, so
/// the correction is defended by nothing and can rot again in silence; the tests
/// above defend the VALUE, not the sentence about it.
bool get isContentPackKeyConfigured => kContentPackPublicKeys.isNotEmpty;

/// Seam for Ed25519 signature verification of a content pack manifest.
///
/// The real implementation is [Ed25519PackVerifier], **in this package**
/// (ADR 007 amended 2026-07-26 by owner decision — `pipeline C-6`). The seam is
/// kept because it earns its keep for test fakes and for [RejectingPackVerifier];
/// it is no longer a promise that an app layer will supply the implementation.
/// For eight months nothing did, and the only impl in the repo rejected every
/// pack unconditionally.
abstract interface class PackVerifier {
  /// Whether [signature] is a valid Ed25519 signature over [message] for the
  /// key pinned under [keyId] in [kContentPackPublicKeys]. MUST return false
  /// (never throw) when [keyId] is unknown/unconfigured or the signature/inputs
  /// are malformed — the fail-closed posture of ADR 007.
  Future<bool> verify({
    required String keyId,
    required List<int> message,
    required List<int> signature,
  });
}

/// A [PackVerifier] that rejects everything. With this verifier only a trusted
/// bundled base pack loads; every remote pack is refused — and it is still the
/// default `verifier` argument of `ContentPackLoader` (`content_pack_loader.dart`,
/// its constructor), so a caller that injects nothing gets the refusing posture
/// rather than an accidental open path.
///
/// 📌 CORRECTED 2026-08-21 — the opening line called this "the safe default
/// before a real Ed25519 impl + pinned keys exist (OWNER_QUEUE S-3)". BOTH now
/// exist, measured this run: `class Ed25519PackVerifier implements PackVerifier`
/// is declared in `packages/core/lib/src/content/ed25519_pack_verifier.dart`
/// — `grep -cF` that exact class line against that file returns 1, taken
/// after this file's last edit — and the map above carries `k1`. The CLASS
/// did not become wrong when they landed — only
/// the "before … exist" framing did, so the sentence now says what this verifier
/// IS and where it is still wired, instead of describing a world that ended on
/// 2026-07-27. Named by structure and not by line number, deliberately: a line
/// number is a pointer into a file other people edit, and this correction's own
/// sibling in tooling/ci/assert-submission-safety.mjs exists because two of them
/// went stale.
/// *(📌 That sentence spent part of 2026-08-21 sitting eight lines under a
/// `…/ed25519_pack_verifier.dart:28` citation in this same block — one paragraph
/// asserting the rule and breaking it. Repointed at the class declaration, in
/// place rather than by appended note, because a line number left standing under
/// a note about line numbers is the defect twice. The SECOND pointer this
/// session broke — the `pack_verifier.dart:28` one in
/// `tooling/ci/assert-stamp-properties.mjs`, a file this change does not own —
/// was repaired the other way round, by moving this session's new prose BELOW
/// the map so the cited line returned to :28. See the 🔴 ANCHOR note there.)*
class RejectingPackVerifier implements PackVerifier {
  const RejectingPackVerifier();

  @override
  Future<bool> verify({
    required String keyId,
    required List<int> message,
    required List<int> signature,
  }) async =>
      false;
}
