#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// generate-dart.mjs — write the Dart view of the ISO 4217 table, or prove the
// committed file still agrees with it.
//
//   node contracts/currency/generate-dart.mjs           rewrite the .g.dart
//   node contracts/currency/generate-dart.mjs --check    exit 1 if it would change
//
// The same pattern as contracts/entitlement/generate-dart.mjs, for the same
// reason: the Workers import `iso4217.js` itself, and Dart cannot import
// JavaScript, so the only honest options are a hand-kept transcription (which
// is what money.dart's two-entry map was, and it disagreed with the platform's
// list — #1118 review finding 3) or a generated one. The output is COMMITTED:
// packages/core has no codegen step, and a committed file makes a drift a diff.
// No dependencies: plain node.
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MINOR_UNIT_DIGITS } from './iso4217.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const REL = 'packages/core/lib/src/money/iso4217.g.dart';
const OUT = join(ROOT, REL);
const check = process.argv.includes('--check');

const entries = Object.entries(MINOR_UNIT_DIGITS).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
// A COVERAGE SELF-CHECK: an empty table renders as valid Dart and would make
// every code "unknown" — every amount printed with two decimals, silently.
if (entries.length < 150) {
  console.error(`✗ COVERAGE LOST — iso4217.js exported ${entries.length} codes; ISO 4217 has more than 150.`);
  console.error(`  ${REL} would be written short, and every missing code would read as two decimals.`);
  process.exit(2);
}
for (const [code, digits] of entries) {
  if (!/^[A-Z]{3}$/.test(code) || !Number.isInteger(digits) || digits < 0 || digits > 4) {
    console.error(`✗ iso4217.js row ${code}: ${digits} is not a three-letter code with 0-4 minor digits.`);
    process.exit(1);
  }
}

const body = [
  '// GENERATED by contracts/currency/generate-dart.mjs from contracts/currency/iso4217.js.',
  '// Never hand-edit it: `node contracts/currency/generate-dart.mjs --check` fails on a diff.',
  '',
  '/// ISO 4217 minor-unit digits by alphabetic code — THE ONE TABLE, shared with',
  '/// the subscriptiontracker-api Worker (which refuses a code not in it) and the',
  '/// platform Worker (which prints reminder prices with it).',
  'const Map<String, int> iso4217MinorUnitDigits = <String, int>{',
  ...entries.map(([code, digits]) => `  '${code}': ${digits},`),
  '};',
  '',
].join('\n');

let current = null;
try {
  current = readFileSync(OUT, 'utf8');
} catch {
  current = null;
}
if (check) {
  if (current !== body) {
    console.error(`✗ ${REL} is not what contracts/currency/iso4217.js generates.`);
    console.error('  Run `node contracts/currency/generate-dart.mjs` and commit the result.');
    process.exit(1);
  }
  console.log(`✓ ${REL} matches iso4217.js (${entries.length} codes).`);
  process.exit(0);
}
writeFileSync(OUT, body);
console.log(`wrote ${REL} (${entries.length} codes).`);
