/**
 * Nikatru brand tokens - Style Dictionary v5 configuration.
 *
 * SCOPE: THE WEBSITES ONLY. One platform, one output:
 *
 *   css -> ../../sites/_shared/assets/tokens.css
 *          CSS custom properties. Names mirror the live nikatru.com :root
 *          exactly (incl. --brand-ink), with dark values in a
 *          `@media (prefers-color-scheme: dark)` block.
 *
 * ── WHY THERE IS NO LONGER A DART OUTPUT (removed 2026-07-26) ──────────────
 * A Dart token class encodes ONE fixed palette. The app factory is explicitly
 * MULTI-BRAND: the Mason brick takes a per-app `seed_hex` and
 * `design_system/build_app_theme.dart` derives the whole Material 3 scheme via
 * `ColorScheme.fromSeed`. So a single generated palette could only ever be
 * correct if all 50 apps shared one brand — which contradicts the brick.
 * `build/nikatru_tokens.dart` had zero consumers for exactly that reason.
 *
 * The websites are the opposite case: nikatru.com and rajasekarselvam.com are
 * ONE company brand, so generated tokens are precisely right for them, and
 * that is the whole remit of this package now.
 *
 * Genuinely cross-app values that are NOT colour (spacing, type scale, radii)
 * live in `packages/design_system` as Dart constants and belong there.
 *
 * ── WHY IT WRITES STRAIGHT INTO sites/_shared ──────────────────────────────
 * It previously emitted to `build/`, which nothing read, while
 * `sites/_shared/assets/tokens.css` was a hand-maintained snapshot whose own
 * header said it "will be REPLACED by the generated output of packages/tokens".
 * That left THREE copies of the brand palette and made the generated one a
 * decoy: editing tokens/color.json changed nothing and CI still passed.
 * Emitting directly to the consumed path collapses that to one source of truth,
 * and the CI drift check now guards the file the sites actually serve.
 *
 * A custom format is used (instead of the built-in `css/variables`) so that:
 *   - the CSS variable names match the live site byte-for-byte,
 *   - the dark palette ships as a prefers-color-scheme override block,
 *   - output carries no timestamps, keeping rebuilds byte-identical
 *     (which is what makes the CI drift check meaningful).
 */

/* --------------------------------------------------------------------- */
/* Canonical ordering - locked so output is deterministic and reviewable. */

const LIGHT_COLORS = [
  'ink', 'ink-2', 'primary', 'teal', 'bg', 'card', 'card-2',
  'text', 'strong', 'muted', 'line',
];
const DARK_COLORS = ['bg', 'card', 'card-2', 'text', 'strong', 'muted', 'line'];

const HEADER_CSS = `/**
 * Nikatru brand tokens - generated by Style Dictionary. DO NOT EDIT BY HAND.
 * Edit packages/tokens/tokens/*.json and run \`npm run build\`.
 * Variable names intentionally mirror the live nikatru.com :root.
 */`;

/* ------------------------------------------------------------------ */
/* Helpers                                                            */

const raw = (token) => token.$value ?? token.value;

/** Collect one top-level token group into `name -> value` (path minus group, kebab-joined). */
function groupMap(dictionary, group) {
  const map = new Map();
  for (const token of dictionary.allTokens) {
    if (token.path[0] === group) map.set(token.path.slice(1).join('-'), raw(token));
  }
  return map;
}

/** Fail the build loudly if a required token disappears or is renamed. */
function must(map, key, group) {
  if (!map.has(key)) throw new Error(`[@nikatru/tokens] missing required token "${group}.${key}"`);
  return map.get(key);
}

/** Live-site CSS custom-property name for a color token. */
const cssVar = (name) => (name === 'ink' ? 'brand-ink' : name);

/** DTCG dimension -> CSS string ('16px' or {value:16, unit:'px'} -> '16px'). */
const dimToCss = (v) => (typeof v === 'object' && v !== null ? `${v.value}${v.unit}` : String(v));

/* ------------------------------------------------------------------ */
/* Formats                                                            */

function formatCss({ dictionary }) {
  const light = groupMap(dictionary, 'color');
  const dark = groupMap(dictionary, 'dark');
  const font = groupMap(dictionary, 'font');
  const size = groupMap(dictionary, 'size');

  const lines = [HEADER_CSS, '', ':root {'];
  for (const name of LIGHT_COLORS) {
    lines.push(`  --${cssVar(name)}: ${must(light, name, 'color')};`);
  }
  lines.push(`  --radius: ${dimToCss(must(size, 'radius', 'size'))};`);
  lines.push(`  --font-display: "${must(font, 'display', 'font')}";`);
  lines.push(`  --font-body: "${must(font, 'body', 'font')}";`);
  lines.push('}', '', '@media (prefers-color-scheme: dark) {', '  :root {');
  for (const name of DARK_COLORS) {
    lines.push(`    --${cssVar(name)}: ${must(dark, name, 'dark')};`);
  }
  lines.push('  }', '}');
  return lines.join('\n') + '\n';
}

/* ------------------------------------------------------------------ */

export default {
  source: ['tokens/**/*.json'],
  hooks: {
    formats: {
      'nikatru/css': formatCss,
    },
  },
  platforms: {
    css: {
      transforms: ['name/kebab'],
      buildPath: '../../sites/_shared/assets/',
      files: [{ destination: 'tokens.css', format: 'nikatru/css' }],
    },
  },
};
