// GENERATED by `node tooling/ci/assert-locale-register.mjs --write` from
// packages/design_system/lib/src/l10n/chassis_en.arb and this app's app_en.arb. NEVER HAND-EDIT: the guard
// fails CI when this file and the two ARBs disagree.
//
// Every chassis key this app's ARB does not declare, readable through the
// app's own `AppLocalizations` — so a call site reads `l10n.settingsTitle`
// and gets the CHASSIS value: one translation, one fix, for every app.
// app_localizations.dart exports this file (l10n.yaml `header`).
import 'package:flutter/widgets.dart' show Locale;
import 'package:nikatru_design_system/nikatru_design_system.dart';

import 'app_localizations.dart';

/// The chassis keys, read through the app's own catalogue.
extension ChassisKeys on AppLocalizations {
  ChassisLocalizations get _chassis => this is ChassisLocalizations
      ? this as ChassisLocalizations
      : lookupChassisLocalizations(Locale(localeName));

  /// [ChassisLocalizations.settingsTitle].
  String get settingsTitle => _chassis.settingsTitle;

  /// [ChassisLocalizations.contactSupport].
  String get contactSupport => _chassis.contactSupport;

  /// [ChassisLocalizations.deleteAccount].
  String get deleteAccount => _chassis.deleteAccount;

  /// [ChassisLocalizations.appearance].
  String get appearance => _chassis.appearance;

  /// [ChassisLocalizations.themeSystem].
  String get themeSystem => _chassis.themeSystem;

  /// [ChassisLocalizations.themeLight].
  String get themeLight => _chassis.themeLight;

  /// [ChassisLocalizations.themeDark].
  String get themeDark => _chassis.themeDark;

  /// [ChassisLocalizations.deleteAccountSubtitle].
  String get deleteAccountSubtitle => _chassis.deleteAccountSubtitle;

  /// [ChassisLocalizations.deleteAccountConfirmTitle].
  String get deleteAccountConfirmTitle => _chassis.deleteAccountConfirmTitle;

  /// [ChassisLocalizations.deleteAccountConfirmBody].
  String get deleteAccountConfirmBody => _chassis.deleteAccountConfirmBody;

  /// [ChassisLocalizations.cancel].
  String get cancel => _chassis.cancel;

  /// [ChassisLocalizations.delete].
  String get delete => _chassis.delete;

  /// [ChassisLocalizations.about].
  String get about => _chassis.about;

  /// [ChassisLocalizations.openSourceLicences].
  String get openSourceLicences => _chassis.openSourceLicences;

  /// [ChassisLocalizations.legalese].
  String get legalese => _chassis.legalese;

  /// [ChassisLocalizations.consentAllow].
  String get consentAllow => _chassis.consentAllow;

  /// [ChassisLocalizations.consentDecline].
  String get consentDecline => _chassis.consentDecline;

  /// [ChassisLocalizations.homeTagline].
  String get homeTagline => _chassis.homeTagline;

  /// [ChassisLocalizations.welcomeTo].
  String welcomeTo(String appName) => _chassis.welcomeTo(appName);

  /// [ChassisLocalizations.consentTitle].
  String consentTitle(String appName) => _chassis.consentTitle(appName);

  /// [ChassisLocalizations.consentBody].
  String get consentBody => _chassis.consentBody;

  /// [ChassisLocalizations.consentPrivacy].
  String get consentPrivacy => _chassis.consentPrivacy;

  /// [ChassisLocalizations.navHome].
  String get navHome => _chassis.navHome;

  /// [ChassisLocalizations.navExplore].
  String get navExplore => _chassis.navExplore;

  /// [ChassisLocalizations.navSettings].
  String get navSettings => _chassis.navSettings;

  /// [ChassisLocalizations.deleteAccountPassword].
  String get deleteAccountPassword => _chassis.deleteAccountPassword;

  /// [ChassisLocalizations.deleteAccountReauthHint].
  String get deleteAccountReauthHint => _chassis.deleteAccountReauthHint;

  /// [ChassisLocalizations.deleteAccountConfirmBodyApple].
  String get deleteAccountConfirmBodyApple =>
      _chassis.deleteAccountConfirmBodyApple;

  /// [ChassisLocalizations.deleteAccountReauthHintApple].
  String get deleteAccountReauthHintApple =>
      _chassis.deleteAccountReauthHintApple;

  /// [ChassisLocalizations.deleteAccountFailed].
  String get deleteAccountFailed => _chassis.deleteAccountFailed;

  /// [ChassisLocalizations.deleteAccountNotConfigured].
  String get deleteAccountNotConfigured => _chassis.deleteAccountNotConfigured;

  /// [ChassisLocalizations.deleteAccountSignInSurvives].
  String get deleteAccountSignInSurvives =>
      _chassis.deleteAccountSignInSurvives;

  /// [ChassisLocalizations.deleteAccountPending].
  String get deleteAccountPending => _chassis.deleteAccountPending;

  /// [ChassisLocalizations.deleteAccountUnknown].
  String get deleteAccountUnknown => _chassis.deleteAccountUnknown;

  /// [ChassisLocalizations.errorTitle].
  String get errorTitle => _chassis.errorTitle;

  /// [ChassisLocalizations.errorMessage].
  String get errorMessage => _chassis.errorMessage;

  /// [ChassisLocalizations.notFoundTitle].
  String get notFoundTitle => _chassis.notFoundTitle;

  /// [ChassisLocalizations.notFoundMessage].
  String get notFoundMessage => _chassis.notFoundMessage;

  /// [ChassisLocalizations.goHome].
  String get goHome => _chassis.goHome;

  /// [ChassisLocalizations.offlineMessage].
  String get offlineMessage => _chassis.offlineMessage;

  /// [ChassisLocalizations.retry].
  String get retry => _chassis.retry;

  /// [ChassisLocalizations.signInTitle].
  String get signInTitle => _chassis.signInTitle;

  /// [ChassisLocalizations.signUpTitle].
  String get signUpTitle => _chassis.signUpTitle;

  /// [ChassisLocalizations.email].
  String get email => _chassis.email;

  /// [ChassisLocalizations.password].
  String get password => _chassis.password;

  /// [ChassisLocalizations.signIn].
  String get signIn => _chassis.signIn;

  /// [ChassisLocalizations.signUp].
  String get signUp => _chassis.signUp;

  /// [ChassisLocalizations.forgotPassword].
  String get forgotPassword => _chassis.forgotPassword;

  /// [ChassisLocalizations.resetSent].
  String get resetSent => _chassis.resetSent;

  /// [ChassisLocalizations.authEnterBoth].
  String get authEnterBoth => _chassis.authEnterBoth;

  /// [ChassisLocalizations.authInvalidEmail].
  String get authInvalidEmail => _chassis.authInvalidEmail;

  /// [ChassisLocalizations.emailRequired].
  String get emailRequired => _chassis.emailRequired;

  /// [ChassisLocalizations.passwordTooShort].
  String get passwordTooShort => _chassis.passwordTooShort;

  /// [ChassisLocalizations.passwordBreached].
  String get passwordBreached => _chassis.passwordBreached;

  /// [ChassisLocalizations.passwordTooWeak].
  String get passwordTooWeak => _chassis.passwordTooWeak;

  /// [ChassisLocalizations.authIncorrect].
  String get authIncorrect => _chassis.authIncorrect;

  /// [ChassisLocalizations.authAlreadyRegistered].
  String get authAlreadyRegistered => _chassis.authAlreadyRegistered;

  /// [ChassisLocalizations.authConfirmEmail].
  String get authConfirmEmail => _chassis.authConfirmEmail;

  /// [ChassisLocalizations.authRateLimited].
  String get authRateLimited => _chassis.authRateLimited;

  /// [ChassisLocalizations.authCaptchaFailed].
  String get authCaptchaFailed => _chassis.authCaptchaFailed;

  /// [ChassisLocalizations.authCaptchaChecking].
  String get authCaptchaChecking => _chassis.authCaptchaChecking;

  /// [ChassisLocalizations.authCaptchaUnavailable].
  String get authCaptchaUnavailable => _chassis.authCaptchaUnavailable;

  /// [ChassisLocalizations.authNetworkError].
  String get authNetworkError => _chassis.authNetworkError;

  /// [ChassisLocalizations.authUnknownError].
  String get authUnknownError => _chassis.authUnknownError;

  /// [ChassisLocalizations.authLinkFailedSignIn].
  String get authLinkFailedSignIn => _chassis.authLinkFailedSignIn;

  /// [ChassisLocalizations.authProviderSignInCancelled].
  String get authProviderSignInCancelled =>
      _chassis.authProviderSignInCancelled;

  /// [ChassisLocalizations.signUpAgeRefused].
  String get signUpAgeRefused => _chassis.signUpAgeRefused;

  /// [ChassisLocalizations.needAccount].
  String get needAccount => _chassis.needAccount;

  /// [ChassisLocalizations.haveAccount].
  String get haveAccount => _chassis.haveAccount;

  /// [ChassisLocalizations.continueWithApple].
  String get continueWithApple => _chassis.continueWithApple;

  /// [ChassisLocalizations.continueWithGoogle].
  String get continueWithGoogle => _chassis.continueWithGoogle;

  /// [ChassisLocalizations.signOut].
  String get signOut => _chassis.signOut;

  /// [ChassisLocalizations.signOutFailed].
  String get signOutFailed => _chassis.signOutFailed;

  /// [ChassisLocalizations.signOutEverywhere].
  String get signOutEverywhere => _chassis.signOutEverywhere;

  /// [ChassisLocalizations.signOutEverywhereSubtitle].
  String get signOutEverywhereSubtitle => _chassis.signOutEverywhereSubtitle;

  /// [ChassisLocalizations.signOutEverywhereFailed].
  String get signOutEverywhereFailed => _chassis.signOutEverywhereFailed;

  /// [ChassisLocalizations.signOutEverywhereConfirmTitle].
  String get signOutEverywhereConfirmTitle =>
      _chassis.signOutEverywhereConfirmTitle;

  /// [ChassisLocalizations.signOutEverywhereConfirmBody].
  String get signOutEverywhereConfirmBody =>
      _chassis.signOutEverywhereConfirmBody;

  /// [ChassisLocalizations.signOutEverywhereConfirmAction].
  String get signOutEverywhereConfirmAction =>
      _chassis.signOutEverywhereConfirmAction;

  /// [ChassisLocalizations.notifications].
  String get notifications => _chassis.notifications;

  /// [ChassisLocalizations.remindersEnabled].
  String get remindersEnabled => _chassis.remindersEnabled;

  /// [ChassisLocalizations.remindersUnavailable].
  String get remindersUnavailable => _chassis.remindersUnavailable;

  /// [ChassisLocalizations.permissionPrimingTitle].
  String get permissionPrimingTitle => _chassis.permissionPrimingTitle;

  /// [ChassisLocalizations.permissionPrimingBody].
  String get permissionPrimingBody => _chassis.permissionPrimingBody;

  /// [ChassisLocalizations.reminderTitle].
  String get reminderTitle => _chassis.reminderTitle;

  /// [ChassisLocalizations.reminderBody].
  String get reminderBody => _chassis.reminderBody;

  /// [ChassisLocalizations.catchUpTitle].
  String get catchUpTitle => _chassis.catchUpTitle;

  /// [ChassisLocalizations.catchUpBody].
  String get catchUpBody => _chassis.catchUpBody;

  /// [ChassisLocalizations.catchUpDismiss].
  String get catchUpDismiss => _chassis.catchUpDismiss;

  /// [ChassisLocalizations.notNow].
  String get notNow => _chassis.notNow;

  /// [ChassisLocalizations.continueLabel].
  String get continueLabel => _chassis.continueLabel;

  /// [ChassisLocalizations.legal].
  String get legal => _chassis.legal;

  /// [ChassisLocalizations.privacyPolicy].
  String get privacyPolicy => _chassis.privacyPolicy;

  /// [ChassisLocalizations.termsOfService].
  String get termsOfService => _chassis.termsOfService;

  /// [ChassisLocalizations.refundPolicy].
  String get refundPolicy => _chassis.refundPolicy;

  /// [ChassisLocalizations.language].
  String get language => _chassis.language;

  /// [ChassisLocalizations.languageSystem].
  String get languageSystem => _chassis.languageSystem;

  /// [ChassisLocalizations.profile].
  String get profile => _chassis.profile;

  /// [ChassisLocalizations.displayName].
  String get displayName => _chassis.displayName;

  /// [ChassisLocalizations.displayNameNotSet].
  String get displayNameNotSet => _chassis.displayNameNotSet;

  /// [ChassisLocalizations.editProfile].
  String get editProfile => _chassis.editProfile;

  /// [ChassisLocalizations.save].
  String get save => _chassis.save;

  /// [ChassisLocalizations.profileUpdateFailed].
  String get profileUpdateFailed => _chassis.profileUpdateFailed;

  /// [ChassisLocalizations.onboarding1Title].
  String get onboarding1Title => _chassis.onboarding1Title;

  /// [ChassisLocalizations.onboarding1Body].
  String get onboarding1Body => _chassis.onboarding1Body;

  /// [ChassisLocalizations.onboarding2Title].
  String get onboarding2Title => _chassis.onboarding2Title;

  /// [ChassisLocalizations.onboarding2Body].
  String get onboarding2Body => _chassis.onboarding2Body;

  /// [ChassisLocalizations.onboarding3Title].
  String get onboarding3Title => _chassis.onboarding3Title;

  /// [ChassisLocalizations.onboarding3Body].
  String get onboarding3Body => _chassis.onboarding3Body;

  /// [ChassisLocalizations.onboardingSkip].
  String get onboardingSkip => _chassis.onboardingSkip;

  /// [ChassisLocalizations.onboardingNext].
  String get onboardingNext => _chassis.onboardingNext;

  /// [ChassisLocalizations.onboardingStart].
  String get onboardingStart => _chassis.onboardingStart;

  /// [ChassisLocalizations.onboardingPageIndicator].
  String onboardingPageIndicator(int current, int total) =>
      _chassis.onboardingPageIndicator(current, total);

  /// [ChassisLocalizations.paywallTitle].
  String get paywallTitle => _chassis.paywallTitle;

  /// [ChassisLocalizations.updateRequiredTitle].
  String get updateRequiredTitle => _chassis.updateRequiredTitle;

  /// [ChassisLocalizations.updateRequiredMessage].
  String get updateRequiredMessage => _chassis.updateRequiredMessage;

  /// [ChassisLocalizations.updateRequiredAction].
  String get updateRequiredAction => _chassis.updateRequiredAction;

  /// [ChassisLocalizations.paywallHeadline].
  String get paywallHeadline => _chassis.paywallHeadline;

  /// [ChassisLocalizations.paywallUpgrade].
  String get paywallUpgrade => _chassis.paywallUpgrade;

  /// [ChassisLocalizations.paywallOpeningHosted].
  String get paywallOpeningHosted => _chassis.paywallOpeningHosted;

  /// [ChassisLocalizations.paywallOpeningStore].
  String get paywallOpeningStore => _chassis.paywallOpeningStore;

  /// [ChassisLocalizations.paywallPending].
  String get paywallPending => _chassis.paywallPending;

  /// [ChassisLocalizations.paywallCheckAgain].
  String get paywallCheckAgain => _chassis.paywallCheckAgain;

  /// [ChassisLocalizations.paywallUnlocked].
  String get paywallUnlocked => _chassis.paywallUnlocked;

  /// [ChassisLocalizations.paywallUnavailable].
  String get paywallUnavailable => _chassis.paywallUnavailable;

  /// [ChassisLocalizations.paywallRetryMessage].
  String get paywallRetryMessage => _chassis.paywallRetryMessage;

  /// [ChassisLocalizations.paywallTryAgain].
  String get paywallTryAgain => _chassis.paywallTryAgain;

  /// [ChassisLocalizations.paywallTerm].
  String paywallTerm(String term) => _chassis.paywallTerm(term);

  /// [ChassisLocalizations.paywallTermWithTrial].
  String paywallTermWithTrial(String term, int count, String unit) =>
      _chassis.paywallTermWithTrial(term, count, unit);

  /// [ChassisLocalizations.paywallProAdds].
  String get paywallProAdds => _chassis.paywallProAdds;

  /// [ChassisLocalizations.paywallAlwaysFree].
  String get paywallAlwaysFree => _chassis.paywallAlwaysFree;

  /// [ChassisLocalizations.paywallLoadingPlans].
  String get paywallLoadingPlans => _chassis.paywallLoadingPlans;

  /// [ChassisLocalizations.paywallTerms].
  String get paywallTerms => _chassis.paywallTerms;

  /// [ChassisLocalizations.paywallTermsTrial].
  String get paywallTermsTrial => _chassis.paywallTermsTrial;

  /// [ChassisLocalizations.managePlanLoading].
  String get managePlanLoading => _chassis.managePlanLoading;

  /// [ChassisLocalizations.managePlanLoadFailed].
  String get managePlanLoadFailed => _chassis.managePlanLoadFailed;

  /// [ChassisLocalizations.restorePurchases].
  String get restorePurchases => _chassis.restorePurchases;

  /// [ChassisLocalizations.keepPlan].
  String get keepPlan => _chassis.keepPlan;

  /// [ChassisLocalizations.cancelRecorded].
  String get cancelRecorded => _chassis.cancelRecorded;

  /// [ChassisLocalizations.privacy].
  String get privacy => _chassis.privacy;

  /// [ChassisLocalizations.privacyNotice].
  String get privacyNotice => _chassis.privacyNotice;

  /// [ChassisLocalizations.privacyNoticeSubtitle].
  String get privacyNoticeSubtitle => _chassis.privacyNoticeSubtitle;

  /// [ChassisLocalizations.usageStatistics].
  String get usageStatistics => _chassis.usageStatistics;

  /// [ChassisLocalizations.usageStatisticsOn].
  String get usageStatisticsOn => _chassis.usageStatisticsOn;

  /// [ChassisLocalizations.usageStatisticsOff].
  String get usageStatisticsOff => _chassis.usageStatisticsOff;

  /// [ChassisLocalizations.promoCardLabel].
  String get promoCardLabel => _chassis.promoCardLabel;

  /// [ChassisLocalizations.promoCardTitle].
  String get promoCardTitle => _chassis.promoCardTitle;

  /// [ChassisLocalizations.promoCardBody].
  String get promoCardBody => _chassis.promoCardBody;

  /// [ChassisLocalizations.promoCardPrice].
  String promoCardPrice(String price, String term) =>
      _chassis.promoCardPrice(price, term);

  /// [ChassisLocalizations.promoCardDismissA11y].
  String get promoCardDismissA11y => _chassis.promoCardDismissA11y;

  /// [ChassisLocalizations.legalAcceptTerms].
  String get legalAcceptTerms => _chassis.legalAcceptTerms;

  /// [ChassisLocalizations.legalMarketingOptIn].
  String get legalMarketingOptIn => _chassis.legalMarketingOptIn;

  /// [ChassisLocalizations.legalMustAcceptTerms].
  String get legalMustAcceptTerms => _chassis.legalMustAcceptTerms;

  /// [ChassisLocalizations.verifyEmailTitle].
  String get verifyEmailTitle => _chassis.verifyEmailTitle;

  /// [ChassisLocalizations.verifyEmailBody].
  String verifyEmailBody(String email) => _chassis.verifyEmailBody(email);

  /// [ChassisLocalizations.verifyEmailSpamHint].
  String get verifyEmailSpamHint => _chassis.verifyEmailSpamHint;

  /// [ChassisLocalizations.verifyEmailContinue].
  String get verifyEmailContinue => _chassis.verifyEmailContinue;

  /// [ChassisLocalizations.verifyEmailResend].
  String get verifyEmailResend => _chassis.verifyEmailResend;

  /// [ChassisLocalizations.verifyEmailResent].
  String get verifyEmailResent => _chassis.verifyEmailResent;

  /// [ChassisLocalizations.verifyEmailStillUnverified].
  String get verifyEmailStillUnverified => _chassis.verifyEmailStillUnverified;

  /// [ChassisLocalizations.checkInboxTitle].
  String get checkInboxTitle => _chassis.checkInboxTitle;

  /// [ChassisLocalizations.checkInboxBody].
  String checkInboxBody(String email) => _chassis.checkInboxBody(email);

  /// [ChassisLocalizations.checkInboxThenSignIn].
  String get checkInboxThenSignIn => _chassis.checkInboxThenSignIn;

  /// [ChassisLocalizations.checkInboxBackToSignIn].
  String get checkInboxBackToSignIn => _chassis.checkInboxBackToSignIn;

  /// [ChassisLocalizations.reacceptTermsTitle].
  String get reacceptTermsTitle => _chassis.reacceptTermsTitle;

  /// [ChassisLocalizations.reacceptTermsBody].
  String get reacceptTermsBody => _chassis.reacceptTermsBody;

  /// [ChassisLocalizations.reacceptTermsAccept].
  String get reacceptTermsAccept => _chassis.reacceptTermsAccept;

  /// [ChassisLocalizations.resetPasswordTitle].
  String get resetPasswordTitle => _chassis.resetPasswordTitle;

  /// [ChassisLocalizations.resetPasswordBody].
  String get resetPasswordBody => _chassis.resetPasswordBody;

  /// [ChassisLocalizations.resetPasswordNew].
  String get resetPasswordNew => _chassis.resetPasswordNew;

  /// [ChassisLocalizations.resetPasswordConfirm].
  String get resetPasswordConfirm => _chassis.resetPasswordConfirm;

  /// [ChassisLocalizations.resetPasswordSubmit].
  String get resetPasswordSubmit => _chassis.resetPasswordSubmit;

  /// [ChassisLocalizations.resetPasswordEnterOne].
  String get resetPasswordEnterOne => _chassis.resetPasswordEnterOne;

  /// [ChassisLocalizations.resetPasswordMismatch].
  String get resetPasswordMismatch => _chassis.resetPasswordMismatch;

  /// [ChassisLocalizations.resetPasswordDone].
  String get resetPasswordDone => _chassis.resetPasswordDone;

  /// [ChassisLocalizations.resetPasswordLinkDead].
  String get resetPasswordLinkDead => _chassis.resetPasswordLinkDead;

  /// [ChassisLocalizations.resetPasswordLinkExpiredHint].
  String get resetPasswordLinkExpiredHint =>
      _chassis.resetPasswordLinkExpiredHint;

  /// [ChassisLocalizations.resetPasswordSameDeviceHint].
  String get resetPasswordSameDeviceHint =>
      _chassis.resetPasswordSameDeviceHint;

  /// [ChassisLocalizations.promotionalOffers].
  String get promotionalOffers => _chassis.promotionalOffers;

  /// [ChassisLocalizations.promoObjectionExplain].
  String get promoObjectionExplain => _chassis.promoObjectionExplain;

  /// [ChassisLocalizations.promoStopOffers].
  String get promoStopOffers => _chassis.promoStopOffers;

  /// [ChassisLocalizations.promoResumeOffers].
  String get promoResumeOffers => _chassis.promoResumeOffers;

  /// [ChassisLocalizations.promoOffersOff].
  String get promoOffersOff => _chassis.promoOffersOff;

  /// [ChassisLocalizations.promoLabel].
  String get promoLabel => _chassis.promoLabel;

  /// [ChassisLocalizations.reportContent].
  String get reportContent => _chassis.reportContent;

  /// [ChassisLocalizations.reportContentBody].
  String get reportContentBody => _chassis.reportContentBody;

  /// [ChassisLocalizations.reportReasonLabel].
  String get reportReasonLabel => _chassis.reportReasonLabel;

  /// [ChassisLocalizations.reportReasonOffensive].
  String get reportReasonOffensive => _chassis.reportReasonOffensive;

  /// [ChassisLocalizations.reportReasonSexual].
  String get reportReasonSexual => _chassis.reportReasonSexual;

  /// [ChassisLocalizations.reportReasonViolence].
  String get reportReasonViolence => _chassis.reportReasonViolence;

  /// [ChassisLocalizations.reportReasonHate].
  String get reportReasonHate => _chassis.reportReasonHate;

  /// [ChassisLocalizations.reportReasonSelfHarm].
  String get reportReasonSelfHarm => _chassis.reportReasonSelfHarm;

  /// [ChassisLocalizations.reportReasonDangerous].
  String get reportReasonDangerous => _chassis.reportReasonDangerous;

  /// [ChassisLocalizations.reportReasonMisinformation].
  String get reportReasonMisinformation => _chassis.reportReasonMisinformation;

  /// [ChassisLocalizations.reportReasonOther].
  String get reportReasonOther => _chassis.reportReasonOther;

  /// [ChassisLocalizations.reportExcerptLabel].
  String get reportExcerptLabel => _chassis.reportExcerptLabel;

  /// [ChassisLocalizations.reportNoteLabel].
  String get reportNoteLabel => _chassis.reportNoteLabel;

  /// [ChassisLocalizations.reportSubmit].
  String get reportSubmit => _chassis.reportSubmit;

  /// [ChassisLocalizations.reportSent].
  String get reportSent => _chassis.reportSent;

  /// [ChassisLocalizations.reportFailed].
  String get reportFailed => _chassis.reportFailed;

  /// [ChassisLocalizations.reportDone].
  String get reportDone => _chassis.reportDone;

  /// [ChassisLocalizations.authShow].
  String get authShow => _chassis.authShow;

  /// [ChassisLocalizations.authHide].
  String get authHide => _chassis.authHide;

  /// [ChassisLocalizations.authShowPassword].
  String get authShowPassword => _chassis.authShowPassword;

  /// [ChassisLocalizations.authHidePassword].
  String get authHidePassword => _chassis.authHidePassword;

  /// [ChassisLocalizations.authOr].
  String get authOr => _chassis.authOr;

  /// [ChassisLocalizations.authPasswordRuleLength].
  String authPasswordRuleLength(int count) =>
      _chassis.authPasswordRuleLength(count);

  /// [ChassisLocalizations.authPasswordRuleBreach].
  String get authPasswordRuleBreach => _chassis.authPasswordRuleBreach;

  /// [ChassisLocalizations.authAttestationRequired].
  String get authAttestationRequired => _chassis.authAttestationRequired;

  /// [ChassisLocalizations.authAttestationRefused].
  String get authAttestationRefused => _chassis.authAttestationRefused;

  /// [ChassisLocalizations.authNativeUnavailable].
  String get authNativeUnavailable => _chassis.authNativeUnavailable;

  /// [ChassisLocalizations.authRetryAfterMinutes].
  String authRetryAfterMinutes(int count) =>
      _chassis.authRetryAfterMinutes(count);

  /// [ChassisLocalizations.authRetryAfterHours].
  String authRetryAfterHours(int count) => _chassis.authRetryAfterHours(count);

  /// [ChassisLocalizations.reacceptTermsNotRecorded].
  String get reacceptTermsNotRecorded => _chassis.reacceptTermsNotRecorded;

  /// [ChassisLocalizations.authResendConfirmation].
  String get authResendConfirmation => _chassis.authResendConfirmation;

  /// [ChassisLocalizations.onboardingPrevious].
  String get onboardingPrevious => _chassis.onboardingPrevious;

  /// [ChassisLocalizations.onboardingHaveAccount].
  String get onboardingHaveAccount => _chassis.onboardingHaveAccount;

  /// [ChassisLocalizations.verifyEmailResendIn].
  String verifyEmailResendIn(String time) => _chassis.verifyEmailResendIn(time);

  /// [ChassisLocalizations.verifyEmailUseDifferent].
  String get verifyEmailUseDifferent => _chassis.verifyEmailUseDifferent;

  /// [ChassisLocalizations.tamperedBuildTitle].
  String get tamperedBuildTitle => _chassis.tamperedBuildTitle;

  /// [ChassisLocalizations.tamperedBuildMessage].
  String get tamperedBuildMessage => _chassis.tamperedBuildMessage;

  /// [ChassisLocalizations.tamperedBuildExit].
  String get tamperedBuildExit => _chassis.tamperedBuildExit;

  /// [ChassisLocalizations.rootedDeviceNotice].
  String get rootedDeviceNotice => _chassis.rootedDeviceNotice;

  /// [ChassisLocalizations.rootedDeviceNoticeDismiss].
  String get rootedDeviceNoticeDismiss => _chassis.rootedDeviceNoticeDismiss;

  /// [ChassisLocalizations.reauthTitle].
  String get reauthTitle => _chassis.reauthTitle;

  /// [ChassisLocalizations.reauthMessage].
  String get reauthMessage => _chassis.reauthMessage;

  /// [ChassisLocalizations.devicesTitle].
  String get devicesTitle => _chassis.devicesTitle;

  /// [ChassisLocalizations.devicesThisDevice].
  String get devicesThisDevice => _chassis.devicesThisDevice;

  /// [ChassisLocalizations.devicesSignOutDevice].
  String get devicesSignOutDevice => _chassis.devicesSignOutDevice;

  /// [ChassisLocalizations.devicesUnavailable].
  String get devicesUnavailable => _chassis.devicesUnavailable;

  /// [ChassisLocalizations.devicesSignOutFailed].
  String get devicesSignOutFailed => _chassis.devicesSignOutFailed;

  /// [ChassisLocalizations.devicesLastActive].
  String devicesLastActive(String date) => _chassis.devicesLastActive(date);

  /// [ChassisLocalizations.devicesShow].
  String get devicesShow => _chassis.devicesShow;

  /// [ChassisLocalizations.devicesRetry].
  String get devicesRetry => _chassis.devicesRetry;
}
