// GENERATED by `node tooling/i18n/locales.mjs --write` from
// packages/design_system/lib/src/l10n/chassis_en.arb. NEVER HAND-EDIT:
// tooling/ci/assert-locale-register.mjs fails CI when the two disagree.
//
// The app reads every CHASSIS string through this bridge rather than
// re-declaring it in its own ARB (lane i18n-pipeline, ARB hygiene): one key,
// one translation, in one place. A key the app ARB still declares wins.
import 'package:flutter/widgets.dart' show Locale;
import 'package:nikatru_design_system/nikatru_design_system.dart'
    show ChassisLocalizations, lookupChassisLocalizations;

import 'app_localizations.dart';

// Re-exported so a call site imports ONE file for both its own keys and the
// chassis keys — the bridge replaces the app_localizations.dart import.
export 'app_localizations.dart';

/// The chassis strings, read through the app's own localizations object.
extension ChassisBridge on AppLocalizations {
  /// How the bridge finds the chassis strings for a locale. Only a test that
  /// pumps a pseudo locale (whose chassis strings no real lookup can give)
  /// points it elsewhere, and restores it in tearDown.
  static ChassisLocalizations Function(Locale locale) lookup =
      lookupChassisLocalizations;

  ChassisLocalizations get _chassis {
    final List<String> parts = localeName.split('_');
    return lookup(
      Locale.fromSubtags(
        languageCode: parts.first,
        countryCode: parts.length > 1 ? parts.last : null,
      ),
    );
  }

  String get about => _chassis.about;

  String get appearance => _chassis.appearance;

  String get authAlreadyRegistered => _chassis.authAlreadyRegistered;

  String get authAttestationRefused => _chassis.authAttestationRefused;

  String get authAttestationRequired => _chassis.authAttestationRequired;

  String get authCaptchaChecking => _chassis.authCaptchaChecking;

  String get authCaptchaFailed => _chassis.authCaptchaFailed;

  String get authCaptchaUnavailable => _chassis.authCaptchaUnavailable;

  String get authCodeInvalid => _chassis.authCodeInvalid;

  String get authConfirmEmail => _chassis.authConfirmEmail;

  String get authEnterBoth => _chassis.authEnterBoth;

  String get authHide => _chassis.authHide;

  String get authHidePassword => _chassis.authHidePassword;

  String get authIncorrect => _chassis.authIncorrect;

  String get authInvalidEmail => _chassis.authInvalidEmail;

  String get authLastSignInMethod => _chassis.authLastSignInMethod;

  String get authLinkFailedSignIn => _chassis.authLinkFailedSignIn;

  String get authNativeUnavailable => _chassis.authNativeUnavailable;

  String get authNetworkError => _chassis.authNetworkError;

  String get authOr => _chassis.authOr;

  String get authPasswordRuleBreach => _chassis.authPasswordRuleBreach;

  String authPasswordRuleLength(int count) =>
      _chassis.authPasswordRuleLength(count);

  String get authProviderSignInCancelled =>
      _chassis.authProviderSignInCancelled;

  String get authRateLimited => _chassis.authRateLimited;

  String get authReauthRequired => _chassis.authReauthRequired;

  String get authResendConfirmation => _chassis.authResendConfirmation;

  String authRetryAfterHours(int count) => _chassis.authRetryAfterHours(count);

  String authRetryAfterMinutes(int count) =>
      _chassis.authRetryAfterMinutes(count);

  String get authSessionsNotRevoked => _chassis.authSessionsNotRevoked;

  String get authShow => _chassis.authShow;

  String get authShowPassword => _chassis.authShowPassword;

  String get authUnknownError => _chassis.authUnknownError;

  String get cancel => _chassis.cancel;

  String get cancelInStore => _chassis.cancelInStore;

  String get cancelRecorded => _chassis.cancelRecorded;

  String get catchUpBody => _chassis.catchUpBody;

  String get catchUpDismiss => _chassis.catchUpDismiss;

  String get catchUpTitle => _chassis.catchUpTitle;

  String get checkInboxBackToSignIn => _chassis.checkInboxBackToSignIn;

  String checkInboxBody(String email) => _chassis.checkInboxBody(email);

  String get checkInboxThenSignIn => _chassis.checkInboxThenSignIn;

  String get checkInboxTitle => _chassis.checkInboxTitle;

  String get connectedAccountsApple => _chassis.connectedAccountsApple;

  String get connectedAccountsBody => _chassis.connectedAccountsBody;

  String get connectedAccountsConnect => _chassis.connectedAccountsConnect;

  String get connectedAccountsConnected => _chassis.connectedAccountsConnected;

  String get connectedAccountsGoogle => _chassis.connectedAccountsGoogle;

  String get connectedAccountsNotConnected =>
      _chassis.connectedAccountsNotConnected;

  String get connectedAccountsOnlyMethod =>
      _chassis.connectedAccountsOnlyMethod;

  String get connectedAccountsPassword => _chassis.connectedAccountsPassword;

  String get connectedAccountsRemove => _chassis.connectedAccountsRemove;

  String get connectedAccountsTitle => _chassis.connectedAccountsTitle;

  String get connectedAccountsVerifyFirst =>
      _chassis.connectedAccountsVerifyFirst;

  String get consentAllow => _chassis.consentAllow;

  String get consentBody => _chassis.consentBody;

  String get consentDecline => _chassis.consentDecline;

  String get consentPrivacy => _chassis.consentPrivacy;

  String consentTitle(String appName) => _chassis.consentTitle(appName);

  String get contactSupport => _chassis.contactSupport;

  String get continueLabel => _chassis.continueLabel;

  String get continueWithApple => _chassis.continueWithApple;

  String get continueWithGoogle => _chassis.continueWithGoogle;

  String get delete => _chassis.delete;

  String get deleteAccount => _chassis.deleteAccount;

  String get deleteAccountConfirmBody => _chassis.deleteAccountConfirmBody;

  String get deleteAccountConfirmBodyApple =>
      _chassis.deleteAccountConfirmBodyApple;

  String get deleteAccountConfirmTitle => _chassis.deleteAccountConfirmTitle;

  String get deleteAccountFailed => _chassis.deleteAccountFailed;

  String get deleteAccountNotConfigured => _chassis.deleteAccountNotConfigured;

  String get deleteAccountPassword => _chassis.deleteAccountPassword;

  String get deleteAccountPending => _chassis.deleteAccountPending;

  String get deleteAccountReauthHint => _chassis.deleteAccountReauthHint;

  String get deleteAccountReauthHintApple =>
      _chassis.deleteAccountReauthHintApple;

  String get deleteAccountSignInSurvives =>
      _chassis.deleteAccountSignInSurvives;

  String get deleteAccountSubtitle => _chassis.deleteAccountSubtitle;

  String get deleteAccountUnknown => _chassis.deleteAccountUnknown;

  String devicesLastActive(String date) => _chassis.devicesLastActive(date);

  String get devicesRetry => _chassis.devicesRetry;

  String get devicesShow => _chassis.devicesShow;

  String get devicesSignOutDevice => _chassis.devicesSignOutDevice;

  String get devicesSignOutFailed => _chassis.devicesSignOutFailed;

  String get devicesThisDevice => _chassis.devicesThisDevice;

  String get devicesTitle => _chassis.devicesTitle;

  String get devicesUnavailable => _chassis.devicesUnavailable;

  String get displayName => _chassis.displayName;

  String get displayNameNotSet => _chassis.displayNameNotSet;

  String get editProfile => _chassis.editProfile;

  String get email => _chassis.email;

  String get emailCodeLabel => _chassis.emailCodeLabel;

  String get emailCodeResend => _chassis.emailCodeResend;

  String emailCodeResendIn(int seconds) => _chassis.emailCodeResendIn(seconds);

  String get emailCodeSentAgain => _chassis.emailCodeSentAgain;

  String emailCodeSentTo(String email) => _chassis.emailCodeSentTo(email);

  String get emailCodeShape => _chassis.emailCodeShape;

  String get emailCodeSignIn => _chassis.emailCodeSignIn;

  String get emailCodeUsePassword => _chassis.emailCodeUsePassword;

  String get emailRequired => _chassis.emailRequired;

  String get errorMessage => _chassis.errorMessage;

  String get errorTitle => _chassis.errorTitle;

  String get forgotPassword => _chassis.forgotPassword;

  String get goHome => _chassis.goHome;

  String get haveAccount => _chassis.haveAccount;

  String get homeTagline => _chassis.homeTagline;

  String get keepPlan => _chassis.keepPlan;

  String get language => _chassis.language;

  String get languageSystem => _chassis.languageSystem;

  String get legal => _chassis.legal;

  String get legalAcceptTerms => _chassis.legalAcceptTerms;

  String get legalMarketingOptIn => _chassis.legalMarketingOptIn;

  String get legalMustAcceptTerms => _chassis.legalMustAcceptTerms;

  String get legalese => _chassis.legalese;

  String get manageInAppStore => _chassis.manageInAppStore;

  String get manageInGooglePlay => _chassis.manageInGooglePlay;

  String get managePlanLoadFailed => _chassis.managePlanLoadFailed;

  String get managePlanLoading => _chassis.managePlanLoading;

  String get navExplore => _chassis.navExplore;

  String get navHome => _chassis.navHome;

  String get navSettings => _chassis.navSettings;

  String get needAccount => _chassis.needAccount;

  String get notFoundMessage => _chassis.notFoundMessage;

  String get notFoundTitle => _chassis.notFoundTitle;

  String get notNow => _chassis.notNow;

  String get notifications => _chassis.notifications;

  String get offlineMessage => _chassis.offlineMessage;

  String get onboarding1Body => _chassis.onboarding1Body;

  String get onboarding1Title => _chassis.onboarding1Title;

  String get onboarding2Body => _chassis.onboarding2Body;

  String get onboarding2Title => _chassis.onboarding2Title;

  String get onboarding3Body => _chassis.onboarding3Body;

  String get onboarding3Title => _chassis.onboarding3Title;

  String get onboardingHaveAccount => _chassis.onboardingHaveAccount;

  String get onboardingNext => _chassis.onboardingNext;

  String onboardingPageIndicator(int current, int total) =>
      _chassis.onboardingPageIndicator(current, total);

  String get onboardingPrevious => _chassis.onboardingPrevious;

  String get onboardingSkip => _chassis.onboardingSkip;

  String get onboardingStart => _chassis.onboardingStart;

  String get openSourceLicences => _chassis.openSourceLicences;

  String get password => _chassis.password;

  String get passwordBreached => _chassis.passwordBreached;

  String get passwordTooShort => _chassis.passwordTooShort;

  String get passwordTooWeak => _chassis.passwordTooWeak;

  String get paywallAlwaysFree => _chassis.paywallAlwaysFree;

  String get paywallAppleEula => _chassis.paywallAppleEula;

  String get paywallCancelHere => _chassis.paywallCancelHere;

  String get paywallCancelInAppStore => _chassis.paywallCancelInAppStore;

  String get paywallCancelInGooglePlay => _chassis.paywallCancelInGooglePlay;

  String get paywallCheckAgain => _chassis.paywallCheckAgain;

  String get paywallHeadline => _chassis.paywallHeadline;

  String get paywallLoadingPlans => _chassis.paywallLoadingPlans;

  String get paywallOpeningHosted => _chassis.paywallOpeningHosted;

  String get paywallOpeningStore => _chassis.paywallOpeningStore;

  String get paywallPending => _chassis.paywallPending;

  String get paywallProAdds => _chassis.paywallProAdds;

  String get paywallRetryMessage => _chassis.paywallRetryMessage;

  String get paywallTermMonthly => _chassis.paywallTermMonthly;

  String paywallTermMonthlyWithTrial(int count, String unit) =>
      _chassis.paywallTermMonthlyWithTrial(count, unit);

  String get paywallTermYearly => _chassis.paywallTermYearly;

  String paywallTermYearlyWithTrial(int count, String unit) =>
      _chassis.paywallTermYearlyWithTrial(count, unit);

  String get paywallTerms => _chassis.paywallTerms;

  String get paywallTermsTrial => _chassis.paywallTermsTrial;

  String get paywallTitle => _chassis.paywallTitle;

  String get paywallTryAgain => _chassis.paywallTryAgain;

  String get paywallUnavailable => _chassis.paywallUnavailable;

  String get paywallUnlocked => _chassis.paywallUnlocked;

  String get paywallUpgrade => _chassis.paywallUpgrade;

  String get permissionPrimingBody => _chassis.permissionPrimingBody;

  String get permissionPrimingTitle => _chassis.permissionPrimingTitle;

  String get planBoughtInAppStore => _chassis.planBoughtInAppStore;

  String get planBoughtInGooglePlay => _chassis.planBoughtInGooglePlay;

  String get planBoughtOnWeb => _chassis.planBoughtOnWeb;

  String planPeriodEnds(DateTime date) => _chassis.planPeriodEnds(date);

  String get privacy => _chassis.privacy;

  String get privacyNotice => _chassis.privacyNotice;

  String get privacyNoticeSubtitle => _chassis.privacyNoticeSubtitle;

  String get privacyPolicy => _chassis.privacyPolicy;

  String get profile => _chassis.profile;

  String get profileUpdateFailed => _chassis.profileUpdateFailed;

  String get promoCardBody => _chassis.promoCardBody;

  String get promoCardDismissA11y => _chassis.promoCardDismissA11y;

  String get promoCardLabel => _chassis.promoCardLabel;

  String promoCardPrice(String price, String term) =>
      _chassis.promoCardPrice(price, term);

  String get promoCardTitle => _chassis.promoCardTitle;

  String get promoLabel => _chassis.promoLabel;

  String get promoObjectionExplain => _chassis.promoObjectionExplain;

  String get promoOffersOff => _chassis.promoOffersOff;

  String get promoResumeOffers => _chassis.promoResumeOffers;

  String get promoStopOffers => _chassis.promoStopOffers;

  String get promotionalOffers => _chassis.promotionalOffers;

  String get reacceptTermsAccept => _chassis.reacceptTermsAccept;

  String get reacceptTermsBody => _chassis.reacceptTermsBody;

  String get reacceptTermsChangedIntro => _chassis.reacceptTermsChangedIntro;

  String get reacceptTermsNotRecorded => _chassis.reacceptTermsNotRecorded;

  String reacceptTermsNoteHeading(
    String document,
    String version,
    String date,
  ) => _chassis.reacceptTermsNoteHeading(document, version, date);

  String reacceptTermsNoteLine(String line) =>
      _chassis.reacceptTermsNoteLine(line);

  String reacceptTermsReadDocument(String document) =>
      _chassis.reacceptTermsReadDocument(document);

  String get reacceptTermsTitle => _chassis.reacceptTermsTitle;

  String get reauthMessage => _chassis.reauthMessage;

  String get reauthTitle => _chassis.reauthTitle;

  String get refundPolicy => _chassis.refundPolicy;

  String get reminderBody => _chassis.reminderBody;

  String get reminderTitle => _chassis.reminderTitle;

  String get remindersEnabled => _chassis.remindersEnabled;

  String get remindersUnavailable => _chassis.remindersUnavailable;

  String get reportContent => _chassis.reportContent;

  String get reportContentBody => _chassis.reportContentBody;

  String get reportDone => _chassis.reportDone;

  String get reportExcerptLabel => _chassis.reportExcerptLabel;

  String get reportFailed => _chassis.reportFailed;

  String get reportNoteLabel => _chassis.reportNoteLabel;

  String get reportReasonDangerous => _chassis.reportReasonDangerous;

  String get reportReasonHate => _chassis.reportReasonHate;

  String get reportReasonLabel => _chassis.reportReasonLabel;

  String get reportReasonMisinformation => _chassis.reportReasonMisinformation;

  String get reportReasonOffensive => _chassis.reportReasonOffensive;

  String get reportReasonOther => _chassis.reportReasonOther;

  String get reportReasonSelfHarm => _chassis.reportReasonSelfHarm;

  String get reportReasonSexual => _chassis.reportReasonSexual;

  String get reportReasonViolence => _chassis.reportReasonViolence;

  String get reportSent => _chassis.reportSent;

  String get reportSubmit => _chassis.reportSubmit;

  String get resetPasswordBody => _chassis.resetPasswordBody;

  String get resetPasswordConfirm => _chassis.resetPasswordConfirm;

  String get resetPasswordDone => _chassis.resetPasswordDone;

  String get resetPasswordEnterOne => _chassis.resetPasswordEnterOne;

  String get resetPasswordLinkDead => _chassis.resetPasswordLinkDead;

  String get resetPasswordLinkExpiredHint =>
      _chassis.resetPasswordLinkExpiredHint;

  String get resetPasswordMismatch => _chassis.resetPasswordMismatch;

  String get resetPasswordNew => _chassis.resetPasswordNew;

  String get resetPasswordSameDeviceHint =>
      _chassis.resetPasswordSameDeviceHint;

  String get resetPasswordSubmit => _chassis.resetPasswordSubmit;

  String get resetPasswordTitle => _chassis.resetPasswordTitle;

  String get resetSent => _chassis.resetSent;

  String get restorePurchases => _chassis.restorePurchases;

  String get retry => _chassis.retry;

  String get rootedDeviceNotice => _chassis.rootedDeviceNotice;

  String get rootedDeviceNoticeDismiss => _chassis.rootedDeviceNoticeDismiss;

  String get save => _chassis.save;

  String get settingsTitle => _chassis.settingsTitle;

  String get signIn => _chassis.signIn;

  String get signInTitle => _chassis.signInTitle;

  String get signOut => _chassis.signOut;

  String get signOutEverywhere => _chassis.signOutEverywhere;

  String get signOutEverywhereConfirmAction =>
      _chassis.signOutEverywhereConfirmAction;

  String get signOutEverywhereConfirmBody =>
      _chassis.signOutEverywhereConfirmBody;

  String get signOutEverywhereConfirmTitle =>
      _chassis.signOutEverywhereConfirmTitle;

  String get signOutEverywhereFailed => _chassis.signOutEverywhereFailed;

  String get signOutEverywhereSubtitle => _chassis.signOutEverywhereSubtitle;

  String get signOutFailed => _chassis.signOutFailed;

  String get signUp => _chassis.signUp;

  String get signUpAgeRefused => _chassis.signUpAgeRefused;

  String get signUpTitle => _chassis.signUpTitle;

  String get tamperedBuildExit => _chassis.tamperedBuildExit;

  String get tamperedBuildMessage => _chassis.tamperedBuildMessage;

  String get tamperedBuildTitle => _chassis.tamperedBuildTitle;

  String get termsOfService => _chassis.termsOfService;

  String get themeDark => _chassis.themeDark;

  String get themeLight => _chassis.themeLight;

  String get themeSystem => _chassis.themeSystem;

  String get updateRequiredAction => _chassis.updateRequiredAction;

  String get updateRequiredMessage => _chassis.updateRequiredMessage;

  String get updateRequiredTitle => _chassis.updateRequiredTitle;

  String get usageStatistics => _chassis.usageStatistics;

  String get usageStatisticsOff => _chassis.usageStatisticsOff;

  String get usageStatisticsOn => _chassis.usageStatisticsOn;

  String verifyEmailBody(String email) => _chassis.verifyEmailBody(email);

  String get verifyEmailContinue => _chassis.verifyEmailContinue;

  String get verifyEmailResend => _chassis.verifyEmailResend;

  String verifyEmailResendIn(String time) => _chassis.verifyEmailResendIn(time);

  String get verifyEmailResent => _chassis.verifyEmailResent;

  String get verifyEmailSpamHint => _chassis.verifyEmailSpamHint;

  String get verifyEmailStillUnverified => _chassis.verifyEmailStillUnverified;

  String get verifyEmailTitle => _chassis.verifyEmailTitle;

  String get verifyEmailUseDifferent => _chassis.verifyEmailUseDifferent;

  String welcomeTo(String appName) => _chassis.welcomeTo(appName);
}
