// GENERATED by tooling/app-yaml/render.mjs from app.yaml (the per-app pin
// tooling/channel-register.json runtimeSignerCheck names). Do not edit; change
// app.yaml and re-render.

/// This app's own signer pins by `RELEASE_CHANNEL`, uppercase SHA-256. Play
/// holds one app signing key PER APP (ADR 030), so this is the app's, not the
/// channel's. nikatru_core's `signerPinsFor` adds it to the channel default.
const Map<String, List<String>> kAppSignerPins = <String, List<String>>{
  'android-play': <String>[
    '98FA5FDCA1491BEC84198D3DABE797B0432985741581BBFEA2555B176C833A3C',
  ],
};
