// GENERATED by tooling/app-yaml/render.mjs from app.yaml
// (stores.windows-store). Do not edit; change app.yaml and re-render.

import 'package:nikatru_notifications/nikatru_notifications.dart'
    show WindowsNotificationIdentity;

/// This app's Windows toast identity (ST-R4). Null = no Windows notifications.
const WindowsNotificationIdentity? kWindowsNotificationIdentity =
    WindowsNotificationIdentity(
      appName: _appName,
      appUserModelId: _appUserModelId,
      toastActivatorClsid: _toastActivatorClsid,
    );

const String _appName = 'Nikatru Subscription Tracker';
const String _appUserModelId =
    '60210NIKATRU.NikatruSubscriptionTracker_ab30hnb4490ma!subscriptiontracker';
const String _toastActivatorClsid = 'f23148ad-7606-46a7-9767-e70e3f378f1d';
