#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// render-privacy.mjs — the privacy DECLARATION is the source; the notice
// surfaces are RENDERINGS.
//
//   apps/<id>/privacy.yaml ─────(this script)──▶ sites/nikatru/<id>/privacy.html
//                                                (the per-app notice, incl. the
//                                                 itemised DPDP notice block)
//
//   extensions/<Cat>/<Tool>/publish/privacy.yaml ─▶ the Chrome Web Store
//                                                   privacy-practices block
//                                                   between the two markers in
//                                                   the sibling STORE-LISTING.md
//
// ── WHY A GENERATOR AT ALL, WHEN THE DECLARATION ALREADY EXISTS ──────────────
// `apps/subscriptiontracker/privacy.yaml`'s own header says what it was missing: "Its
// renderings — the Play data-safety answers, the Apple privacy manifest, the
// published policy text — are NOT generated from it today, and nothing here
// pretends they are." Two of those three must never be generated ([ADR 037] —
// a sworn declaration regenerated by a template is a statement nobody made).
// The third — the NOTICE a reader is shown — is exactly the thing that should
// be, because the alternative is a human retyping eleven categories, four
// processors and three retention classes into HTML and into a store console and
// nothing anywhere being able to tell the two apart from agreement.
//
// ── WHAT IT DELIBERATELY DOES NOT WRITE ──────────────────────────────────────
// ⛔ The four SWORN declarations under `apps/<id>/store/` — data-safety.json,
//    content-rating.json, ads-declaration.json, privacy-manifest.json. This
//    script never opens them. `assert-app-yaml.mjs` limb 4 READS two of them, in
//    the only direction that is safe: to check that the declaration and the
//    sworn answers still describe the same eleven rows.
// ⛔ `sites/nikatru/privacy.html`, the PORTFOLIO policy. It is pinned by
//    `kPrivacyPolicyVersion` in two Dart files, archived under
//    `sites/nikatru/legal/<version>/<locale>/`, and consent records cite its
//    version. A generator writing it would move a document people have already
//    agreed to. The per-app page below is a NOTICE ABOUT ONE APP that links to
//    it; it carries no `data-policy-version` of its own, on purpose, because
//    that attribute is the portfolio policy's identity and
//    `assert-policy-archive.mjs`'s VERSION_SOURCES is the closed list of files
//    allowed to declare one.
// ⛔ `app.yaml`'s `legal.privacyPolicyUrl`, from which the store
//    `privacy-policy-url.txt` files are rendered. A per-app privacy URL change
//    is a STORE LISTING change and is made deliberately and recorded, never as
//    a side effect of adding a page.
//
// ── THE PAGE IS NOT CONTRACT-SOURCED, AND THAT IS A MEASURED CHOICE ──────────
// 🔴 `assert-legal-text-parity.mjs` sweeps `contracts/legal/*.md` and FAILS any
// document there that is not published in at least TWO places
// (`MIN_COPIES_PER_DOCUMENT = 2`). The per-app notice is published in exactly
// ONE place. Putting its text under `contracts/legal/` would therefore fail that
// guard on the day it landed — and the repair would be either to weaken the
// floor or to invent a second copy. So the page is rendered from the
// declaration, its facts have one source, and `contracts/legal/` is untouched.
//
// ── `--check` IS THE ONLY THING BETWEEN A HAND EDIT AND A STORE CONSOLE ──────
// The HTML page carries a GENERATED / DO NOT EDIT header. The STORE-LISTING
// block cannot carry one of its own at the top of the file — the document is
// hand-written prose that a human maintains — so it is fenced by two markers
// and only the bytes BETWEEN them are rendered. Everything outside them is
// carried through unchanged, which is what makes an edit inside them detectable
// at all: the rendering of that file is "the file as it is, with the fenced
// region replaced".
//
// ⚠️ THE STYLE BLOCK'S VALUES ARE GENERATED TOKENS. `assert-palette-consistent.
// mjs` reads every page on the site and caught the imported FullShot policy's
// own greys as the only dissenting declaration on the whole site (that page's
// `:22-27` comment records it). The values below are the ones from
// `sites/_shared/assets/tokens.css` — edit `contracts/tokens`, never this file.
//
// Usage:  node tooling/app-yaml/render-privacy.mjs [root] [--check]
//         (default) writes every rendering whose bytes differ
//         --check   renders in memory and DIFFS; exit 1 NAMING each stale file
// Exit 0 = the notice surfaces match the declarations. 1 = they do not (or a
// declaration is invalid). 2 = COVERAGE LOST — see the refusals in `planPrivacy`.
// ─────────────────────────────────────────────────────────────────────────────
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseYaml, YamlError } from './yaml.mjs';
import { validate } from './schema-validate.mjs';
// 🔴 THE PAGE CARRIES THE SITE'S SHARED CHROME, IT DOES NOT OPT OUT OF IT.
// `chrome.mjs`'s `isChromePage` is DERIVED FROM THE TREE: a page added to
// sites/nikatru/ is in the chrome contract the moment it exists, and the only
// way out is a NAMED entry in CHROME_EXCLUDED with a written reason. The
// FullShot policy has one — it is a mirrored legal document whose footer is the
// publisher identification a store reviewer reads. This page is not mirrored and
// not a contract copy, so taking that exit would have been buying a green run
// with an exemption. It emits the four sentinel regions instead, which is also
// the only way it gets a skip link and a visible focus ring: C-WCAG-22-AA is a
// PUBLISHED claim, and a new page without them fails SC 2.4.1 and SC 2.4.7 on
// the day it ships.
import { REGIONS, openMarker, closeMarker, isCssRegion } from '../sites/chrome.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

export const PRIVACY_SCHEMA_PATH = join(HERE, 'schema', 'privacy.schema.json');
/** Where a processor id's company name is read from, relative to the root. */
export const PROVIDER_REGISTER = 'tooling/legal/provider-register.json';
export const APPS_DIR = 'apps';
export const EXTENSIONS_DIR = 'extensions';
/** The tool template. It ships NO declaration, on purpose — see `UNANSWERED`. */
export const TEMPLATE_LISTING = 'extensions/templates/tool/publish/STORE-LISTING.md';

/** The site the per-app notice is served from, and the URL it calls itself. */
const SITE_ROOT = 'sites/nikatru';
const ORIGIN = 'https://nikatru.com';

/** The fence. Two comments a Markdown reader ignores and a diff cannot miss. */
export const MARK_START = '<!-- GENERATED:privacy-practices — rendered from publish/privacy.yaml by tooling/app-yaml/render-privacy.mjs. DO NOT EDIT BETWEEN THESE MARKERS. -->';
export const MARK_END = '<!-- /GENERATED:privacy-practices -->';

const listDirs = (abs) => readdirSync(abs, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name);

/**
 * Read a file, or `null` when it is not there.
 *
 * 🔴 ONE SYSCALL, NOT `existsSync` THEN `readFileSync`. CodeQL's
 * `js/file-system-race` raised the check-then-read pair here at high severity on
 * 2026-09-06, and it is right rather than pedantic: between the two calls the
 * file can be replaced, so the branch a renderer takes is decided by a fact that
 * was true a moment ago. The generators in this tree run beside each other —
 * `generate-discovery.mjs` splices the same site pages this script writes — so
 * the window is a real one, not a hypothetical. Reading and catching ENOENT
 * makes "is it there" and "what does it say" the same observation. Anything
 * OTHER than ENOENT is re-thrown: a permission error silently read as "absent"
 * would make a missing declaration and an unreadable one the same case, and they
 * need opposite repairs.
 */
const readIf = (abs) => {
  try {
    return readFileSync(abs, 'utf8');
  } catch (e) {
    if (e && (e.code === 'ENOENT' || e.code === 'EISDIR')) return null;
    throw e;
  }
};

const isDir = (p) => {
  try {
    return statSync(p).isDirectory();
  } catch (e) {
    if (e && e.code === 'ENOENT') return false;
    throw e;
  }
};

/* ------------------------------------------------------------------ */
/* Escaping                                                            */

/** HTML text. Every string below comes from a declaration a human wrote, so it
 *  is escaped rather than trusted — the same reason
 *  `render-fullshot-privacy.mjs` REFUSES inline HTML it does not recognise. */
export const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/** A Markdown table cell. A literal pipe would end the cell and silently move
 *  every column after it one place left — a rendering that is wrong and looks
 *  deliberate. The numeric reference renders as the character it replaces. */
export const cell = (s) => String(s).replace(/\|/g, '&#124;').replace(/\r?\n/g, ' ').trim();

/* ------------------------------------------------------------------ */
/* The per-app notice page                                             */

/** Shared with the FullShot policy on purpose: one site, one palette. */
const STYLE_BODY = `  :root { --ink:#0B1220; --muted:#586275; --line:#E2E8F0; --accent:#2563EB; }
  * { box-sizing: border-box; }
  body { max-width: 760px; margin: 0 auto; padding: 40px 20px 80px;
         font: 16px/1.65 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         color: var(--ink); background: #fff; }
  h1 { font-size: 30px; margin: 0 0 4px; }
  h2 { font-size: 20px; margin: 34px 0 8px; padding-top: 14px; border-top: 1px solid var(--line); }
  h3 { font-size: 16px; margin: 20px 0 4px; }
  p, li, td, th { color: var(--ink); }
  .meta { color: var(--muted); font-size: 14px; margin: 0 0 8px; }
  .lead { font-size: 17px; color: #333; }
  ul { padding-left: 22px; }
  li { margin: 5px 0; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 15px; }
  th, td { border: 1px solid var(--line); padding: 8px 10px; text-align: left; vertical-align: top; }
  th { background: #f7f9fc; font-weight: 600; }
  .callout { background: #f0f6ff; border: 1px solid #cfe0fb; border-radius: 8px;
             padding: 14px 16px; margin: 16px 0; }
  .tag { display:inline-block; background:#e8f0fe; color:var(--accent);
         border-radius: 999px; padding: 2px 10px; font-size: 13px; font-weight: 600; }
  footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--line);
           color: var(--muted); font-size: 14px; }
  a { color: var(--accent); }`;

/** What each locked retention class is, in the words [ADR 045] locked it with.
 *  A number on a notice page that a reader cannot interpret is not a notice. */
const RETENTION_MEANING = {
  400: 'raw, event-level data — the floor is one year, set by the DPDP Rules 2025, and the ceiling is the 425-day industry maximum',
  730: 'the money rail — our copy has to outlive the payment provider’s own 90-day replay window and the outer card-dispute window',
  1100: 'the derived rollup, which holds strictly less about a person than the raw table it is computed from',
};

const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;

/** One chrome region, sentinels and body, exactly as chrome.mjs emits it. The
 *  body is written here rather than left empty so the page is correct BEFORE
 *  `generate-discovery.mjs` next runs; that script re-splices the same bytes, so
 *  the two generators agree instead of fighting over the file. */
const region = (name) => {
  const css = isCssRegion(name);
  return [openMarker(name, css), REGIONS.get(name)(), closeMarker(name, css)].join('\n');
};

/**
 * The per-app notice. Every fact on it is a field of the declaration; the only
 * sentences that are not are the statutory chrome, which is held here because
 * it is the same for every app and belongs in one place rather than in each
 * declaration.
 */
export function renderAppPage(doc, { appName, appId, providerNames, portfolioPolicyPath = '/privacy' }) {
  if (!(providerNames instanceof Map)) {
    throw new TypeError(`renderAppPage needs providerNames, the ${PROVIDER_REGISTER} id → name map`);
  }
  const rows = doc.collects ?? [];
  const classes = [...new Set(rows.map((r) => r.retentionClass))].sort((a, b) => a - b);
  const purposes = [...new Set(rows.flatMap((r) => r.purposes ?? []))].sort();
  const shared = rows.filter((r) => r.shared === true);
  const url = `${ORIGIN}/${appId}/privacy`;

  const out = [];
  const p = (s) => out.push(s);

  p('<!DOCTYPE html>');
  p('<html lang="en">');
  p('<head>');
  p('<meta charset="utf-8">');
  p('<meta name="viewport" content="width=device-width, initial-scale=1">');
  p(`<title>${esc(appName)} — What this app collects</title>`);
  p(`<link rel="canonical" href="${url}">`);
  p(`<meta name="description" content="${esc(`What ${appName} collects, why, for how long, and who else touches it — itemised from the app's own privacy declaration.`)}">`);
  p('<!-- GENERATED from apps/' + appId + '/privacy.yaml by');
  p('     tooling/app-yaml/render-privacy.mjs. DO NOT EDIT THIS FILE.');
  p('     Edit the declaration and re-run the renderer.');
  p('');
  p('     This page is the PER-APP notice. It is not the portfolio privacy');
  p('     policy: that is /privacy, it carries the data-policy-version consent');
  p('     records cite, and it is archived under sites/nikatru/legal/. This page');
  p('     carries no version attribute of its own for exactly that reason. -->');
  p('<style>');
  p('  /* Nikatru brand palette, the generated values from');
  p('     sites/_shared/assets/tokens.css — edit contracts/tokens, never this');
  p('     line. assert-palette-consistent.mjs compares every page on this site');
  p('     and the FullShot policy’s own :22-27 comment records what happens');
  p('     when one of them ships its own greys instead. */');
  p(STYLE_BODY);
  // The two regions added 2026-09-09. `scale-css` must sit inside a `:root`
  // block of its own — it emits bare custom-property declarations, which are
  // only legal in a rule — and `generate-discovery.mjs` writes the identical
  // wrapper, so the two generators produce the same bytes rather than fighting
  // over this file on alternate runs. The region list is iterated from
  // chrome.mjs's REGIONS; what is written here is only WHERE each one lands.
  p('  :root{');
  p(region('scale-css'));
  p('  }');
  p(region('marks-css'));
  p(region('a11y-css'));
  p(region('footer-css'));
  p('</style>');
  p('</head>');
  p('<body>');
  p(region('skiplink'));
  p('');
  p('<main id="main">');
  p('');
  p(`<h1>${esc(appName)} — what this app collects</h1>`);
  p(`<p class="meta">Declaration last re-read against the code: ${esc(doc.asOf)} &nbsp;·&nbsp; Itemised from <code>apps/${esc(appId)}/privacy.yaml</code> &nbsp;·&nbsp; The policy you agree to is the <a href="${esc(portfolioPolicyPath)}">Nikatru Privacy Policy</a>.</p>`);
  p('');
  p(`<p class="lead">This page lists, item by item, every category of personal data ${esc(appName)} collects, why it is collected, how long it is kept and who outside Nikatru touches it. It is generated from the declaration the app itself is built and audited against, so it cannot drift from what the code does without a build failing.</p>`);
  p('');
  p('<div class="callout">');
  p('<span class="tag">In one line</span>');
  p(`<p style="margin:8px 0 0">${esc(`${appName} collects ${plural(rows.length, 'category', 'categories')} of personal data for ${plural(purposes.length, 'stated purpose', 'stated purposes')}, keeps each for a fixed period, shares ${shared.length === 0 ? 'none of it' : plural(shared.length, 'category', 'categories')} with anyone beyond the service providers named below, and records no network address at all.`)}</p>`);
  p('</div>');

  // ── 1 · what is collected ────────────────────────────────────────────────
  p('');
  p('<h2>1. What is collected</h2>');
  p(`<p>${plural(rows.length, 'category', 'categories')}, in the vocabulary the Google Play Data safety form uses — the same words the sworn store declaration answers in, so the two cannot quietly disagree.</p>`);
  p('<table>');
  p('<tr><th>Category</th><th>What it is</th><th>Why</th><th>Kept for</th><th>Needed to use the app?</th><th>Shared?</th></tr>');
  for (const r of rows) {
    p(
      `<tr><td>${esc(r.category)}</td><td>${esc(r.type)}</td><td>${esc((r.purposes ?? []).join(', '))}</td>`
        + `<td>${r.retentionClass} days</td><td>${r.required === true ? 'Yes' : 'No'}</td><td>${r.shared === true ? 'Yes' : 'No'}</td></tr>`,
    );
  }
  p('</table>');

  // ── 2 · why each row says what it says ───────────────────────────────────
  p('');
  p('<h2>2. Why each of those answers is what it is</h2>');
  p('<p>Every row above carries the reason it was decided on, the file that reason was read out of, and the date it was read. They are reproduced here in full rather than summarised, because a summary of a basis is a new claim.</p>');
  for (const r of rows) {
    p(`<h3>${esc(r.category)} — ${esc(r.type)}</h3>`);
    p(`<p>${esc(r.basis)}</p>`);
    p(`<p class="meta">Read from <code>${esc(r.source)}</code> on ${esc(r.asOf)}.</p>`);
  }

  // ── 3 · how long ─────────────────────────────────────────────────────────
  p('');
  p('<h2>3. How long each period is, and why it is that number</h2>');
  p('<p>There are three retention periods in this portfolio and no others. They are locked: a convenience change cannot quietly extend how long personal data is kept, because the declaration will not accept a fourth value.</p>');
  p('<ul>');
  for (const c of classes) {
    p(`  <li><strong>${c} days</strong> — ${esc(RETENTION_MEANING[c] ?? 'a locked retention class')}.</li>`);
  }
  p('</ul>');

  // ── 4 · who else ─────────────────────────────────────────────────────────
  p('');
  p('<h2>4. Who else touches it</h2>');
  const procs = doc.processors ?? [];
  p(`<p>${plural(procs.length, 'service provider', 'service providers')}. Services Nikatru runs on its own machines are deliberately not listed: they are infrastructure this company operates, not a party the data is disclosed to.</p>`);
  p('<table>');
  p('<tr><th>Who</th><th>Role</th><th>What they do with it</th></tr>');
  for (const pr of procs) {
    // ⏱ 2026-09-25 — the page names the COMPANY (the register row's `name`),
    // not the register id: "revenuecat" is a key, "RevenueCat" is a party a
    // reader can look up. O-APP-PRIVACY-OMITS-STORE-BILLING.
    const name = providerNames.get(pr.id);
    if (name === undefined) {
      throw new Error(`processor "${pr.id}" has no row in ${PROVIDER_REGISTER}, so the notice has no company name to print for it.`);
    }
    p(`<tr><td>${esc(name)}</td><td>${esc(String(pr.role).replace(/_/g, ' '))}</td><td>${esc(pr.purpose)}</td></tr>`);
  }
  p('</table>');

  // ── 5 · what is never collected ──────────────────────────────────────────
  p('');
  p('<h2>5. What is never collected</h2>');
  p('<p>No network address is recorded anywhere, for any of the rows above. This is not a setting: there is no column to put one in, the declaration cannot say otherwise, and a build fails if the words appear in it. It is the one identifier that would turn every analytics row into personal data, and it is the one this portfolio does not keep.</p>');
  p('<p>Nothing on this page is collected from anyone under 18. Nikatru does not offer any app, extension or site to children, and does not knowingly collect data from them.</p>');

  // ── 6 · the itemised notice ──────────────────────────────────────────────
  p('');
  p('<h2>6. Notice, consent and your rights</h2>');
  p('<p>This section is the itemised notice: what is processed, for what purpose, how a consent is withdrawn, and how a complaint is made. It is generated from the same declaration as the table above, so the notice and the practice are one document.</p>');
  p('<h3>What is processed, and for what purpose</h3>');
  p('<p>Exactly the categories in section 1, each for exactly the purposes listed beside it, and for no other purpose. Consent is recorded separately for each purpose and the record is append-only: a consent given for one purpose is never treated as a consent for another, and withdrawing one leaves the others as they were.</p>');
  p('<h3>How to withdraw a consent</h3>');
  p('<p>Every consent given in the app can be withdrawn in the app, at any time, with the same number of taps it took to give. Withdrawal stops the processing that depended on it; it does not undo processing that had already happened, and it does not affect the categories marked as needed to use the app, which are held for as long as the account exists.</p>');
  p('<h3>How to have your data erased</h3>');
  p(`<p>Deleting the account erases everything keyed to it. The reach of that deletion is derived from the database schema rather than from a list somebody keeps up to date by hand, so a new table cannot be silently missed. Start at <a href="/delete-account">nikatru.com/delete-account</a>.</p>`);
  p('<h3>How to reach a person, and how to complain</h3>');
  p(`<p>The grievance contact is on <a href="/contact">nikatru.com/contact</a>. A complaint that we do not resolve can be taken to the data-protection authority for your jurisdiction; for India that is the Data Protection Board established under the Digital Personal Data Protection Act, 2023.</p>`);
  p('<p class="meta">This section states what this app actually does, itemised from its declaration. It is written to be plain and complete rather than to a statutory checklist: the applicable notice-content provisions have not been read line by line against it, and that gap is tracked as an open item rather than papered over with a claim of compliance.</p>');

  p('');
  p(`<p class="meta">Generated from <code>apps/${esc(appId)}/privacy.yaml</code>, declaration date ${esc(doc.asOf)}.</p>`);
  p('');
  p('</main>');
  p('');
  p(region('footer'));
  p('');
  p('</body>');
  p('</html>');
  return `${out.join('\n')}\n`;
}

/* ------------------------------------------------------------------ */
/* The Chrome Web Store privacy-practices block                        */

const ANSWER = {
  'local-only': '**YES — handled locally only**',
  'not-collected': '**NO**',
  collected: '**YES — collected**',
};

/** What the tool template gets, because a template cannot answer for a tool
 *  that does not exist yet. The brick stamps its four sworn store files
 *  UNANSWERED for exactly this reason, and this is the same decision: a
 *  plausible default here would be a store answer nobody made, and the one
 *  default that is tempting — "this item does not collect user data" — is the
 *  one that is a policy strike when the tool reads any page content. */
export const UNANSWERED = [
  '⛔ **UNANSWERED — this tool has no `publish/privacy.yaml` yet.**',
  '',
  'Write one beside this file (copy `extensions/Extension/Full_Screen_Shot/publish/privacy.yaml`,',
  'which is the worked example) and re-run `node tooling/app-yaml/render-privacy.mjs`. The nine',
  'answers below this line are then generated from it and this notice disappears.',
  '',
  '🔴 Do **not** hand-write the answers into this block. It is fenced by the two markers around it',
  'and `tooling/ci/assert-app-yaml.mjs` fails the build on any edit inside them — for the same reason',
  'a store listing file carries no "generated" header: the bytes here are pasted into a dashboard, and',
  'a dashboard answer that contradicts the code is a policy strike at account level.',
  '',
  '🔴 In particular, do not tick *"This item does not collect user data"* for any tool that reads page',
  'content. Under Google’s User Data FAQ Q2–Q3 taking a screenshot, reading DOM text or reading a page',
  'title IS handling user data, and local-only handling must still be disclosed.',
].join('\n');

export function renderStoreBlock(doc) {
  const out = [];
  const p = (s) => out.push(s);
  p('Data collection disclosures — the nine **Privacy practices → Data usage** categories, in the');
  p('dashboard’s own order. Every answer carries the basis it was decided on and the file that basis');
  p('was read out of.');
  p('');
  p('| Category | Dashboard answer | Why |');
  p('|---|---|---|');
  for (const d of doc.storeDisclosures ?? []) {
    p(`| ${cell(d.category)} | ${ANSWER[d.disposition] ?? cell(d.disposition)} | ${cell(d.basis)} |`);
  }
  p('');
  p('Limited Use certification — all three must be affirmed:');
  p('');
  p('- ☑ I do not sell user data to third parties.');
  p('- ☑ I do not use or transfer user data for purposes unrelated to my item’s single purpose.');
  p('- ☑ I do not use or transfer user data to determine creditworthiness or for lending purposes.');
  p('');
  p(`Why each is affirmable: ${cell(doc.limitedUse?.basis ?? '')}`);
  p('');
  const src = doc.limitedUse?.source;
  p(`Rendered from \`publish/privacy.yaml\`, declaration date ${cell(doc.asOf)}${src ? `; Limited Use basis read from \`${cell(src)}\`` : ''}.`);
  return out.join('\n');
}

/** Replace the fenced region of `text` with `block`. Returns null when the file
 *  does not carry both markers, which is a FINDING and never a silent skip. */
export function spliceBlock(text, block) {
  const start = text.indexOf(MARK_START);
  if (start === -1) return null;
  const end = text.indexOf(MARK_END, start);
  if (end === -1) return null;
  return `${text.slice(0, start + MARK_START.length)}\n\n${block}\n\n${text.slice(end)}`;
}

/* ------------------------------------------------------------------ */
/* Plan                                                                */

/**
 * Read every privacy declaration and compute every notice rendering. Nothing is
 * written here.
 *
 * 🔴 THE COVERAGE REFUSALS, AND WHY EACH IS 2 RATHER THAN 0. Every one of them
 * describes a run that rendered NOTHING and would otherwise print ok:
 *   · no apps/ directory                — there is no app to render a notice for
 *   · not one apps/<id>/privacy.yaml    — the declaration this renders from does
 *                                         not exist, so "0 renderings, all fresh"
 *   · not one extension STORE-LISTING.md
 *     carries the markers               — the store half rendered nothing, and
 *                                         the page alone is not what this is for
 *   · every extension listing is the
 *     template                          — the only thing rendered was the
 *                                         "no declaration yet" notice, which
 *                                         proves nothing about a real tool
 */
export function planPrivacy(root) {
  const problems = [];
  const lost = [];
  const files = new Map();
  const declarations = [];

  const schema = JSON.parse(readFileSync(PRIVACY_SCHEMA_PATH, 'utf8'));

  /** Parse and grade one declaration whose bytes have ALREADY been read. Taking
   *  the text rather than the path is what keeps this side of the script free of
   *  a check-then-read pair — see `readIf`. */
  const gradeDoc = (rel, text) => {
    let doc;
    try {
      doc = parseYaml(text);
    } catch (e) {
      problems.push(`${rel}: ${e instanceof YamlError ? e.message : String(e)}`);
      return null;
    }
    const bad = validate(doc, schema, rel);
    if (bad.length) {
      for (const b of bad) problems.push(b);
      return null;
    }
    // ⏱ 2026-09-24 — A REPOSITORY-PATH `source` MUST NAME A FILE THAT EXISTS.
    // The schema grades a source's SHAPE (repo-path or https-url) and nothing
    // opened it, so a row could cite a deleted file and still render and pass:
    // a source naming any missing path exited 0 here and in assert-app-yaml,
    // measured before this limb. A basis read from a file that is gone cannot be
    // re-read. An https source is an external authority and is not fetched. The
    // doc is still returned, so the run stays a FINDING (1) and never turns into
    // a coverage loss (2) for want of a declaration to render.
    const sources = [
      ...(doc.collects ?? []).map((r) => r?.source),
      ...(doc.storeDisclosures ?? []).map((r) => r?.source),
      ...(doc.processors ?? []).map((r) => r?.source),
      doc.limitedUse?.source,
    ].filter((s) => typeof s === 'string' && !s.startsWith('https://'));
    for (const s of [...new Set(sources)]) {
      if (!existsSync(join(root, s))) {
        problems.push(`${rel}: source ${s} does not exist in this repository. A row's basis must be re-readable from the file it names; point the source at the file that holds that reasoning now.`);
      }
    }
    return doc;
  };

  // ── the app notices ───────────────────────────────────────────────────────
  const appsAbs = join(root, APPS_DIR);
  if (!isDir(appsAbs)) {
    lost.push(`${APPS_DIR}/ does not exist, so this run had no app declaration to render a notice from.`);
    return { declarations, files, problems, lost };
  }
  // Read once. `readIf` returns null for an absent file, so the set of apps that
  // declare and the bytes they declare come out of the same observation.
  const appDeclarations = listDirs(appsAbs)
    .sort()
    .map((id) => [id, readIf(join(appsAbs, id, 'privacy.yaml'))])
    .filter(([, text]) => text !== null);
  if (appDeclarations.length === 0) {
    lost.push(
      `no ${APPS_DIR}/<id>/privacy.yaml exists. The per-app notice is a function of that declaration, so `
        + 'zero declarations render zero bytes and every comparison below would pass over an empty set.',
    );
    return { declarations, files, problems, lost };
  }
  // The company name printed for each processor. Read here, once, for every app.
  const registerText = readIf(join(root, PROVIDER_REGISTER));
  if (registerText === null) {
    lost.push(`${PROVIDER_REGISTER} does not exist, so no processor on an app notice can be named.`);
    return { declarations, files, problems, lost };
  }
  let providerNames;
  try {
    const reg = JSON.parse(registerText);
    providerNames = new Map(
      (Array.isArray(reg.providers) ? reg.providers : [])
        .filter((row) => row && typeof row.id === 'string' && typeof row.name === 'string')
        .map((row) => [row.id, row.name]),
    );
  } catch (e) {
    problems.push(`${PROVIDER_REGISTER}: not valid JSON (${e.message}), so no processor on an app notice can be named.`);
    return { declarations, files, problems, lost };
  }
  for (const [id, text] of appDeclarations) {
    const rel = `${APPS_DIR}/${id}/privacy.yaml`;
    const doc = gradeDoc(rel, text);
    if (!doc) continue;
    if (doc.app !== id) {
      problems.push(`${rel}: declares app "${doc.app}" but lives in ${APPS_DIR}/${id}/ — two files describing two different apps.`);
      continue;
    }
    if (doc.surface !== 'app') {
      problems.push(`${rel}: declares surface "${doc.surface}". A declaration under ${APPS_DIR}/ is the app surface; the extension surface lives under ${EXTENSIONS_DIR}/.`);
      continue;
    }
    // The display name comes from app.yaml when there is one — one name, one
    // source. Without it the id is used rather than a name being invented.
    let appName = id;
    const appYaml = readIf(join(root, APPS_DIR, id, 'app.yaml'));
    if (appYaml) {
      const m = /^name:\s*(.+)$/m.exec(appYaml);
      if (m) appName = m[1].trim().replace(/^["']|["']$/g, '');
    }
    let page;
    try {
      page = renderAppPage(doc, { appName, appId: id, providerNames });
    } catch (e) {
      problems.push(`${rel}: ${e.message}`);
      continue;
    }
    declarations.push({ surface: 'app', id, rel, doc });
    files.set(`${SITE_ROOT}/${id}/privacy.html`, page);
  }

  // ── the extension store blocks ────────────────────────────────────────────
  let listingsFenced = 0;
  let realListings = 0;
  const extAbs = join(root, EXTENSIONS_DIR);
  if (isDir(extAbs)) {
    for (const listingRel of findStoreListings(root)) {
      const current = readIf(join(root, listingRel));
      if (current === null) continue;
      if (!current.includes(MARK_START)) continue;
      listingsFenced += 1;
      const isTemplate = listingRel === TEMPLATE_LISTING;
      const declRel = `${dirname(listingRel)}/privacy.yaml`;
      let block;
      const declText = readIf(join(root, declRel));
      if (declText !== null) {
        // 🔴 COUNTED BEFORE IT IS VALIDATED, and that ordering is the whole
        // point. Counting a real tool's listing only once its declaration
        // PARSED means a broken declaration empties the count, the refusal
        // below fires, and the run exits 2 reporting "nothing to compare" —
        // hiding the finding, which is the broken declaration, behind a
        // coverage message that names the wrong repair. The guard's own limb 1
        // carries this exact correction in its header ("a declaration that does
        // not parse stops the run here… the finding is the broken declaration")
        // and it was re-learned here: `tooling/ci/test/app-yaml.test.mjs`'s
        // extension-grading case went 2 instead of 1 until this moved.
        if (!isTemplate) realListings += 1;
        const doc = gradeDoc(declRel, declText);
        if (!doc) continue;
        if (doc.surface !== 'extension') {
          problems.push(`${declRel}: declares surface "${doc.surface}". A declaration beside a store listing is the extension surface.`);
          continue;
        }
        declarations.push({ surface: 'extension', id: doc.app, rel: declRel, doc });
        block = renderStoreBlock(doc);
      } else {
        block = UNANSWERED;
      }
      const next = spliceBlock(current, block);
      if (next === null) {
        problems.push(`${listingRel}: carries the opening privacy-practices marker but not the closing one, so the fenced region has no end.`);
        continue;
      }
      files.set(listingRel, next);
    }
  }
  if (listingsFenced === 0) {
    lost.push(
      `not one ${EXTENSIONS_DIR}/**/publish/STORE-LISTING.md carries the privacy-practices markers. The store `
        + 'half of this renderer then covers nothing, and the per-app page alone is not what a privacy generator is for.',
    );
  } else if (realListings === 0) {
    lost.push(
      `every fenced store listing is the tool TEMPLATE — ${listingsFenced} fenced, 0 belonging to a real tool with a `
        + 'declaration. The only thing rendered was the "no declaration yet" notice, which proves nothing about any '
        + 'answer that reaches a store console.',
    );
  }

  return { declarations, files, problems, lost };
}

/** Every `publish/STORE-LISTING.md` under `extensions/`, repo-relative. */
function findStoreListings(root) {
  const out = [];
  const walk = (relDir) => {
    const abs = join(root, relDir);
    let entries;
    try {
      entries = readdirSync(abs, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const rel = `${relDir}/${e.name}`;
      if (e.isDirectory()) {
        if (e.name === 'node_modules' || e.name === '.git') continue;
        walk(rel);
      } else if (e.name === 'STORE-LISTING.md' && relDir.endsWith('/publish')) {
        out.push(rel);
      }
    }
  };
  walk(EXTENSIONS_DIR);
  return out.sort();
}

/* ------------------------------------------------------------------ */
/* Main                                                                */

export function renderPrivacy(root, { check = false } = {}) {
  const { files, problems, lost, declarations } = planPrivacy(root);
  if (lost.length) return { code: 2, lost, problems, stale: [], wrote: [], total: 0, declarations };
  if (problems.length) return { code: 1, lost, problems, stale: [], wrote: [], total: 0, declarations };
  const stale = [];
  const wrote = [];
  for (const [rel, contents] of files) {
    const abs = join(root, rel);
    const current = readIf(abs);
    if (current === contents) continue;
    stale.push(rel);
    if (!check) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, contents);
      wrote.push(rel);
    }
  }
  return { code: check && stale.length ? 1 : 0, lost, problems, stale, wrote, total: files.size, declarations };
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (invokedDirectly) {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const positional = args.filter((a) => !a.startsWith('--'));
  const root = resolve(positional[0] ?? join(HERE, '..', '..'));
  const r = renderPrivacy(root, { check });
  if (r.code === 2) {
    console.error('');
    for (const l of r.lost) console.error(`FAIL COVERAGE LOST — ${l}`);
    console.error('\nrender-privacy: COVERAGE LOST');
    process.exit(2);
  }
  if (r.problems.length) {
    for (const p of r.problems) console.error(`✗ ${p}`);
    console.error(`\nrender-privacy: ${r.problems.length} problem(s) in the declaration(s) — nothing was written.`);
    process.exit(1);
  }
  const apps = r.declarations.filter((d) => d.surface === 'app').length;
  const exts = r.declarations.filter((d) => d.surface === 'extension').length;
  if (check) {
    if (r.stale.length) {
      console.error('✗ these notice surfaces no longer match the declaration they are rendered from:');
      for (const s of r.stale) console.error(`    ${s}`);
      console.error('\n  Change the declaration, not the rendering, then:  node tooling/app-yaml/render-privacy.mjs');
      console.error('  (A STORE-LISTING.md edit BETWEEN the privacy-practices markers is exactly this failure.)');
      process.exit(1);
    }
    console.log(`ok   render-privacy --check — ${r.total} notice rendering(s) match ${apps} app and ${exts} extension declaration(s)`);
    process.exit(0);
  }
  if (r.wrote.length) for (const w of r.wrote) console.log(`wrote ${w}`);
  console.log(`ok   render-privacy — ${r.total} notice rendering(s) from ${apps} app and ${exts} extension declaration(s), ${r.wrote.length} rewritten`);
  process.exit(0);
}
