#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// render.mjs — THE PORT TABLES CODE READS, RENDERED FROM THE REGISTRIES.
//
//   node tooling/ports/render.mjs [--check] [--root <repoRoot>]
//
// Writes services/platform/src/generated/ports.ts from tooling/ports/payments.json:
// the payments adapter list per environment (id, status, environments, declared
// capabilities) and each rail's cancel path, DERIVED from its capabilities (`cancel`
// → api, `cancel-store` → store, neither → none). The Worker's composition root
// (services/platform/src/ports.ts) and lib/mor/registry.ts read these tables; no
// hand array restates them. The rail PRICE map (RAIL_PRICE_IDS[railId][appId][offeringId])
// is rendered by the generator that already owns the price ids,
// tooling/catalog/render-rail-prices.mjs, into routes/rail-price-ids.ts — one renderer
// per source register, never a hand merge.
//
// --check re-renders in memory and compares: exit 1 on any difference (a hand edit of
// the generated file, or a registry edit not re-rendered), 2 when the registry cannot
// be read (COVERAGE LOST), 0 when current. Without --check it writes. assert-ports.mjs
// limb 3 runs `renderCheck` on every build. Row O-NO-PORT-SELECTS-AN-ADAPTER-BY-CONFIG.
// ─────────────────────────────────────────────────────────────────────────────
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const PAYMENTS_REGISTRY = 'tooling/ports/payments.json';
export const RENDERED_PORTS = 'services/platform/src/generated/ports.ts';
const ENV_ORDER = ['test', 'sandbox', 'live'];

/** The cancel path a rail's DECLARED capabilities give it. */
export function cancelPathOf(capabilities) {
  const caps = new Set(capabilities ?? []);
  if (caps.has('cancel')) return 'api';
  if (caps.has('cancel-store')) return 'store';
  return 'none';
}

const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const list = (xs) => `[${xs.map(q).join(', ')}]`;

/** The generated module's bytes for one payments registry document. */
export function renderPortsTs(doc) {
  const adapters = (doc?.adapters ?? []).filter((a) => a && typeof a.id === 'string');
  const ids = adapters.map((a) => a.id);
  const L = [
    '// GENERATED by tooling/ports/render.mjs from tooling/ports/payments.json.',
    '// Do not edit: `node tooling/ports/render.mjs --check` re-renders this file and fails on any difference,',
    '// and assert-ports.mjs limb 3 runs that check on every build. Change the registry, then re-render.',
    '',
    `export type PaymentsAdapterId = ${ids.map(q).join(' | ') || 'never'};`,
    "export type PortEnvironment = 'test' | 'sandbox' | 'live';",
    "export type RailCancelPath = 'api' | 'store' | 'none';",
    '',
    'export interface PaymentsAdapterRow {',
    '  readonly id: PaymentsAdapterId;',
    '  readonly status: string;',
    '  readonly environments: readonly PortEnvironment[];',
    '  readonly capabilities: readonly string[];',
    '  readonly cancelPath: RailCancelPath;',
    '}',
    '',
    '// Every payments adapter, in registry order, with the environments it may serve.',
    'export const PAYMENTS_ADAPTERS: readonly PaymentsAdapterRow[] = [',
  ];
  for (const a of adapters) {
    const envs = ENV_ORDER.filter((e) => (a.environments ?? []).includes(e));
    L.push(
      `  { id: ${q(a.id)}, status: ${q(a.status)}, environments: ${list(envs)}, capabilities: ${list(a.capabilities ?? [])}, cancelPath: ${q(cancelPathOf(a.capabilities))} },`,
    );
  }
  L.push('];', '');
  L.push('// How each rail cancels, DERIVED from its declared capabilities (cancel → api, cancel-store → store).');
  L.push('export const RAIL_CANCEL_PATH: Readonly<Record<string, RailCancelPath>> = {');
  for (const a of adapters) L.push(`  ${a.id}: ${q(cancelPathOf(a.capabilities))},`);
  L.push('};', '');
  // The inbound rails that verify REAL money: every non-fake, non-retired adapter declaring `verify`. The
  // composition root builds MOR_VERIFIERS from this list, and the money guards (assert-mor-adapters,
  // assert-money-config, assert-purchase-path, the policy-claims rail row) read the provider set from it.
  const moneyRails = adapters.filter((a) => a.status !== 'fake' && a.status !== 'retired' && (a.capabilities ?? []).includes('verify'));
  L.push('// The inbound rails that verify real money (non-fake adapters declaring `verify`), in registry order.');
  L.push(`export const MOR_VERIFIER_IDS = ${list(moneyRails.map((a) => a.id))} as const satisfies readonly PaymentsAdapterId[];`, '');
  // The web checkout rail: the ONE real adapter that declares `checkout`. Two would need a per-channel
  // selection (channel-register purchaseRails) the checkout route does not read yet, so two render null
  // and the route refuses rather than guessing.
  const sellers = adapters.filter((a) => a.status !== 'fake' && a.status !== 'retired' && a.status !== 'draft' && (a.capabilities ?? []).includes('checkout'));
  L.push('// The web checkout rail: the one non-fake adapter declaring `checkout` (null when zero or several do).');
  L.push(`export const CHECKOUT_RAIL_ID: PaymentsAdapterId | null = ${sellers.length === 1 ? q(sellers[0].id) : 'null'};`, '');
  L.push('// The adapter ids per environment: the set a deploy of that environment may select.');
  L.push('export const PAYMENTS_ADAPTERS_BY_ENVIRONMENT: Readonly<Record<PortEnvironment, readonly PaymentsAdapterId[]>> = {');
  for (const e of ENV_ORDER) L.push(`  ${e}: ${list(adapters.filter((a) => (a.environments ?? []).includes(e)).map((a) => a.id))},`);
  L.push('};');
  return `${L.join('\n')}\n`;
}

/**
 * The file's text, or null when it does not exist. ONE read, never an exists-then-read
 * pair: a check between the test and the use is a file-system race (CodeQL
 * js/file-system-race, #1127). Any error but ENOENT — a directory, a permission — throws,
 * and the callers turn it into LOST rather than into "absent".
 */
export function readIfPresent(abs) {
  try {
    return readFileSync(abs, 'utf8');
  } catch (e) {
    if (e?.code === 'ENOENT') return null;
    throw e;
  }
}

/** Re-render in memory and compare. {ok, lost, detail}. */
export function renderCheck(root) {
  let doc;
  try {
    doc = JSON.parse(readFileSync(join(root, PAYMENTS_REGISTRY), 'utf8'));
  } catch (e) {
    return { ok: false, lost: true, detail: `${PAYMENTS_REGISTRY} could not be read (${e.message})` };
  }
  if (!Array.isArray(doc?.adapters) || doc.adapters.length === 0) {
    return { ok: false, lost: true, detail: `${PAYMENTS_REGISTRY} lists no adapter; a table of zero rows is current by construction` };
  }
  const want = renderPortsTs(doc);
  const abs = join(root, RENDERED_PORTS);
  let have;
  try {
    have = readIfPresent(abs);
  } catch (e) {
    return { ok: false, lost: true, detail: `${RENDERED_PORTS} could not be read (${e.message})` };
  }
  if (have === null) return { ok: false, lost: false, detail: `${RENDERED_PORTS} does not exist; run node tooling/ports/render.mjs` };
  if (have !== want) {
    const a = have.split('\n');
    const b = want.split('\n');
    let i = 0;
    while (i < Math.max(a.length, b.length) && a[i] === b[i]) i++;
    return {
      ok: false,
      lost: false,
      detail: `${RENDERED_PORTS} differs from its render at line ${i + 1}: have ${JSON.stringify(a[i] ?? '<eof>')}, want ${JSON.stringify(b[i] ?? '<eof>')}. A generated file is never hand-edited; re-render from ${PAYMENTS_REGISTRY}.`,
    };
  }
  return { ok: true, lost: false, detail: `${RENDERED_PORTS} matches ${PAYMENTS_REGISTRY} (${doc.adapters.length} adapter(s))` };
}

function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const at = args.indexOf('--root');
  const root = resolve(at >= 0 ? args[at + 1] ?? '.' : process.cwd());
  for (const a of args) {
    if (a.startsWith('--') && a !== '--check' && a !== '--root') {
      console.error(`render: REFUSED — unknown flag ${a}`);
      process.exit(2);
    }
  }
  if (check) {
    const r = renderCheck(root);
    if (r.ok) console.log(`ok   render --check — ${r.detail}`);
    else console.error(`${r.lost ? 'LOST' : 'FAIL'} render --check — ${r.detail}`);
    process.exit(r.ok ? 0 : r.lost ? 2 : 1);
  }
  let doc;
  try {
    doc = JSON.parse(readFileSync(join(root, PAYMENTS_REGISTRY), 'utf8'));
  } catch (e) {
    console.error(`LOST render — ${PAYMENTS_REGISTRY} could not be read (${e.message})`);
    process.exit(2);
  }
  const abs = join(root, RENDERED_PORTS);
  mkdirSync(dirname(abs), { recursive: true });
  const want = renderPortsTs(doc);
  let have;
  try {
    have = readIfPresent(abs);
  } catch (e) {
    console.error(`LOST render — ${RENDERED_PORTS} could not be read (${e.message})`);
    process.exit(2);
  }
  if (have !== want) writeFileSync(abs, want);
  console.log(`ok   render — ${have === want ? 'unchanged' : 'wrote'} ${RENDERED_PORTS}`);
}

const IS_MAIN = (() => {
  try { return resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url); } catch { return false; }
})();
if (IS_MAIN) main();
