#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// render-entity.mjs — the entity-source facts Worker code needs, rendered into
// services/platform/src/generated/entity.ts so no address is a literal in a
// Worker's source.
//
// THE ONE SOURCE is tooling/house-identity.json: `mail.from.<stream>` (the From
// of each mail stream, tooling/ports/mail.json `streams`) and `supportEmail`
// (the published support inbox, the report notice's recipient). The Worker
// reads MAIL_FROM and SUPPORT_EMAIL from the generated module; assert-ports
// limb 9 refuses an owner-domain address literal anywhere else in
// services/*/src and runs this file's comparison, so the generated module
// cannot drift from the source in CI.
//
// A small renderer for the mail fields only (port-mail). When a general entity
// renderer lands (tooling/ports/render.mjs), it takes this output over.
//
// Usage:  node tooling/ports/render-entity.mjs [--check] [--root <dir>]
// Exit 0 = written (or, with --check, already current). 1 = --check found a
// difference, or the source lacks a field. 2 = the source could not be read.
// ─────────────────────────────────────────────────────────────────────────────
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ENTITY_SOURCE = 'tooling/house-identity.json';
export const ENTITY_TARGET = 'services/platform/src/generated/entity.ts';

const isObj = (v) => typeof v === 'object' && v !== null && !Array.isArray(v);

/** The generated module's text for an entity-source document, or {error}. */
export function renderEntity(doc) {
  const from = doc?.mail?.from;
  if (!isObj(from)) return { error: `${ENTITY_SOURCE} has no \`mail.from\` object` };
  const streams = Object.keys(from).filter((k) => !k.startsWith('_'));
  if (!streams.length) return { error: `${ENTITY_SOURCE} \`mail.from\` names no stream` };
  for (const s of streams) {
    if (!/^[a-z][a-z0-9]*$/.test(s)) return { error: `${ENTITY_SOURCE} \`mail.from.${s}\` is not a stream name` };
    if (typeof from[s]?.value !== 'string' || !from[s].value) return { error: `${ENTITY_SOURCE} \`mail.from.${s}.value\` is not a non-empty string` };
  }
  const support = doc?.supportEmail?.value;
  if (typeof support !== 'string' || !support) return { error: `${ENTITY_SOURCE} \`supportEmail.value\` is not a non-empty string` };
  const lines = [
    `// GENERATED by tooling/ports/render-entity.mjs from ${ENTITY_SOURCE} (\`mail.from.*\`, \`supportEmail\`).`,
    '// Edit the entity source and re-render; never this file. `node tooling/ports/render-entity.mjs --check`',
    '// fails on any difference, and tooling/ci/assert-ports.mjs limb 9 runs the same comparison.',
    '',
    '/** The From of each Worker mail stream — `mail.from.<stream>`. */',
    'export const MAIL_FROM = {',
    ...streams.map((s) => `  ${s}: ${JSON.stringify(from[s].value)},`),
    '} as const;',
    '',
    '/** The published support inbox — `supportEmail`. */',
    `export const SUPPORT_EMAIL = ${JSON.stringify(support)};`,
    '',
  ];
  return { text: lines.join('\n') };
}

/** Compare (or write) the generated module under `root`. Returns {code, msg}. */
export function renderEntityAt(root, { check }) {
  let doc;
  try { doc = JSON.parse(readFileSync(join(root, ENTITY_SOURCE), 'utf8')); } catch (e) {
    return { code: 2, msg: `render-entity: COVERAGE LOST — ${ENTITY_SOURCE} could not be read (${e.message})` };
  }
  const r = renderEntity(doc);
  if (r.error) return { code: 1, msg: `render-entity: REFUSED — ${r.error}` };
  const abs = join(root, ENTITY_TARGET);
  // Read, never stat-then-read: a missing file is ENOENT here, so there is no
  // check-then-use window before the write below (CodeQL js/file-system-race).
  let current = null;
  try { current = readFileSync(abs, 'utf8'); } catch (e) {
    if (e?.code !== 'ENOENT') return { code: 2, msg: `render-entity: COVERAGE LOST — ${ENTITY_TARGET} could not be read (${e.message})` };
  }
  if (check) {
    if (current === r.text) return { code: 0, msg: `render-entity: ok — ${ENTITY_TARGET} is what ${ENTITY_SOURCE} renders` };
    return { code: 1, msg: `render-entity: STALE — ${ENTITY_TARGET} ${current === null ? 'does not exist' : 'differs from'} what ${ENTITY_SOURCE} renders. Run: node tooling/ports/render-entity.mjs` };
  }
  if (current !== r.text) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, r.text);
    return { code: 0, msg: `render-entity: wrote ${ENTITY_TARGET}` };
  }
  return { code: 0, msg: `render-entity: ${ENTITY_TARGET} already current` };
}

function main() {
  const argv = process.argv.slice(2);
  let root = process.cwd();
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--check') check = true;
    else if (argv[i] === '--root' && argv[i + 1] && !argv[i + 1].startsWith('--')) root = argv[++i];
    else { console.error(`render-entity: REFUSED — unknown argument ${argv[i]}`); process.exit(2); }
  }
  const { code, msg } = renderEntityAt(resolve(root), { check });
  (code ? console.error : console.log)(msg);
  process.exit(code);
}

const IS_MAIN = (() => {
  try { return resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url); } catch { return false; }
})();
if (IS_MAIN) main();
