// GENERATED by `node tooling/ci/assert-runtime-signer-check.mjs --write` from
// tooling/channel-register.json `runtimeSignerCheck` and each app's per-app pin
// in apps/<id>/app.yaml. NEVER HAND-EDIT: the guard fails CI when this file and
// those sources disagree.
//
// The expected signing-certificate digests (SHA-256, uppercase hex) an Android
// build compiles in. `complete` is true only when EVERY pin the set declares is
// set; an incomplete set reports and never blocks. A per-app pin (Play App
// Signing holds one key per app) is never in a channel default.
import 'device_integrity.dart' show SignerPins;

/// The CHANNEL DEFAULT by `RELEASE_CHANNEL`: the factory-wide pins, for an app
/// with no row of its own in [kSignerPinsByApp].
const Map<String, SignerPins> kSignerPinsByChannel = <String, SignerPins>{
  // signing.uploadCertificate.sha256
  // per app: stores.android-play.appSigningSha256 — kSignerPinsByApp
  'android-play': SignerPins(
    digests: <String>[
      '43C84D1162C4D19C0FA0C5E001905B89523DC082A68083C993069B863C28A616',
    ],
    complete: false,
  ),
  // signing.signingCertificate.sha256 — not set
  'apps-gov-in': SignerPins(digests: <String>[], complete: false),
};

/// The pins by app id, then `RELEASE_CHANNEL`: the factory-wide pins plus the
/// app's own, for each app whose apps/<id>/app.yaml records its per-app pin.
const Map<String, Map<String, SignerPins>>
kSignerPinsByApp = <String, Map<String, SignerPins>>{
  'subscriptiontracker': <String, SignerPins>{
    // apps/subscriptiontracker/app.yaml stores.android-play.appSigningSha256
    'android-play': SignerPins(
      digests: <String>[
        '43C84D1162C4D19C0FA0C5E001905B89523DC082A68083C993069B863C28A616',
        '98FA5FDCA1491BEC84198D3DABE797B0432985741581BBFEA2555B176C833A3C',
      ],
      complete: true,
    ),
  },
};
