#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// gen-ci-map.mjs — the CI docs' workflow facts, written from the workflows.
//
// Rows O-CI-DOCS-DESCRIBE-A-GONE-TREE and O-GUARD-HEADERS-CITE-CODE-BY-LINE-NUMBER
// (limb c). Until this file, docs/ci/README.md §3, §6, §7 and §9 and
// tooling/release/RELEASE-RUNBOOK.md §2 each carried a hand copy of a fact the
// workflows already state, and each copy had moved away from its source: the
// runbook named the tag lane by a `name:` the workflow no longer has and said
// one workflow triggers on a tag where two do; §7 counted five third-party
// actions where the tree uses six; §6 named a Windows secret no workflow reads.
// Nothing compared any of them to the files.
//
// Five marker blocks, each rendered from tooling/ci/workflow-scan.mjs (the one
// workflow reader) and nothing else:
//
//   docs/ci/README.md                  lane-map   ci.yml's jobs and ci-gate's needs (§3)
//                                      secrets    every `secrets.NAME` a workflow reads (§6)
//                                      actions    every action a workflow or a composite
//                                                 action under .github/actions uses (§7)
//                                      workflows  one row per workflow, with its page (§9)
//   tooling/release/RELEASE-RUNBOOK.md tag-trigger every workflow with `on: push: tags:` (§2)
//
// A block is the lines between
//   <!-- BEGIN GENERATED: gen-ci-map <block> -->
//   <!-- END GENERATED: gen-ci-map <block> -->
// and its first line is the `<!-- why: GENERATED by … --write. Never hand-edit. -->`
// comment. --write replaces what is between the two markers and nothing else.
//
// --check also runs three limbs over the lane pages and the tree:
//   (a) every `### above \`X\`` heading in docs/ci/<w>.md quotes X, and X is on
//       a line of .github/workflows/<w>.yml. A page's anchor that names a line
//       the workflow no longer has points a reader at nothing. An X ending in
//       `…` is the start of a long line, and only that start is looked for.
//   (b) a `##` heading in a lane page that names ONE token — `## job \`X\`` or a
//       lone `## X` — names a job of that workflow. The 2026-09-06 migration
//       wrote a `## job` heading for some keys inside a job (`strategy`, `with`,
//       `needs`, `permissions`), and a reader then looks for a job that is not
//       there. Such a heading is demoted to `###`.
//   ⏱ 2026-09-26 (option B): for (a) and (b), "its workflow" is the page's
//       workflow AND every workflow it calls by a local `uses:`, as workflow-scan's
//       resolveLocalCalls reads them; a call that does not resolve is COVERAGE LOST.
//       docs/ci/extensions.md documents extensions-ci.yml's jobs, which
//       extensions.yml's `ci` job calls.
//   (c) no git-tracked file outside docs/ cites a line of a docs/ci page or of
//       RELEASE-RUNBOOK.md by number: every edit above the cited line moves it,
//       and most moved citations land on another real line. Cite the section
//       heading or the job instead. The files come from `git ls-files`, never a
//       filesystem walk, so an untracked scratch file is not the tree.
//
// Usage:
//   node tooling/ci/gen-ci-map.mjs [--check] [root]   (the default mode)
//   node tooling/ci/gen-ci-map.mjs --write [root]
//
// Exit codes: 0 green; 1 a finding, each printed as `file:line — what — the fix`;
// 2 COVERAGE LOST — a marker missing or doubled, a workflow that parses to no
// job, no workflow at all, no lane page in docs/ci, or a `git ls-files` that
// listed nothing. A block rendered from an empty tree, or a limb that read no
// file, would pass.
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { listDir } from './tree-walk.mjs';
import {
  WORKFLOW_DIR,
  parseAllWorkflows,
  parseAllActions,
  workflowName,
  workflowUses,
  workflowSecrets,
  workflowEvents,
  releaseTrigger,
  resolveLocalCalls,
} from './workflow-scan.mjs';

export const TOOL = 'gen-ci-map';
export const COMMAND = 'node tooling/ci/gen-ci-map.mjs';
export const DOCS_CI = 'docs/ci';
export const README_REL = `${DOCS_CI}/README.md`;
export const RUNBOOK_REL = 'tooling/release/RELEASE-RUNBOOK.md';
export const CI_REL = `${WORKFLOW_DIR}/ci.yml`;
/** The job whose `needs` is the merge gate — the single required check on main. */
export const AGGREGATE_JOB = 'ci-gate';
/** The token GitHub issues to every run; it is not a secret anybody creates. */
const ISSUED_TOKEN = 'GITHUB_TOKEN';
/** Owners whose actions GitHub itself publishes. */
const GITHUB_OWNERS = new Set(['actions', 'github']);

// ── Markers ──────────────────────────────────────────────────────────────────
// Exported so tooling/ci/channel-arming.mjs writes its two runbook blocks in the
// same shape, with its own tool name, rather than a second marker grammar.

export const beginMarker = (tool, block) => `<!-- BEGIN GENERATED: ${tool} ${block} -->`;
export const endMarker = (tool, block) => `<!-- END GENERATED: ${tool} ${block} -->`;
export const whyLine = (command) => `<!-- why: GENERATED by ${command} --write. Never hand-edit. -->`;

/**
 * Where one block sits in `text`: `{ ok: true, lines, begin, end }` with the
 * 0-based indexes of the two marker lines, or `{ ok: false, why }` when either
 * marker is missing, doubled, or out of order.
 */
export function findBlock(text, tool, block) {
  const lines = text.split('\n');
  const b = beginMarker(tool, block);
  const e = endMarker(tool, block);
  const at = (m) => lines.flatMap((l, i) => (l.trim() === m ? [i] : []));
  const bi = at(b);
  const ei = at(e);
  if (bi.length !== 1 || ei.length !== 1) {
    return { ok: false, why: `${bi.length} \`${b}\` line(s) and ${ei.length} \`${e}\` line(s); exactly one of each is required` };
  }
  if (ei[0] < bi[0]) return { ok: false, why: `\`${e}\` sits above \`${b}\`` };
  return { ok: true, lines, begin: bi[0], end: ei[0] };
}

/** The lines --write puts between the markers: the why line, then the body. */
export const blockLines = (command, body) => [whyLine(command), ...body];

/** `text` with one block's inside replaced, or null when its markers are not found. */
export function spliceBlock(text, tool, block, command, body) {
  const f = findBlock(text, tool, block);
  if (!f.ok) return null;
  const lines = [...f.lines];
  lines.splice(f.begin + 1, f.end - f.begin - 1, ...blockLines(command, body));
  return lines.join('\n');
}

/** Does the block in `text` hold exactly what --write would put there? null when its markers are not found. */
export function blockMatches(text, tool, block, command, body) {
  const f = findBlock(text, tool, block);
  if (!f.ok) return null;
  const have = f.lines.slice(f.begin + 1, f.end);
  return have.join('\n') === blockLines(command, body).join('\n');
}

// ── The tree ─────────────────────────────────────────────────────────────────

const cell = (s) => String(s).replace(/\|/g, '\\|');
const code = (s) => `\`${s}\``;
const fileOf = (rel) => rel.slice(rel.lastIndexOf('/') + 1);

/**
 * Every workflow and composite action, parsed. `lost` names what could not be
 * read: no workflow at all, or a workflow that parses to no job.
 */
export function readTree(root) {
  const lost = [];
  const workflows = parseAllWorkflows(root);
  if (workflows.length === 0) lost.push(`${WORKFLOW_DIR} holds no workflow, so every block would be rendered from nothing`);
  for (const wf of workflows) {
    if (wf.jobsAt === null || wf.jobs.size === 0) lost.push(`${wf.rel} parses to no job (no \`jobs:\` key with a job under it), so it cannot be described`);
  }
  const ci = workflows.find((w) => w.rel === CI_REL) ?? null;
  if (workflows.length > 0 && ci === null) lost.push(`${CI_REL} does not exist, so the lane map has no source`);
  if (ci !== null && !ci.jobs.has(AGGREGATE_JOB)) lost.push(`${CI_REL} has no \`${AGGREGATE_JOB}\` job, so no job can be said to be in its needs`);
  return { lost, workflows, actions: parseAllActions(root), ci };
}

// ── The five blocks ──────────────────────────────────────────────────────────

/** README §3: every ci.yml job, its `name:`, its own `needs`, whether it carries a
 *  job-level `if:`, and whether ci-gate needs it. ⏱ 2026-09-26 (CIMAP-8(a)): the
 *  `needs` and `if:` columns read the parse's `needs` and `jobIf`; `runs-on` is not a
 *  column, because the parse yields no `runs-on` field and a second reading of the
 *  key is the defect this file ends. */
export function renderLaneMap(tree) {
  const ci = tree.ci;
  const needs = new Set(ci.jobs.get(AGGREGATE_JOB).needs);
  const jobs = [...ci.jobs.values()];
  const gated = jobs.filter((j) => needs.has(j.name)).length;
  const out = [
    `\`ci.yml\` runs **${jobs.length}** jobs, and **${gated}** of them are in \`${AGGREGATE_JOB}\`'s \`needs\`.`,
    '',
    `| job | its \`name:\` | its \`needs\` | job-level \`if:\` | in \`${AGGREGATE_JOB}\`'s \`needs\` |`,
    '|---|---|---|---|---|',
  ];
  for (const j of jobs) {
    const inNeeds = j.name === AGGREGATE_JOB ? '— (the aggregate: the single required status check on `main`)' : needs.has(j.name) ? 'yes' : '**no**';
    const own = j.needs.length ? j.needs.map(code).join(', ') : '—';
    out.push(`| ${code(j.name)} | ${cell(j.displayName ?? '—')} | ${own} | ${j.jobIf ? 'yes' : '—'} | ${inNeeds} |`);
  }
  return out;
}

/** README §6: every secret name a workflow reads, and the workflows that read it. */
export function renderSecrets(tree) {
  const by = new Map();
  for (const wf of [...tree.workflows, ...tree.actions]) {
    for (const s of workflowSecrets(wf)) {
      if (s.name === ISSUED_TOKEN) continue;
      if (!by.has(s.name)) by.set(s.name, new Set());
      by.get(s.name).add(fileOf(wf.rel) === 'action.yml' || fileOf(wf.rel) === 'action.yaml' ? wf.rel : fileOf(wf.rel));
    }
  }
  const names = [...by.keys()].sort();
  const out = [
    `The workflows read **${names.length}** secret names (\`${ISSUED_TOKEN}\` is not counted: GitHub issues it to every run).`,
    '',
    '| secret | read by |',
    '|---|---|',
  ];
  for (const n of names) out.push(`| ${code(n)} | ${[...by.get(n)].sort().map(code).join(', ')} |`);
  return out;
}

/** README §7: every action a workflow or a composite action uses, by owner. */
export function renderActions(tree) {
  const by = new Map();
  for (const wf of [...tree.workflows, ...tree.actions]) {
    for (const u of workflowUses(wf)) {
      if (u.uses.startsWith('./') || u.uses.startsWith('docker://')) continue;
      const action = u.uses.replace(/@.*$/, '');
      if (!by.has(action)) by.set(action, new Set());
      by.get(action).add(wf.rel.startsWith(`${WORKFLOW_DIR}/`) ? fileOf(wf.rel) : wf.rel);
    }
  }
  const ownerOf = (a) => a.split('/')[0];
  const actions = [...by.keys()].sort((x, y) => {
    const gx = GITHUB_OWNERS.has(ownerOf(x)) ? 1 : 0;
    const gy = GITHUB_OWNERS.has(ownerOf(y)) ? 1 : 0;
    return gx - gy || x.localeCompare(y);
  });
  const third = actions.filter((a) => !GITHUB_OWNERS.has(ownerOf(a)));
  const out = [
    `The tree uses **${third.length}** third-party actions and **${actions.length - third.length}** GitHub-owned ones, read from every \`uses:\` in \`${WORKFLOW_DIR}\` and in the composite actions under \`.github/actions\`. Each third-party one runs only while the \`allowed_actions\` setting allows it: named on its allowlist, or published by a verified creator.`,
    '',
    '| action | owner | used by |',
    '|---|---|---|',
  ];
  for (const a of actions) {
    out.push(`| ${code(a)} | ${GITHUB_OWNERS.has(ownerOf(a)) ? 'GitHub' : 'third-party'} | ${[...by.get(a)].sort().map(code).join(', ')} |`);
  }
  return out;
}

/** The lane pages in docs/ci, as file names, README excluded. */
export function lanePages(root) {
  const dir = join(root, DOCS_CI);
  if (!existsSync(dir)) return [];
  return listDir(dir).filter((f) => f.endsWith('.md') && f !== 'README.md').sort();
}

/** README §9: one row per workflow, with its page, its `name:` and its triggers. */
export function renderWorkflows(tree, root) {
  const pages = new Set(lanePages(root));
  const out = [
    `**${tree.workflows.length}** workflows. A workflow's page is \`docs/ci/<workflow>.md\`; \`ci.yml\`'s is this one.`,
    '',
    '| page | workflow | its `name:` | triggers | jobs |',
    '|---|---|---|---|---|',
  ];
  const described = new Set();
  for (const wf of tree.workflows) {
    const file = fileOf(wf.rel);
    const page = file.replace(/\.ya?ml$/, '.md');
    described.add(page);
    const pageCell = wf.rel === CI_REL ? 'this page' : pages.has(page) ? `[${code(page)}](${page})` : 'none';
    const events = [...workflowEvents(wf)];
    out.push(`| ${pageCell} | ${code(wf.rel)} | ${cell(workflowName(wf) ?? '—')} | ${events.length ? events.map(code).join(', ') : '—'} | ${wf.jobs.size} |`);
  }
  for (const p of [...pages].filter((x) => !described.has(x))) {
    out.push(`| [${code(p)}](${p}) | none: no \`${WORKFLOW_DIR}/${p.replace(/\.md$/, '.yml')}\` | — | — | — |`);
  }
  return out;
}

/** RELEASE-RUNBOOK §2: every workflow a pushed tag starts, with its `tags:` list. */
export function renderTagTrigger(tree) {
  const tagged = tree.workflows.map((wf) => ({ wf, t: releaseTrigger(wf) })).filter((x) => x.t !== null);
  const out = [
    tagged.length === 0
      ? `No workflow in \`${WORKFLOW_DIR}/\` has an \`on: push: tags:\` trigger, so a pushed tag starts nothing.`
      : `**${tagged.length}** workflow(s) in \`${WORKFLOW_DIR}/\` have an \`on: push: tags:\` trigger, and a tag starts the one whose list it matches. Every other workflow has no tag trigger. Each list is itself generated from the product and channel registers by \`node tooling/ci/tag-owner.mjs --write\`.`,
  ];
  if (tagged.length) {
    out.push('', '| workflow | its `name:` | `tags:` |', '|---|---|---|');
    for (const { wf, t } of tagged) {
      out.push(`| ${code(wf.rel)} | ${cell(workflowName(wf) ?? '—')} | ${t.items.map((i) => code(i.pattern)).join(', ')} |`);
    }
  }
  return out;
}

export const BLOCKS = [
  { file: README_REL, name: 'lane-map', render: (tree) => renderLaneMap(tree) },
  { file: README_REL, name: 'secrets', render: (tree) => renderSecrets(tree) },
  { file: README_REL, name: 'actions', render: (tree) => renderActions(tree) },
  { file: README_REL, name: 'workflows', render: (tree, root) => renderWorkflows(tree, root) },
  { file: RUNBOOK_REL, name: 'tag-trigger', render: (tree) => renderTagTrigger(tree) },
];

// ── The three limbs ──────────────────────────────────────────────────────────

const finding = (at, what, fix) => ({ at, what, fix });
export const formatFinding = (f) => `${f.at} — ${f.what} — ${f.fix}`;

/** The workflow a lane page describes, or null. */
const workflowOfPage = (tree, page) => {
  const stem = page.replace(/\.md$/, '');
  return tree.workflows.find((w) => w.rel === `${WORKFLOW_DIR}/${stem}.yml` || w.rel === `${WORKFLOW_DIR}/${stem}.yaml`) ?? null;
};

/**
 * The workflows a lane page may describe: its own, then every workflow that one calls
 * by a local `uses: ./.github/workflows/<f>.yml`, read through workflow-scan's
 * `resolveLocalCalls` (never a second reader of `uses:`). `{ wf, workflows, refusal }`;
 * `wf` null when the page has no workflow of its name.
 *
 * ⏱ 2026-09-26 (CIMAP-4, option B): #922 moved extensions.yml's jobs into
 * extensions-ci.yml, which extensions.yml's `ci` job calls, and left their notes on
 * docs/ci/extensions.md, where they were measured. A caller's page may document its
 * callee's jobs; the set comes from the tree, not from a list. A refusal (a callee
 * that does not exist, or one that makes a local call itself) is COVERAGE LOST in
 * check(): limbs (a) and (b) would otherwise grade that page against part of what runs.
 */
export function pageWorkflows(tree, page) {
  const wf = workflowOfPage(tree, page);
  if (wf === null) return { wf: null, workflows: [], refusal: null };
  const { calls, refusal } = resolveLocalCalls(wf, tree.workflows);
  const workflows = [wf];
  for (const c of calls) if (!workflows.includes(c.callee)) workflows.push(c.callee);
  return { wf, workflows, refusal };
}

/** The COVERAGE LOST lines for every lane page whose workflow's local calls did not resolve. */
export function callRefusals(root, tree) {
  const out = [];
  for (const page of lanePages(root)) {
    const { wf, refusal } = pageWorkflows(tree, page);
    if (refusal) {
      out.push(`${DOCS_CI}/${page}: ${wf.rel}:${refusal.n} (job "${refusal.job}") calls ${refusal.callee}, and that call does not resolve (${refusal.kind}), so limbs (a) and (b) cannot read the workflows this page describes`);
    }
  }
  return out;
}

/** `wf.rel`, or `wf.rel` and the workflows it calls, for a finding's text. */
const describedBy = (workflows) =>
  workflows.length === 1 ? workflows[0].rel : `${workflows[0].rel} or a workflow it calls (${workflows.slice(1).map((w) => w.rel).join(', ')})`;

/** Limb (a): every `### above \`X\`` quotes a line its workflow, or a workflow it calls, still has. */
export function anchorFindings(root, tree) {
  const out = [];
  for (const page of lanePages(root)) {
    const rel = `${DOCS_CI}/${page}`;
    const { wf, workflows } = pageWorkflows(tree, page);
    const lines = readFileSync(join(root, rel), 'utf8').split('\n');
    lines.forEach((l, i) => {
      const m = l.match(/^### above `(.*)`\s*$/);
      if (!m) return;
      if (wf === null) {
        out.push(finding(`${rel}:${i + 1}`, `anchor ${code(m[1])} is on a page with no workflow of its name`, `move the note to the page of the workflow it describes, or delete it`));
        return;
      }
      // An anchor ending in `…` quotes the START of a long line, as the 2026-09-06
      // migration wrote it; the text before the `…` must be on a line.
      const quoted = m[1].endsWith('…') ? m[1].slice(0, -1) : m[1];
      if (quoted === '' || !workflows.some((w) => w.rawLines.some((r) => r.text.includes(quoted)))) {
        out.push(finding(`${rel}:${i + 1}`, `anchor ${code(m[1])} is on no line of ${describedBy(workflows)}`, 're-quote it to the line the note now sits above, or delete the heading and its note if that step is gone'));
      }
    });
  }
  return out;
}

/** Limb (b): a one-token `##` heading on a lane page names a job of its workflow, or of a workflow it calls. */
export function headingFindings(root, tree) {
  const out = [];
  for (const page of lanePages(root)) {
    const rel = `${DOCS_CI}/${page}`;
    const { wf, workflows } = pageWorkflows(tree, page);
    const lines = readFileSync(join(root, rel), 'utf8').split('\n');
    lines.forEach((l, i) => {
      const h = l.match(/^## (.+?)\s*$/);
      if (!h) return;
      const m = h[1].match(/^job `([^`]+)`$/) ?? h[1].match(/^`?([^\s`]+?)`?$/);
      if (!m) return;
      const id = m[1].replace(/:$/, '');
      if (wf !== null && workflows.some((w) => w.jobs.has(id))) return;
      out.push(
        finding(
          `${rel}:${i + 1}`,
          wf === null ? `heading "## ${h[1]}" names a job on a page with no workflow of its name` : `heading "## ${h[1]}" names ${code(id)}, which is not a job of ${describedBy(workflows)}`,
          'demote it to ### (it names a key inside a job, not a job), or rename it to the job it documents',
        ),
      );
    });
  }
  return out;
}

/** The pattern limb (c) refuses: a line number after a docs/ci page or the runbook. */
export const LINE_CITE = /(?:docs\/ci\/[A-Za-z0-9._-]+\.md|RELEASE-RUNBOOK\.md):[0-9]+/g;

/** Every tracked path, from `git ls-files`; null when git could not list them. */
export function trackedFiles(root) {
  // A hook exports GIT_DIR / GIT_INDEX_FILE for the repository it runs in; left
  // set, `git -C <root>` would list THAT index, not root's.
  const env = { ...process.env };
  for (const k of ['GIT_DIR', 'GIT_INDEX_FILE', 'GIT_WORK_TREE', 'GIT_PREFIX']) delete env[k];
  const r = spawnSync('git', ['-C', root, 'ls-files', '-z'], { encoding: 'utf8', env, maxBuffer: 64 * 1024 * 1024 });
  if (r.status !== 0) return null;
  return r.stdout.split('\0').filter(Boolean);
}

/** Limb (c): no tracked file outside docs/ cites a docs/ci page or the runbook by line. */
export function citationFindings(root, files) {
  const out = [];
  for (const rel of files) {
    if (rel.startsWith('docs/')) continue;
    const abs = join(root, rel);
    if (!existsSync(abs)) continue;
    const buf = readFileSync(abs);
    if (buf.length > 8 * 1024 * 1024 || buf.subarray(0, 8000).includes(0)) continue;
    const lines = buf.toString('utf8').split('\n');
    lines.forEach((l, i) => {
      for (const m of l.matchAll(LINE_CITE)) {
        out.push(finding(`${rel}:${i + 1}`, `cites ${code(m[0])} by line number, and every edit above that line moves it`, 'cite the section instead: `docs/ci/<page>.md §<heading text>`, `docs/ci/<page>.md, job <id>`, or the runbook\'s `##` section title'));
      }
    });
  }
  return out;
}

// ── The run ──────────────────────────────────────────────────────────────────

/**
 * Everything --check decides, pure over `root`:
 * `{ lost: string[], findings: {at, what, fix}[], counts: { blocks, a, b, c } }`.
 */
export function check(root) {
  const tree = readTree(root);
  const lost = [...tree.lost];
  const findings = [];
  const counts = { blocks: 0, a: 0, b: 0, c: 0 };
  if (lost.length === 0) {
    for (const blk of BLOCKS) {
      const abs = join(root, blk.file);
      const text = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
      const same = text === null ? null : blockMatches(text, TOOL, blk.name, COMMAND, blk.render(tree, root));
      if (same === null) {
        lost.push(`${blk.file} has no complete \`${blk.name}\` block (${text === null ? 'the file does not exist' : findBlock(text, TOOL, blk.name).why})`);
      } else if (!same) {
        const at = findBlock(text, TOOL, blk.name).begin + 1;
        findings.push(finding(`${blk.file}:${at}`, `the \`${blk.name}\` block is not what the workflows say`, `run \`${COMMAND} --write\` and commit what it writes`));
        counts.blocks += 1;
      }
    }
    if (lanePages(root).length === 0) lost.push(`${DOCS_CI} holds no lane page, so limbs (a) and (b) would read nothing`);
    lost.push(...callRefusals(root, tree));
    const a = anchorFindings(root, tree);
    const b = headingFindings(root, tree);
    const files = trackedFiles(root);
    if (files === null || files.length === 0) {
      lost.push(`\`git ls-files\` listed nothing under ${root}, so no citation was read (limb c)`);
    }
    const c = files ? citationFindings(root, files) : [];
    counts.a = a.length;
    counts.b = b.length;
    counts.c = c.length;
    findings.push(...a, ...b, ...c);
  }
  return { lost, findings, counts, tree };
}

/** Writes every block. `{ lost, wrote }`; nothing is written while anything is lost. */
export function write(root) {
  const tree = readTree(root);
  const lost = [...tree.lost];
  const next = new Map();
  if (lost.length === 0) {
    for (const blk of BLOCKS) {
      const abs = join(root, blk.file);
      const text = next.get(blk.file) ?? (existsSync(abs) ? readFileSync(abs, 'utf8') : null);
      const spliced = text === null ? null : spliceBlock(text, TOOL, blk.name, COMMAND, blk.render(tree, root));
      if (spliced === null) {
        lost.push(`${blk.file} has no complete \`${blk.name}\` block to write into (${text === null ? 'the file does not exist' : findBlock(text, TOOL, blk.name).why})`);
        continue;
      }
      next.set(blk.file, spliced);
    }
  }
  if (lost.length) return { lost, wrote: [] };
  for (const [rel, text] of next) writeFileSync(join(root, rel), text);
  return { lost, wrote: [...next.keys()] };
}

/** The COVERAGE LOST stop: every reason, then exit 2. */
function coverageLost(lines) {
  for (const l of lines) console.error(`COVERAGE LOST — gen-ci-map: ${l}`);
  process.exitCode = 2;
}

function main(argv) {
  const positional = argv.filter((a) => !a.startsWith('--'));
  const here = dirname(fileURLToPath(import.meta.url));
  const root = resolve(positional[0] ?? join(here, '..', '..'));

  if (argv.includes('--write')) {
    const r = write(root);
    if (r.lost.length) {
      coverageLost(r.lost);
      return;
    }
    console.log(`wrote ${BLOCKS.length} block(s) into ${r.wrote.join(', ')}`);
    return;
  }

  const r = check(root);
  if (r.lost.length) {
    coverageLost(r.lost);
    return;
  }
  if (r.findings.length) {
    for (const f of r.findings) console.error(formatFinding(f));
    console.error(
      `✗ gen-ci-map: ${r.findings.length} finding(s) — blocks ${r.counts.blocks}, limb (a) anchors ${r.counts.a}, limb (b) headings ${r.counts.b}, limb (c) line citations ${r.counts.c}`,
    );
    process.exitCode = 1;
    return;
  }
  console.log(
    `✓ gen-ci-map: ${BLOCKS.length} block(s) match ${r.tree.workflows.length} workflow(s); every lane-page anchor and job heading resolves; no tracked file outside docs/ cites a doc line by number`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  main(process.argv.slice(2));
}
